force-app/main/default/objects/Account_Budget_Detail__c/Account_Budget_Detail__c.object-meta.xml
<CustomObject>
    <label>Account Budget Detail</label>
    <nameField>
        <label>Account Budget Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Budget Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_10__c.field-meta.xml
<CustomField>
    <fullName>Column_10__c</fullName>
    <label>Column 10</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_11__c.field-meta.xml
<CustomField>
    <fullName>Column_11__c</fullName>
    <label>Column 11</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_12__c.field-meta.xml
<CustomField>
    <fullName>Column_12__c</fullName>
    <label>Column 12</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_13__c.field-meta.xml
<CustomField>
    <fullName>Column_13__c</fullName>
    <label>Column 13</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_14__c.field-meta.xml
<CustomField>
    <fullName>Column_14__c</fullName>
    <label>Column 14</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_15__c.field-meta.xml
<CustomField>
    <fullName>Column_15__c</fullName>
    <label>Column 15</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_16__c.field-meta.xml
<CustomField>
    <fullName>Column_16__c</fullName>
    <label>Column 16</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_17__c.field-meta.xml
<CustomField>
    <fullName>Column_17__c</fullName>
    <label>Column 17</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_18__c.field-meta.xml
<CustomField>
    <fullName>Column_18__c</fullName>
    <label>Column 18</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_19__c.field-meta.xml
<CustomField>
    <fullName>Column_19__c</fullName>
    <label>Column 19</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_1__c.field-meta.xml
<CustomField>
    <fullName>Column_1__c</fullName>
    <label>Column 1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_20__c.field-meta.xml
<CustomField>
    <fullName>Column_20__c</fullName>
    <label>Column 20</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_21__c.field-meta.xml
<CustomField>
    <fullName>Column_21__c</fullName>
    <label>Column 21</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_22__c.field-meta.xml
<CustomField>
    <fullName>Column_22__c</fullName>
    <label>Column 22</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_23__c.field-meta.xml
<CustomField>
    <fullName>Column_23__c</fullName>
    <label>Column 23</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_24__c.field-meta.xml
<CustomField>
    <fullName>Column_24__c</fullName>
    <label>Column 24</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_25__c.field-meta.xml
<CustomField>
    <fullName>Column_25__c</fullName>
    <label>Column 25</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_26__c.field-meta.xml
<CustomField>
    <fullName>Column_26__c</fullName>
    <label>Column 26</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_27__c.field-meta.xml
<CustomField>
    <fullName>Column_27__c</fullName>
    <label>Column 27</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_28__c.field-meta.xml
<CustomField>
    <fullName>Column_28__c</fullName>
    <label>Column 28</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_29__c.field-meta.xml
<CustomField>
    <fullName>Column_29__c</fullName>
    <label>Column 29</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_2__c.field-meta.xml
<CustomField>
    <fullName>Column_2__c</fullName>
    <label>Column 2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_30__c.field-meta.xml
<CustomField>
    <fullName>Column_30__c</fullName>
    <label>Column 30</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_31__c.field-meta.xml
<CustomField>
    <fullName>Column_31__c</fullName>
    <label>Column 31</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_32__c.field-meta.xml
<CustomField>
    <fullName>Column_32__c</fullName>
    <label>Column 32</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_33__c.field-meta.xml
<CustomField>
    <fullName>Column_33__c</fullName>
    <label>Column 33</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_34__c.field-meta.xml
<CustomField>
    <fullName>Column_34__c</fullName>
    <label>Column 34</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_35__c.field-meta.xml
<CustomField>
    <fullName>Column_35__c</fullName>
    <label>Column 35</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_36__c.field-meta.xml
<CustomField>
    <fullName>Column_36__c</fullName>
    <label>Column 36</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_37__c.field-meta.xml
<CustomField>
    <fullName>Column_37__c</fullName>
    <label>Column 37</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_38__c.field-meta.xml
<CustomField>
    <fullName>Column_38__c</fullName>
    <label>Column 38</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_39__c.field-meta.xml
<CustomField>
    <fullName>Column_39__c</fullName>
    <label>Column 39</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_3__c.field-meta.xml
<CustomField>
    <fullName>Column_3__c</fullName>
    <label>Column 3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_40__c.field-meta.xml
<CustomField>
    <fullName>Column_40__c</fullName>
    <label>Column 40</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_41__c.field-meta.xml
<CustomField>
    <fullName>Column_41__c</fullName>
    <label>Column 41</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_42__c.field-meta.xml
<CustomField>
    <fullName>Column_42__c</fullName>
    <label>Column 42</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_43__c.field-meta.xml
<CustomField>
    <fullName>Column_43__c</fullName>
    <label>Column 43</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_44__c.field-meta.xml
<CustomField>
    <fullName>Column_44__c</fullName>
    <label>Column 44</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_45__c.field-meta.xml
<CustomField>
    <fullName>Column_45__c</fullName>
    <label>Column 45</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_4__c.field-meta.xml
<CustomField>
    <fullName>Column_4__c</fullName>
    <label>Column 4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_5__c.field-meta.xml
<CustomField>
    <fullName>Column_5__c</fullName>
    <label>Column 5</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_6__c.field-meta.xml
<CustomField>
    <fullName>Column_6__c</fullName>
    <label>Column 6</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_7__c.field-meta.xml
<CustomField>
    <fullName>Column_7__c</fullName>
    <label>Column 7</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_8__c.field-meta.xml
<CustomField>
    <fullName>Column_8__c</fullName>
    <label>Column 8</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_9__c.field-meta.xml
<CustomField>
    <fullName>Column_9__c</fullName>
    <label>Column 9</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Expense_Detail__c/Account_Expense_Detail__c.object-meta.xml
<CustomObject>
    <label>Account Expense Detail</label>
    <nameField>
        <label>Account Expense Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Expense Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Expense_Detail__c/fields/Account_Budget_Detail__c.field-meta.xml
<CustomField>
    <fullName>Account_Budget_Detail__c</fullName>
    <label>Account Budget</label>
    <referenceTo>Account_Budget_Detail__c</referenceTo>
    <relationshipLabel>Account Expense Details</relationshipLabel>
    <relationshipName>Account_Expense_Details</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Conf_Category__c/Conf_Category__c.object-meta.xml
<CustomObject>
    <label>Configuration Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conf_Category__c/fields/Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Category_Type__c</fullName>
    <label>Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Conf_Category__c/fields/Column_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Name__c</fullName>
    <label>Column Name</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/Configuration_Category_Detail__c.object-meta.xml
<CustomObject>
    <label>Configuration Category Detail</label>
    <nameField>
        <label>Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Category Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Column_Name_2__c.field-meta.xml
<CustomField>
    <fullName>Column_Name_2__c</fullName>
    <label>Column Name 2</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Column_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Name__c</fullName>
    <label>Column Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Configuration_Category__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Category__c</fullName>
    <label>Configuration Category</label>
    <referenceTo>Conf_Category__c</referenceTo>
    <relationshipName>Category_Configuration_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Category_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Health</fullName>
    </customValue>
    <customValue>
        <fullName>Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Company Division</fullName>
    </customValue>
    <customValue>
        <fullName>Relationship Type</fullName>
    </customValue>
    <customValue>
        <fullName>Program Milestone</fullName>
    </customValue>
    <customValue>
        <fullName>Stakeholder Personality</fullName>
    </customValue>
    <customValue>
        <fullName>Budget</fullName>
    </customValue>
    <customValue>
        <fullName>Soft Credit Role</fullName>
    </customValue>
    <customValue>
        <fullName>Target</fullName>
    </customValue>
    <customValue>
        <fullName>Company Offerings</fullName>
    </customValue>
    <customValue>
        <fullName>Credit</fullName>
    </customValue>
    <customValue>
        <fullName>Tab Visibility</fullName>
    </customValue>
    <customValue>
        <fullName>Account Insight</fullName>
    </customValue>
    <customValue>
        <fullName>Bbbb</fullName>
        <isActive>false</isActive>
        <label>Bbbb</label>
    </customValue>
    <customValue>
        <fullName>Aaaa</fullName>
        <isActive>false</isActive>
        <label>Aaaa</label>
    </customValue>
    <description>Category Type Picklist values for Conf_Category_Name Object.</description>
    <masterLabel>Category Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Account_Budget_Helper.cls
public with sharing class Account_Budget_Helper {
    @AuraEnabled(cacheable=true)
    public static List<Account_Budget_Detail__c> getAccountBudget(Id recId){
        List<Account_Budget_Detail__c> accountBudgets;
        try{
            accountBudgets = [SELECT Id,Name,varasi_am__Budget_Amount_3__c,varasi_am__Year__c,varasi_am__Total_Expenses__c FROM Account_Budget_Detail__c where Id=:recId WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        return accountBudgets;
    }

    @AuraEnabled(cacheable=true)
    public static Map<String,List<Configuration_Category_Detail__c>> getConfigData(){
        List<Conf_Category__c> conf;
        try{
            conf = [Select Id,Name,(Select Id,Column_Name__c,Column_Name_2__c,Configuration_Category__c,Name FROM Category_Configuration_Details__r) FROM Conf_Category__c WHERE Category_Type__c='Budget' WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        Map<String,List<Configuration_Category_Detail__c>> configMap = new Map<String,List<Configuration_Category_Detail__c>>();
        for(Conf_Category__c c:conf){
        	configMap.put(c.Name,c.Category_Configuration_Details__r);
        }
        return configMap;
    }

    @AuraEnabled(cacheable=true)
    public static List<budgetWrapper> getAcctBudgetRecs(String acctId){
        List<Account_Budget_Detail__c> acctBudgetList;
        List<Conf_Category__c> categs;
        try{
            acctBudgetList =
            [Select Id,Name,varasi_am__Total_Expenses__c,Column_1__c,Column_2__c,Column_3__c,Column_4__c,Column_5__c,Column_6__c,Column_7__c,Column_8__c,Column_9__c,Column_10__c,
                                                Column_11__c,Column_12__c,Column_13__c,Column_14__c,Column_15__c,Column_16__c,Column_17__c,Column_18__c,Column_19__c,
                                                Column_20__c,Column_21__c,Column_22__c,Column_23__c,Column_24__c,Column_25__c,Column_26__c,Column_27__c,Column_28__c,Column_29__c,
                                                Column_30__c,Column_31__c,Column_32__c,Column_33__c,Column_34__c,Column_35__c,Column_36__c,Column_37__c,Column_38__c,Column_39__c,
                                                Column_40__c,Column_41__c,Column_42__c,Column_43__c,Column_44__c,Column_45__c,Column_46__c,Column_47__c,Column_48__c,Column_49__c,Column_50__c
                                                from Account_Budget_Detail__c WHERE Account__c=:acctId WITH SECURITY_ENFORCED];
            categs = [Select Id,Name,Category_Type__c,(Select id,name,Column_Name__c from Category_Configuration_Details__r) FROM Conf_Category__c WHERE Category_Type__c='Budget' WITH SECURITY_ENFORCED];
        }
         catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
         List<budgetWrapper> budgetList = new List<budgetWrapper>();
         for(Account_Budget_Detail__c bud:acctBudgetList){
            budgetWrapper budget = new budgetWrapper();
            budget.Id=bud.Id;
            budget.Name=bud.Name;
            budget.expense=bud.varasi_am__Total_Expenses__c;
            Double categTotal=0.00;
            for(Conf_Category__c categ:categs){
                for(Configuration_Category_Detail__c detail: categ.Category_Configuration_Details__r){
                    categTotal+=bud.get(detail.Column_Name__c) == null ? 0 : Double.valueOf(bud.get(detail.Column_Name__c));
                }
            }
            budget.budget=categTotal;
            budgetList.add(budget);
         }
         return budgetList;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<categWrapper> getConfigData2(String recordId){
        Account_Budget_Detail__c budgetRec;
        List<Conf_Category__c> categs;
        try{
            budgetRec = [Select id,name,Column_1__c,Column_2__c,Column_3__c,Column_4__c,Column_5__c,Column_6__c,Column_7__c,Column_8__c,Column_9__c,Column_10__c,
                                                Column_11__c,Column_12__c,Column_13__c,Column_14__c,Column_15__c,Column_16__c,Column_17__c,Column_18__c,Column_19__c,
                                                Column_20__c,Column_21__c,Column_22__c,Column_23__c,Column_24__c,Column_25__c,Column_26__c,Column_27__c,Column_28__c,Column_29__c,
                                                Column_30__c,Column_31__c,Column_32__c,Column_33__c,Column_34__c,Column_35__c,Column_36__c,Column_37__c,Column_38__c,Column_39__c,
                                                Column_40__c,Column_41__c,Column_42__c,Column_43__c,Column_44__c,Column_45__c,Column_46__c,Column_47__c,Column_48__c,Column_49__c,Column_50__c,
                                                (Select id,name,Account__c,Account_Budget_Detail__c,Budget_Sub_Category__c,varasi_am__Budget_Category__r.Name,
                                                Expense_Amount__c,Expense_Date__c 
                                                from Account_Expense_Details__r)from Account_Budget_Detail__c
                                                where id=:recordId WITH SECURITY_ENFORCED];
            categs = [Select Id,Name,Category_Type__c,(Select id,name,Column_Name__c from Category_Configuration_Details__r) FROM Conf_Category__c WHERE Category_Type__c='Budget' WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        List<categWrapper> categList= new List<categWrapper>();
        for(Conf_Category__c categ:categs){
            categWrapper c =new categWrapper();
            c.Id=categ.Id;
            c.name=categ.name;
            List<subCategWrapper> subCategList= new List<subCategWrapper>();
            Double categTotal=0.00;
            Double expenseTotal=0.00;
            for(Configuration_Category_Detail__c detail: categ.Category_Configuration_Details__r){
                subCategWrapper s=new subCategWrapper();
                //System.debug(detail);
                s.Id=detail.id;
                s.name=detail.name;
                s.colName=detail.Column_Name__c;
                categTotal+=budgetRec.get(detail.Column_Name__c) == null ? 0 : Double.valueOf(budgetRec.get(detail.Column_Name__c));
                for(Account_Expense_Detail__c expense: budgetRec.Account_Expense_Details__r){
                    //System.debug(expense);
                    if(expense.Budget_Sub_Category__c == detail.id){
                        //System.debug(expense.Expense_Amount__c);
                        s.expense=expense.Expense_Amount__c;
                        expenseTotal+=expense.Expense_Amount__c;
                    }
                }
                subCategList.add(s);
            }
            c.expenseTotal=expenseTotal;
            c.categTotalBudget=categTotal;
            c.subCategs=subCategList;
            categList.add(c);
        }
        return categList;
    }
    public class categWrapper{
        @AuraEnabled
        public  string Id {get;set;}
        @AuraEnabled
        public  string name {get;set;}
        @AuraEnabled
        public  Double expenseTotal {get;set;}
        @AuraEnabled
        public  Double categTotalBudget {get;set;}
        @AuraEnabled
        public  List<subCategWrapper> subCategs {get;set;}
    }
    public class subCategWrapper{
        @AuraEnabled
        public string Id {get;set;}
        @AuraEnabled
        public string colName {get;set;}
        @AuraEnabled
        public string name {get;set;}
        @AuraEnabled
        public Double expense {get;set;}
    }

    public class budgetWrapper{
        @AuraEnabled
        public string Id {get;set;}
        @AuraEnabled
        public string Name {get;set;}
        @AuraEnabled
        public Decimal budget {get;set;}
        @AuraEnabled
        public Decimal expense {get;set;}
    }
}