force-app/main/default/objects/Account_Budget_Detail__c/Account_Budget_Detail__c.object-meta.xml
<CustomObject>
    <label>Account Budget Detail</label>
    <nameField>
        <label>Account Budget Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Budget Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Budget Details</relationshipLabel>
    <relationshipName>Account_Budget_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_1__c.field-meta.xml
<CustomField>
    <fullName>Column_1__c</fullName>
    <label>Column 1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_2__c.field-meta.xml
<CustomField>
    <fullName>Column_2__c</fullName>
    <label>Column 2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Expense_Detail__c/Account_Expense_Detail__c.object-meta.xml
<CustomObject>
    <label>Account Expense Detail</label>
    <nameField>
        <label>Account Expense Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Expense Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Expense_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Expense Details</relationshipLabel>
    <relationshipName>Account_Expense_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Expense_Detail__c/fields/Account_Budget_Detail__c.field-meta.xml
<CustomField>
    <fullName>Account_Budget_Detail__c</fullName>
    <label>Account Budget</label>
    <referenceTo>Account_Budget_Detail__c</referenceTo>
    <relationshipLabel>Account Expense Details</relationshipLabel>
    <relationshipName>Account_Expense_Details</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Expense_Detail__c/fields/Budget_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Budget_Sub_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Budget Sub Category</label>
    <referenceTo>Configuration_Category_Detail__c</referenceTo>
    <relationshipLabel>Account Expense Details</relationshipLabel>
    <relationshipName>Account_Expense_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Expense_Detail__c/fields/Expense_Amount__c.field-meta.xml
<CustomField>
    <fullName>Expense_Amount__c</fullName>
    <label>Expense Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Conf_Category__c/Conf_Category__c.object-meta.xml
<CustomObject>
    <label>Configuration Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conf_Category__c/fields/Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Category_Type__c</fullName>
    <label>Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Conf_Category__c/fields/Column_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Name__c</fullName>
    <label>Column Name</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/Configuration_Category_Detail__c.object-meta.xml
<CustomObject>
    <label>Configuration Category Detail</label>
    <nameField>
        <label>Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Category Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Column_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Name__c</fullName>
    <label>Column Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Configuration_Category__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Category__c</fullName>
    <label>Configuration Category</label>
    <referenceTo>Conf_Category__c</referenceTo>
    <relationshipName>Category_Configuration_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <label>Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Chatter_Feed__c.field-meta.xml
<CustomField>
    <fullName>Chatter_Feed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Post to Chatter Feed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Criteria_Value__c.field-meta.xml
<CustomField>
    <fullName>Criteria_Value__c</fullName>
    <label>Criteria Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Notification_Type__c.field-meta.xml
<CustomField>
    <fullName>Notification_Type__c</fullName>
    <label>Notification Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>=</fullName>
            </value>
            <value>
                <fullName>!=</fullName>
            </value>
            <value>
                <fullName>&lt;</fullName>
            </value>
            <value>
                <fullName>&gt;</fullName>
            </value>
            <value>
                <fullName>&lt;=</fullName>
            </value>
            <value>
                <fullName>&gt;=</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Category_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Health</fullName>
    </customValue>
    <customValue>
        <fullName>Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Company Division</fullName>
    </customValue>
    <customValue>
        <fullName>Relationship Type</fullName>
    </customValue>
    <customValue>
        <fullName>Program Milestone</fullName>
    </customValue>
    <customValue>
        <fullName>Stakeholder Personality</fullName>
    </customValue>
    <customValue>
        <fullName>Budget</fullName>
    </customValue>
    <customValue>
        <fullName>Soft Credit Role</fullName>
    </customValue>
    <customValue>
        <fullName>Target</fullName>
    </customValue>
    <customValue>
        <fullName>Company Offerings</fullName>
    </customValue>
    <customValue>
        <fullName>Credit</fullName>
    </customValue>
    <customValue>
        <fullName>Tab Visibility</fullName>
    </customValue>
    <customValue>
        <fullName>Account Insight</fullName>
    </customValue>
    <customValue>
        <fullName>Bbbb</fullName>
        <isActive>false</isActive>
        <label>Bbbb</label>
    </customValue>
    <customValue>
        <fullName>Aaaa</fullName>
        <isActive>false</isActive>
        <label>Aaaa</label>
    </customValue>
    <description>Category Type Picklist values for Conf_Category_Name Object.</description>
    <masterLabel>Category Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Account_Budget_Helper_Test.cls
@isTest
public class Account_Budget_Helper_Test {
	
    @testSetup
    public static void DataSet(){
        Profile p2 = [SELECT Id FROM Profile WHERE Name='Solution Manager']; 
  		User u2 = new User(Alias = 'solUser', Email='testsoltionManUser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='SolManager', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p2.Id, 
        TimeZoneSidKey='America/Los_Angeles', UserName='testuserVarasi@testorg.com');
        insert u2;
        Account accnt=new Account(Name='New Account');
        insert accnt;
        Conf_Category__c config = new Conf_Category__c(Name='New Budget',Category_Type__c='Budget');
        insert config;
        Configuration_Category_Detail__c cDetail = new Configuration_Category_Detail__c(Column_Name__c='Column_1__c',Configuration_Category__c=config.Id);
        insert cDetail;
        Configuration_Category_Detail__c cDetail2 = new Configuration_Category_Detail__c(Column_Name__c='Column_2__c',Configuration_Category__c=config.Id);
        insert cDetail2;
        Account_Budget_Detail__c budget =  new Account_Budget_Detail__c(Name='New Budget',Account__c=accnt.Id);
        insert budget;  
        Account_Expense_Detail__c expense = new Account_Expense_Detail__c(Expense_Amount__c=800,Account_Budget_Detail__c=budget.Id,Account__c=accnt.Id,Budget_Sub_Category__c=cDetail.Id);
        insert expense;
        //Notification__c n = new Notification__c(Account__c=accnt.Id,Criteria_Value__c='3',Operator__c='<',Notification_Type__c='Big Expense',Chatter_Feed__c=true);
        //insert n;
    }
    
    static testMethod void getAccountBudgetTest(){
        Account_Budget_Detail__c budget = [Select Id,Name from Account_Budget_Detail__c where Name='New Budget'WITH SECURITY_ENFORCED];
        List<Account_Budget_Detail__c> budgets = Account_Budget_Helper.getAccountBudget(budget.Id);
       	System.assertEquals(budget.Name,budgets.get(0).Name);
    }
    
    static testMethod void getAccountBudgetExceptionTest(){
    	User solManUser = [SELECT id FROM User WHERE Email='testsoltionManUser@testorg.com'];
        Account_Budget_Detail__c budget = [Select Id,Name from Account_Budget_Detail__c where Name='New Budget'WITH SECURITY_ENFORCED];
		System.runAs(solManUser) 
        { 		
			Test.startTest();
			try{
				List<Account_Budget_Detail__c> budgets = Account_Budget_Helper.getAccountBudget(budget.Id);
			}
			catch(Exception e){
				System.assertEquals(true,e.getMessage().contains('Error')||e.getMessage().contains('exception'));  
			}
			Test.stopTest();
        }
    }

    
    static testMethod void getAccountBudgetRecsTest(){
        Account acc=[Select Id,Name from Account where Name='New Account' WITH SECURITY_ENFORCED];
        LIst<Account_Budget_Detail__c> budgetDetail=[select id,name,Account__c from Account_Budget_Detail__c where Account__c=:acc.Id WITH SECURITY_ENFORCED];
        User solManUser = [SELECT id FROM User WHERE Email='testsoltionManUser@testorg.com'];
		System.runAs(solManUser) 
        {
            Test.startTest();
			try{
				List<Account_Budget_Helper.budgetWrapper> budgets = Account_Budget_Helper.getAcctBudgetRecs(acc.Id);
			}
			catch(Exception e){
				System.assertEquals(true,e.getMessage().contains('Error')||e.getMessage().contains('exception'));  
			}
			Test.stopTest();
        }
    }
    
    static testMethod void getAccountBudgetRecsExceptionTest(){
        Account acc=[Select Id,Name from Account where Name='New Account' WITH SECURITY_ENFORCED];
        LIst<Account_Budget_Detail__c> budgetDetail=[select id,name,Account__c from Account_Budget_Detail__c where Account__c=:acc.Id WITH SECURITY_ENFORCED];
        User solManUser = [SELECT id FROM User WHERE Email='testsoltionManUser@testorg.com'];
		System.runAs(solManUser) 
        {
            Test.startTest();
			try{
				List<Account_Budget_Helper.budgetWrapper> budgets = Account_Budget_Helper.getAcctBudgetRecs(acc.Id);
			}
			catch(Exception e){
				System.assertEquals(true,e.getMessage().contains('Error')||e.getMessage().contains('exception'));  
			}
			Test.stopTest();
        }
    }
    
    static testMethod void getConfigDataTest(){
        User solManUser = [SELECT id FROM User WHERE Email='testsoltionManUser@testorg.com'];
		System.runAs(solManUser) 
        {
            Test.startTest();
			try{
				Map<String,List<Configuration_Category_Detail__c>> configMap = Account_Budget_Helper.getConfigData();
			}
			catch(Exception e){
				System.assertEquals(true,e.getMessage().contains('Error')||e.getMessage().contains('exception'));  
			}
			Test.stopTest();
        }
    }
    
    static testMethod void getConfigDataExceptionTest(){
        User solManUser = [SELECT id FROM User WHERE Email='testsoltionManUser@testorg.com'];
		System.runAs(solManUser) 
        {
            Test.startTest();
			try{
				Map<String,List<Configuration_Category_Detail__c>> configMap = Account_Budget_Helper.getConfigData();
			}
			catch(Exception e){
				System.assertEquals(true,e.getMessage().contains('Error')||e.getMessage().contains('exception'));  
			}
			Test.stopTest();
        }
    }
    
    static testMethod void getConfigData2ExceptionTest(){
        Account_Budget_Detail__c budget;
        try{
            budget = [Select Id,Name from Account_Budget_Detail__c where Name='New Budget' WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        User solManUser = [SELECT id FROM User WHERE Email='testsoltionManUser@testorg.com'];
		System.runAs(solManUser) 
        {
            Test.startTest();
			try{
				List<Account_Budget_Helper.categWrapper> listCateg = Account_Budget_Helper.getConfigData2(budget.Id);
			}
			catch(Exception e){
				System.assertEquals(true,e.getMessage().contains('Error')||e.getMessage().contains('exception'));  
			}
			Test.stopTest();
        }
    }
    
    static testMethod void getConfigData2Test(){
        Account_Budget_Detail__c budget;
        try{
            budget = [Select Id,Name from Account_Budget_Detail__c where Name='New Budget' WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        List<Account_Budget_Helper.categWrapper> listCateg = Account_Budget_Helper.getConfigData2(budget.Id);
        System.assertEquals(1, listCateg.size());
    }
    
    
    @isTest static void getExpenseNotificationDataTest(){
        Account_Budget_Detail__c budget;
        try{
            budget = [Select Id,Name from Account_Budget_Detail__c where Name='New Budget' WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        List<notification__c> notifData = notification.getExpenseNotificationData(budget.Id);
        System.assert(notifData.size()>0);
    }
    
    @isTest static void getExpenseNotificationDataExceptionTest(){
        Account_Budget_Detail__c budget;
        try{
            budget = [Select Id,Name from Account_Budget_Detail__c where Name='New Budget' WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        User solManUser = [SELECT id FROM User WHERE Email='testsoltionManUser@testorg.com'];
		System.runAs(solManUser) 
        {
            Test.startTest();
			try{
				List<notification__c> notifData = notification.getExpenseNotificationData(budget.Id);
			}
			catch(Exception e){
				System.assertEquals(true,e.getMessage().contains('Error')||e.getMessage().contains('exception'));  
			}
			Test.stopTest();
        }
    }
}