force-app/main/default/objects/Account_Budget_Detail__c/Account_Budget_Detail__c.object-meta.xml
<CustomObject>
    <label>Account Budget Detail</label>
    <nameField>
        <label>Account Budget Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Budget Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Budget Details</relationshipLabel>
    <relationshipName>Account_Budget_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Budget_Allotted__c.field-meta.xml
<CustomField>
    <fullName>Budget_Allotted__c</fullName>
    <label>Budget Allotted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Total_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Total_Expenses__c</fullName>
    <label>Budget Used</label>
    <summarizedField>Account_Expense_Detail__c.Expense_Amount__c</summarizedField>
    <summaryForeignKey>Account_Expense_Detail__c.Account_Budget_Detail__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/Account_Checklist__c.object-meta.xml
<CustomObject>
    <label>Account Checklist</label>
    <nameField>
        <label>Account Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Checklist__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Checklists</relationshipLabel>
    <relationshipName>Account_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Configuration_Category__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Checklist Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Conf_Category__c.Category_Type__c</field>
            <operation>equals</operation>
            <value>Checklist</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Conf_Category__c</referenceTo>
    <relationshipLabel>Account Checklists</relationshipLabel>
    <relationshipName>Account_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Expense_Detail__c/Account_Expense_Detail__c.object-meta.xml
<CustomObject>
    <label>Account Expense Detail</label>
    <nameField>
        <label>Account Expense Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Expense Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Expense_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Expense Details</relationshipLabel>
    <relationshipName>Account_Expense_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Expense_Detail__c/fields/Account_Budget_Detail__c.field-meta.xml
<CustomField>
    <fullName>Account_Budget_Detail__c</fullName>
    <label>Account Budget</label>
    <referenceTo>Account_Budget_Detail__c</referenceTo>
    <relationshipLabel>Account Expense Details</relationshipLabel>
    <relationshipName>Account_Expense_Details</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Expense_Detail__c/fields/Budget_Category__c.field-meta.xml
<CustomField>
    <fullName>Budget_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Budget Category</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Conf_Category__c.Category_Type__c</field>
            <operation>equals</operation>
            <value>Budget</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Conf_Category__c</referenceTo>
    <relationshipLabel>Account Expense Details</relationshipLabel>
    <relationshipName>Account_Expense_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Expense_Detail__c/fields/Expense_Amount__c.field-meta.xml
<CustomField>
    <fullName>Expense_Amount__c</fullName>
    <label>Expense Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Expense_Detail__c/fields/Expense_Date__c.field-meta.xml
<CustomField>
    <fullName>Expense_Date__c</fullName>
    <label>Expense Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Health_Metrics__c/Account_Health_Metrics__c.object-meta.xml
<CustomObject>
    <label>Account Health Metrics</label>
    <nameField>
        <displayFormat>AHM-{0000}</displayFormat>
        <label>Account Health Metrics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Health Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Health_Metrics__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Health Metrics</relationshipLabel>
    <relationshipName>Account_Health_Metrics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Health_Metrics__c/fields/Average_Health_Score__c.field-meta.xml
<CustomField>
    <fullName>Average_Health_Score__c</fullName>
    <label>Average Health Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Health_Metrics__c/fields/Health_Score_Date__c.field-meta.xml
<CustomField>
    <fullName>Health_Score_Date__c</fullName>
    <label>Health Score Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Health_Metrics__c/fields/Score_Month__c.field-meta.xml
<CustomField>
    <fullName>Score_Month__c</fullName>
    <formula>CASE(Month(Health_Score_Date__c),
							1, &apos;January&apos;,
							2, &apos;February&apos;,
							3, &apos;March&apos;,
							4, &apos;April&apos;,
							5, &apos;May&apos;,
							6, &apos;June&apos;,
							7, &apos;July&apos;,
							8, &apos;August&apos;,
							9, &apos;September&apos;,
							10, &apos;October&apos;,
							11, &apos;November&apos;,
							12, &apos;December&apos;,
					&apos;&apos;
							)</formula>
    <label>Score Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Health_Metrics__c/fields/Score_Year__c.field-meta.xml
<CustomField>
    <fullName>Score_Year__c</fullName>
    <formula>TEXT( YEAR(Health_Score_Date__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Score Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Review__c/Business_Review__c.object-meta.xml
<CustomObject>
    <label>Business Review</label>
    <nameField>
        <label>Business Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Review__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Reviews</relationshipLabel>
    <relationshipName>Business_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Review__c/fields/Bussiness_Review_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Bussiness_Review_Assessment__c</fullName>
    <label>Business Review Assessment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Positive</fullName>
                <label>Positive (Green)</label>
            </value>
            <value>
                <fullName>Neutral</fullName>
                <label>Neutral (Amber)</label>
            </value>
            <value>
                <fullName>Negative</fullName>
                <label>Negative (Red)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Review__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Initiative</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Business Reviews</relationshipLabel>
    <relationshipName>Business_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Review__c/fields/Review_Date__c.field-meta.xml
<CustomField>
    <fullName>Review_Date__c</fullName>
    <label>Review Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Conf_Category__c/Conf_Category__c.object-meta.xml
<CustomObject>
    <label>Configuration Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Sponsor__c.field-meta.xml
<CustomField>
    <fullName>Sponsor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sponsor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Strategic__c.field-meta.xml
<CustomField>
    <fullName>Strategic__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Strategic?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/acctRelatedObjects.cls
public with sharing class acctRelatedObjects {
   /* 
    Public Id accID;
    public Account acct{get;set;}
    public List<Program__c> programList{get;set;}
    public List<Business_Review__c> bussReviewList{get;set;}
    public String bussReviewListString{get;set;}
    public List<Account_Checklist__c> checkListList{get;set;}
    public String checkListListString{get;set;}
    public List<Account_Health_Metrics__c> healthList{get;set;}
    public String healthListString{get;set;}
    public List<String> healthLabel{get;set;}
    public List<Decimal> healthValue{get;set;}
    public String healthLabelString{get;set;}
    public String healthValueString{get;set;}
    public List<Account_Budget_Detail__c> budgetList{get;set;}
    public String budgetListString{get;set;}
    public List<Account_Expense_Detail__c> expenseList{get;set;}
    public String expenseListString{get;set;}
    public String trackerList{get;set;}
    public String testData{get;set;}
    public acctRelatedObjects(){
        accID=  ApexPages.currentPage().getParameters().get('id').escapeHtml4();
        programList = new List<Program__c>();
        bussReviewList = new List<Business_Review__c>();
        checkListList = new List<Account_Checklist__c>();
        try{
            acct = [Select Id,Name FROM Account WHERE Id=:accID WITH SECURITY_ENFORCED];
            programList =[Select Id,Name,Strategic__c,Sponsor__r.Name,Active__c,Account__c FROM Program__c WHERE Account__c = :accID WITH SECURITY_ENFORCED];
            bussReviewList =[Select Id,Name,Review_Date__c,Bussiness_Review_Assessment__c,Account__c FROM Business_Review__c WHERE Account__c = :accID WITH SECURITY_ENFORCED];
            bussReviewListString = JSON.serializePretty(bussReviewList);
            System.debug(bussReviewListString);
            checklistList =[Select Id,Name,Configuration_Category__r.Name FROM Account_Checklist__c where Id!='' WITH SECURITY_ENFORCED
        // WHERE Account__c = :accID
        ];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        checkListListString = JSON.serializePretty(checklistList);
        //List<Account_Health_Metrics__c> healthList = new List<Account_Health_Metrics__c>();
        List<Account_Health_Metrics__c> healthList;
        try{
           healthList = [Select Id,Name,Health_Score_Date__c,Average_Health_Score__c,Score_Month__c,Score_Year__c,Account__c FROM Account_Health_Metrics__c WHERE Account__c = :accID WITH SECURITY_ENFORCED ORDER BY Health_Score_Date__c];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        List<String> healthLabel = new List<String>();
        List<Decimal> healthValue = new List<Decimal>();
        for(Account_Health_Metrics__c h:healthList){
            if (h!=null){
            	if(h.Score_Month__c != null && h.Average_Health_Score__c != null){
            		system.debug('healthData   :    '+h.Score_Month__c + ' '+ h.Average_Health_Score__c); 
            		healthLabel.add(h.Score_Month__c+' '+h.Score_Year__c);
            		healthValue.add(h.Average_Health_Score__c);
            	}
			}
        }
        healthLabelString = JSON.serializePretty(healthLabel);
        healthValueString = JSON.serializePretty(healthValue);
        System.debug('healthLabel'+healthLabelString);
        System.debug('healthValue'+healthValueString);
        healthListString = JSON.serializePretty(healthList);
        
        budgetList = new List<Account_Budget_Detail__c>();
        try{
            budgetList =[Select Id,Name,Year__c,Budget_Allotted__c,Total_Expenses__c,Account__c FROM Account_Budget_Detail__c WHERE Account__c = :accID WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
          }
        budgetListString = JSON.serializePretty(budgetList);
        expenseList = new List<Account_Expense_Detail__c>();
        try{
            expenseList =[Select Id,Name,Account_Budget_Detail__r.Name,Budget_Category__r.Name,Expense_Amount__c,Expense_Date__c,Account__c FROM Account_Expense_Detail__c WHERE Account__c = :accID WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
          }
        expenseListString = JSON.serializePretty(expenseList);
        trackerList = JSON.serializePretty(trackProjectsHelper.getPrograms(accID));
        //system.debug('trackerList   :    '+trackerList); 
        List<String> testList = new List<String>();
        testList.add('Col1');testList.add('Col2');testList.add('Col3');
        testList.add('A');testList.add('B');testList.add('C');
        testData = JSON.serializePretty(testList);     
    }*/
}