force-app/main/default/objects/Account_Budget_Detail__c/Account_Budget_Detail__c.object-meta.xml
<CustomObject>
    <label>Account Budget Detail</label>
    <nameField>
        <label>Account Budget Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Budget Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Budget Details</relationshipLabel>
    <relationshipName>Account_Budget_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_10__c.field-meta.xml
<CustomField>
    <fullName>Column_10__c</fullName>
    <label>Column 10</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_11__c.field-meta.xml
<CustomField>
    <fullName>Column_11__c</fullName>
    <label>Column 11</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_12__c.field-meta.xml
<CustomField>
    <fullName>Column_12__c</fullName>
    <label>Column 12</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_13__c.field-meta.xml
<CustomField>
    <fullName>Column_13__c</fullName>
    <label>Column 13</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_14__c.field-meta.xml
<CustomField>
    <fullName>Column_14__c</fullName>
    <label>Column 14</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_15__c.field-meta.xml
<CustomField>
    <fullName>Column_15__c</fullName>
    <label>Column 15</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_16__c.field-meta.xml
<CustomField>
    <fullName>Column_16__c</fullName>
    <label>Column 16</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_17__c.field-meta.xml
<CustomField>
    <fullName>Column_17__c</fullName>
    <label>Column 17</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_18__c.field-meta.xml
<CustomField>
    <fullName>Column_18__c</fullName>
    <label>Column 18</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_19__c.field-meta.xml
<CustomField>
    <fullName>Column_19__c</fullName>
    <label>Column 19</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_1__c.field-meta.xml
<CustomField>
    <fullName>Column_1__c</fullName>
    <label>Column 1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_20__c.field-meta.xml
<CustomField>
    <fullName>Column_20__c</fullName>
    <label>Column 20</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_21__c.field-meta.xml
<CustomField>
    <fullName>Column_21__c</fullName>
    <label>Column 21</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_22__c.field-meta.xml
<CustomField>
    <fullName>Column_22__c</fullName>
    <label>Column 22</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_23__c.field-meta.xml
<CustomField>
    <fullName>Column_23__c</fullName>
    <label>Column 23</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_24__c.field-meta.xml
<CustomField>
    <fullName>Column_24__c</fullName>
    <label>Column 24</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_25__c.field-meta.xml
<CustomField>
    <fullName>Column_25__c</fullName>
    <label>Column 25</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_26__c.field-meta.xml
<CustomField>
    <fullName>Column_26__c</fullName>
    <label>Column 26</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_27__c.field-meta.xml
<CustomField>
    <fullName>Column_27__c</fullName>
    <label>Column 27</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_28__c.field-meta.xml
<CustomField>
    <fullName>Column_28__c</fullName>
    <label>Column 28</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_29__c.field-meta.xml
<CustomField>
    <fullName>Column_29__c</fullName>
    <label>Column 29</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_2__c.field-meta.xml
<CustomField>
    <fullName>Column_2__c</fullName>
    <label>Column 2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_30__c.field-meta.xml
<CustomField>
    <fullName>Column_30__c</fullName>
    <label>Column 30</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_31__c.field-meta.xml
<CustomField>
    <fullName>Column_31__c</fullName>
    <label>Column 31</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_32__c.field-meta.xml
<CustomField>
    <fullName>Column_32__c</fullName>
    <label>Column 32</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_33__c.field-meta.xml
<CustomField>
    <fullName>Column_33__c</fullName>
    <label>Column 33</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_34__c.field-meta.xml
<CustomField>
    <fullName>Column_34__c</fullName>
    <label>Column 34</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_35__c.field-meta.xml
<CustomField>
    <fullName>Column_35__c</fullName>
    <label>Column 35</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_36__c.field-meta.xml
<CustomField>
    <fullName>Column_36__c</fullName>
    <label>Column 36</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_37__c.field-meta.xml
<CustomField>
    <fullName>Column_37__c</fullName>
    <label>Column 37</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_38__c.field-meta.xml
<CustomField>
    <fullName>Column_38__c</fullName>
    <label>Column 38</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_39__c.field-meta.xml
<CustomField>
    <fullName>Column_39__c</fullName>
    <label>Column 39</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_3__c.field-meta.xml
<CustomField>
    <fullName>Column_3__c</fullName>
    <label>Column 3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_40__c.field-meta.xml
<CustomField>
    <fullName>Column_40__c</fullName>
    <label>Column 40</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_41__c.field-meta.xml
<CustomField>
    <fullName>Column_41__c</fullName>
    <label>Column 41</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_42__c.field-meta.xml
<CustomField>
    <fullName>Column_42__c</fullName>
    <label>Column 42</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_43__c.field-meta.xml
<CustomField>
    <fullName>Column_43__c</fullName>
    <label>Column 43</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_44__c.field-meta.xml
<CustomField>
    <fullName>Column_44__c</fullName>
    <label>Column 44</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_45__c.field-meta.xml
<CustomField>
    <fullName>Column_45__c</fullName>
    <label>Column 45</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_4__c.field-meta.xml
<CustomField>
    <fullName>Column_4__c</fullName>
    <label>Column 4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_5__c.field-meta.xml
<CustomField>
    <fullName>Column_5__c</fullName>
    <label>Column 5</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_6__c.field-meta.xml
<CustomField>
    <fullName>Column_6__c</fullName>
    <label>Column 6</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_7__c.field-meta.xml
<CustomField>
    <fullName>Column_7__c</fullName>
    <label>Column 7</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_8__c.field-meta.xml
<CustomField>
    <fullName>Column_8__c</fullName>
    <label>Column 8</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Budget_Detail__c/fields/Column_9__c.field-meta.xml
<CustomField>
    <fullName>Column_9__c</fullName>
    <label>Column 9</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Expense_Detail__c/Account_Expense_Detail__c.object-meta.xml
<CustomObject>
    <label>Account Expense Detail</label>
    <nameField>
        <label>Account Expense Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Expense Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Expense_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Expense Details</relationshipLabel>
    <relationshipName>Account_Expense_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Expense_Detail__c/fields/Account_Budget_Detail__c.field-meta.xml
<CustomField>
    <fullName>Account_Budget_Detail__c</fullName>
    <label>Account Budget</label>
    <referenceTo>Account_Budget_Detail__c</referenceTo>
    <relationshipLabel>Account Expense Details</relationshipLabel>
    <relationshipName>Account_Expense_Details</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Conf_Category__c/Conf_Category__c.object-meta.xml
<CustomObject>
    <label>Configuration Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conf_Category__c/fields/Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Category_Type__c</fullName>
    <label>Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/Configuration_Category_Detail__c.object-meta.xml
<CustomObject>
    <label>Configuration Category Detail</label>
    <nameField>
        <label>Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Category Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Configuration_Category__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Category__c</fullName>
    <label>Configuration Category</label>
    <referenceTo>Conf_Category__c</referenceTo>
    <relationshipName>Category_Configuration_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Category_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Health</fullName>
    </customValue>
    <customValue>
        <fullName>Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Company Division</fullName>
    </customValue>
    <customValue>
        <fullName>Relationship Type</fullName>
    </customValue>
    <customValue>
        <fullName>Program Milestone</fullName>
    </customValue>
    <customValue>
        <fullName>Stakeholder Personality</fullName>
    </customValue>
    <customValue>
        <fullName>Budget</fullName>
    </customValue>
    <customValue>
        <fullName>Soft Credit Role</fullName>
    </customValue>
    <customValue>
        <fullName>Target</fullName>
    </customValue>
    <customValue>
        <fullName>Company Offerings</fullName>
    </customValue>
    <customValue>
        <fullName>Credit</fullName>
    </customValue>
    <customValue>
        <fullName>Tab Visibility</fullName>
    </customValue>
    <customValue>
        <fullName>Account Insight</fullName>
    </customValue>
    <customValue>
        <fullName>Bbbb</fullName>
        <isActive>false</isActive>
        <label>Bbbb</label>
    </customValue>
    <customValue>
        <fullName>Aaaa</fullName>
        <isActive>false</isActive>
        <label>Aaaa</label>
    </customValue>
    <description>Category Type Picklist values for Conf_Category_Name Object.</description>
    <masterLabel>Category Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Account_Expense_Helper.cls
public with sharing class Account_Expense_Helper {
    @AuraEnabled(cacheable=true)
    public static List<Account_Budget_Detail__c> getBudgetRecords(String acctId){
        System.debug('acctId-->'+acctId);
        List<Account_Budget_Detail__c> budgetRecs;
        try{
            budgetRecs = [Select Id,Name,Account__c FROM Account_Budget_Detail__c WHERE Account__c=:acctId WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        System.debug('Expense budgetRecs-->'+budgetRecs.size());
        /*Map<String,String> mapData = new Map<String,String>();
        for(Account_Budget_Detail__c a : budgetRecs){
            mapData.put(a.Id,a.Name);
        }*/
        return budgetRecs;
    }

    @AuraEnabled(cacheable=true)
    public static List<Account_Budget_Detail__c> getBudgetRecords2(String expenseId){
        System.debug('expenseId-->'+expenseId);
        Account_Expense_Detail__c expense;
        try{
            expense = [SELECT Id,Account__c FROM Account_Expense_Detail__c WHERE Id=:expenseId WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        String acctId= expense.Account__c;
        System.debug('acctId-->'+acctId);
        List<Account_Budget_Detail__c> budgetRecs;
        try{
            budgetRecs = [Select Id,Name,Account__c FROM Account_Budget_Detail__c WHERE Account__c=:acctId WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        System.debug('Expense budgetRecs-->'+budgetRecs.size());
        /*Map<String,String> mapData = new Map<String,String>();
        for(Account_Budget_Detail__c a : budgetRecs){
            mapData.put(a.Id,a.Name);
        }*/
        return budgetRecs;
    }

    @AuraEnabled(cacheable=true)
    public static List<Conf_Category__c> getBudgetCategories(){
        List<Conf_Category__c> budgetRecsCats;
        try{
            budgetRecsCats = [Select Id,Name,Category_Type__c FROM Conf_Category__c WHERE Category_Type__c='Budget' WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        System.debug('Expense budgetRecsCats-->'+budgetRecsCats.size());
        return budgetRecsCats;
    }

    @AuraEnabled(cacheable=true)
    public static List<Configuration_Category_Detail__c> getBudgetSubCategories(String catName){
        List<Configuration_Category_Detail__c> budgetRecsCats;
        try{
            budgetRecsCats = [Select Id,Name,varasi_am__Configuration_Category__r.Id,varasi_am__Configuration_Category__r.varasi_am__Category_Type__c,varasi_am__Configuration_Category__r.Name FROM varasi_am__Configuration_Category_Detail__c where varasi_am__Configuration_Category__r.varasi_am__Category_Type__c='Budget' and varasi_am__Configuration_Category__r.Id=:catName WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        System.debug('Expense budgetRecsCats-->'+budgetRecsCats.size());
        return budgetRecsCats;
    }


    @AuraEnabled(cacheable=true)
    public static List<budgetWrapper> getExpenseRecs(String acctId){
        List<budgetWrapper> budgetRecords = new List<budgetWrapper>();
        List<varasi_am__Account_Budget_Detail__c> budgetRecs;
        List<Conf_Category__c> categsOld;
        List<Conf_Category__c> categories;
        try{
            budgetRecs=[  SELECT id,varasi_am__Account__c,name,varasi_am__Year__c,varasi_am__Budget_Allotted__c,varasi_am__Total_Expenses__c,Column_1__c,Column_2__c,Column_3__c,Column_4__c,Column_5__c,Column_6__c,Column_7__c,Column_8__c,Column_9__c,Column_10__c,
                                                                Column_11__c,Column_12__c,Column_13__c,Column_14__c,Column_15__c,Column_16__c,Column_17__c,Column_18__c,Column_19__c,
                                                                Column_20__c,Column_21__c,Column_22__c,Column_23__c,Column_24__c,Column_25__c,Column_26__c,Column_27__c,Column_28__c,Column_29__c,
                                                                Column_30__c,Column_31__c,Column_32__c,Column_33__c,Column_34__c,Column_35__c,Column_36__c,Column_37__c,Column_38__c,Column_39__c,
                                                                Column_40__c,Column_41__c,Column_42__c,Column_43__c,Column_44__c,Column_45__c,Column_46__c,Column_47__c,Column_48__c,Column_49__c,Column_50__c,
                                                                (Select id,name,Account__c,Account_Budget_Detail__c,Budget_Category__c,varasi_am__Budget_Category__r.Name,
                                                                Expense_Amount__c,Expense_Date__c
                                                                from Account_Expense_Details__r) 
                                                                FROM varasi_am__Account_Budget_Detail__c 
                                                                WHERE varasi_am__Account__c=:acctId WITH SECURITY_ENFORCED];
            categsOld = [Select Id,Name,Category_Type__c,(Select id,name,Column_Name__c from Category_Configuration_Details__r) FROM Conf_Category__c WHERE Category_Type__c='Budget' WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        
        Set<String> categSet1 = new Set<string>();
        for(Account_Budget_Detail__c budget:budgetRecs){
            for (Account_Expense_Detail__c e : budget.Account_Expense_Details__r) {
                categSet1.add(e.varasi_am__Budget_Category__r.Name);
            }
        }
        try{
        categories = [Select Id,Name,Category_Type__c,
                                                (Select id,name,Column_Name__c from Category_Configuration_Details__r) 
                                                FROM Conf_Category__c 
                                                WHERE Category_Type__c='Budget' AND Name IN :categSet1 WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        
        for(Account_Budget_Detail__c budget:budgetRecs){
            budgetWrapper b =new budgetWrapper();
            b.budgetName=budget.name;
            b.id='/'+budget.id;
            b.year = budget.varasi_am__Year__c;
            // b.budgetAlloted=budget.varasi_am__Budget_Allotted__c;
            b.budgetUsed=budget.varasi_am__Total_Expenses__c;
            //Double totalBudget=0;
            Set<String> categSet = new Set<string>();
            List<budgetCategWrapper> categList = new List<budgetCategWrapper>();
            for (Account_Expense_Detail__c e : budget.Account_Expense_Details__r) {
                categSet.add(e.varasi_am__Budget_Category__r.Name);
            }
            List<String> categs = new List<String>(categSet);
            for (String categ : categs) {
                budgetCategWrapper budgetCateg = new budgetCategWrapper();
                budgetCateg.id = '/'+budget.id;
                
                //totalBudget+=categTotal;
                Double expenseTotal=0;
                List<expenseWrapper> expWrapList = new List<expenseWrapper>();
                
                Double categTotal=0;
                    for(Conf_Category__c category:categories){
                        if(category.Name == categ){
                            for(Configuration_Category_Detail__c detail:category.Category_Configuration_Details__r){
                                categTotal+=budget.get(detail.Column_Name__c) == null ? 0 : Double.valueOf(budget.get(detail.Column_Name__c));
                            }                        
                        }
                    }

					budgetCateg.budgetAlloted=categTotal;
                
                for (Account_Expense_Detail__c exp : budget.Account_Expense_Details__r) {
                    if(exp.varasi_am__Budget_Category__r.Name == categ){
                        expenseWrapper expwrap = new expenseWrapper();
                        expwrap.id = '/'+exp.Id;
                        expwrap.name = exp.Name;
                        // expwrap.expenseDate = exp.Expense_Date__c;
                        expwrap.budgetUsed =exp.Expense_Amount__c;
                        expenseTotal+=exp.Expense_Amount__c==null?0:exp.Expense_Amount__c;
                        expWrapList.add(expwrap);
                    }                    
                    
                }
                budgetCateg.budgetUsed=expenseTotal;
                budgetCateg.items=expWrapList;
                budgetCateg.name = categ+ ' (' +expWrapList.size()+')';
                categList.add(budgetCateg);
            }
            Double catTotal=0.00;
            for(Conf_Category__c categ:categsOld){
                for(Configuration_Category_Detail__c detail: categ.Category_Configuration_Details__r){
                    catTotal+=budget.get(detail.Column_Name__c) == null ? 0 : Double.valueOf(budget.get(detail.Column_Name__c));
                }
            }
            b.budgetAlloted=catTotal;
            b.items=categList;
            b.name=budget.name+' ('+categList.size()+')';
            budgetRecords.add(b);
        }                                                                
        // List<Account_Expense_Detail__c> recs = [Select Id,Name,Account__c,Account_Budget_Detail__c,Budget_Category__c,varasi_am__Account_Budget_Detail__r.Name,varasi_am__Budget_Category__r.Name,
        // Expense_Amount__c,Expense_Date__c FROM Account_Expense_Detail__c WHERE Account__c=:acctId];
        // System.debug('Expense recs-->'+recs.size());
        return budgetRecords;
    }
    public class budgetWrapper{
        @AuraEnabled
        public string budgetName {get;set;}
        @AuraEnabled
        public string name {get;set;}
        @AuraEnabled
        public string id {get;set;}
        @AuraEnabled
        public double budgetUsed {get;set;}
        @AuraEnabled
        public double budgetAlloted {get;set;}
        @AuraEnabled
        public String year {get;set;}
        @AuraEnabled
        public List<budgetCategWrapper> items {get;set;}
    }
    public class budgetCategWrapper{
        @AuraEnabled
        public string id {get;set;}
        @AuraEnabled
        public string name {get;set;}
        @AuraEnabled
        public double budgetUsed {get;set;}
        @AuraEnabled
        public double budgetAlloted {get;set;}
        @AuraEnabled
        public List<expenseWrapper> items {get;set;}
    }
    public class expenseWrapper{
        @AuraEnabled
        public string id {get;set;}
        @AuraEnabled
        public string name {get;set;}
        @AuraEnabled
        public string budgetSubcateg {get;set;}
        @AuraEnabled
        public Decimal  budgetUsed{get;set;}
        @AuraEnabled
        public Date expenseDate {get;set;}
    }
    // @AuraEnabled(cacheable=true)
    // public static Account_Expense_Detail__c getExpenseRecord(String expenseId){
    //     List<Account_Expense_Detail__c> recs;
    //     try{
    //         recs = [Select Id,Name,Account__c,Account_Budget_Detail__c,Budget_Category__c,Account_Budget_Detail__r.Name,Budget_Category__r.Name,
    //         Expense_Amount__c,Expense_Date__c FROM Account_Expense_Detail__c WHERE Id=:expenseId WITH SECURITY_ENFORCED];
    //     }
    //     catch (System.QueryException exp) {
    //         AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
    //         throw e;
    //     }
    //     System.debug('Expense recs-->'+recs.size());
    //     return recs.get(0);
    // }
}