force-app/main/default/objects/Company_Offering__c/Company_Offering__c.object-meta.xml
<CustomObject>
    <label>Company Offering</label>
    <nameField>
        <displayFormat>CF-{000}</displayFormat>
        <label>Company_Offering Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Company Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Company_Offering__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Company_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Company_Offering__c/fields/Business_Owner__c.field-meta.xml
<CustomField>
    <fullName>Business_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Company Offerings</relationshipLabel>
    <relationshipName>Company_Offerings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company_Offering__c/fields/Configuration_Category_Detail__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Category_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration Category Detail</label>
    <referenceTo>Configuration_Category_Detail__c</referenceTo>
    <relationshipLabel>Company Offerings</relationshipLabel>
    <relationshipName>Company_Offerings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company_Offering__c/fields/Incumbent_or_Competitor__c.field-meta.xml
<CustomField>
    <fullName>Incumbent_or_Competitor__c</fullName>
    <label>Incumbent or Competitor</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Offering__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not a Fit</fullName>
            </value>
            <value>
                <fullName>Target</fullName>
            </value>
            <value>
                <fullName>Long Shot</fullName>
            </value>
            <value>
                <fullName>Improve Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company_Offering__c/fields/Tech_Owner__c.field-meta.xml
<CustomField>
    <fullName>Tech_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tech Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Company Offerings (Tech Owner)</relationshipLabel>
    <relationshipName>Company_Offerings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Conf_Category__c/Conf_Category__c.object-meta.xml
<CustomObject>
    <label>Configuration Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conf_Category__c/fields/Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Category_Type__c</fullName>
    <label>Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/Configuration_Category_Detail__c.object-meta.xml
<CustomObject>
    <label>Configuration Category Detail</label>
    <nameField>
        <label>Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Category Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Business_Owner__c.field-meta.xml
<CustomField>
    <fullName>Business_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Configuration Category Details</relationshipLabel>
    <relationshipName>Configuration_Category_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Configuration_Category__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Category__c</fullName>
    <label>Configuration Category</label>
    <referenceTo>Conf_Category__c</referenceTo>
    <relationshipName>Category_Configuration_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Incumbent_or_Competitor__c.field-meta.xml
<CustomField>
    <fullName>Incumbent_or_Competitor__c</fullName>
    <label>Incumbent or Competitor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Tech_Owner__c.field-meta.xml
<CustomField>
    <fullName>Tech_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tech Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Configuration Category Details (Tech Owner)</relationshipLabel>
    <relationshipName>Configuration_Category_Details1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Category_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Health</fullName>
    </customValue>
    <customValue>
        <fullName>Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Company Division</fullName>
    </customValue>
    <customValue>
        <fullName>Relationship Type</fullName>
    </customValue>
    <customValue>
        <fullName>Program Milestone</fullName>
    </customValue>
    <customValue>
        <fullName>Stakeholder Personality</fullName>
    </customValue>
    <customValue>
        <fullName>Budget</fullName>
    </customValue>
    <customValue>
        <fullName>Soft Credit Role</fullName>
    </customValue>
    <customValue>
        <fullName>Target</fullName>
    </customValue>
    <customValue>
        <fullName>Company Offerings</fullName>
    </customValue>
    <customValue>
        <fullName>Credit</fullName>
    </customValue>
    <customValue>
        <fullName>Tab Visibility</fullName>
    </customValue>
    <customValue>
        <fullName>Account Insight</fullName>
    </customValue>
    <customValue>
        <fullName>Bbbb</fullName>
        <isActive>false</isActive>
        <label>Bbbb</label>
    </customValue>
    <customValue>
        <fullName>Aaaa</fullName>
        <isActive>false</isActive>
        <label>Aaaa</label>
    </customValue>
    <description>Category Type Picklist values for Conf_Category_Name Object.</description>
    <masterLabel>Category Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Whitespace_Analysis_Helper_Test.cls
@isTest
public class Whitespace_Analysis_Helper_Test {
  	 @testSetup static void DataSet(){
        Contact c = new Contact(LastName='Internal Contact');
        insert c;
        Conf_Category__c config = new Conf_Category__c(Name='Account Onboarding',Category_Type__c='Company Offerings');
        insert config;
        Conf_Category__c config1 = new Conf_Category__c(Name='Analytics',Category_Type__c='Company Offerings');
        insert config1;
		Account a = new Account(Name='Test 1');
        insert a;
		Company_Offering__c comp_offering= new Company_Offering__c(varasi_am__Account__c=a.id);
        insert comp_offering;
        Configuration_Category_Detail__c configDetail = new Configuration_Category_Detail__c(Name='Marketing Plan',Configuration_Category__c=config.Id,Business_Owner__c=c.Id,Tech_Owner__c=c.Id); 
        insert configDetail;
        Configuration_Category_Detail__c configDetail1 = new Configuration_Category_Detail__c(Name='ETL Jobs',Configuration_Category__c=config1.Id,Business_Owner__c=c.Id,Tech_Owner__c=c.Id); 
        insert configDetail1;
        Profile p2 = [SELECT Id FROM Profile WHERE Name='Solution Manager']; 
  		User u2 = new User(Alias = 'solUser', Email='testsoltionManUser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='SolManager', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p2.Id, 
        TimeZoneSidKey='America/Los_Angeles', UserName='testuserVarasi@testorg.com');
        insert u2;
     }
    @IsTest
    static void updateOfferingstest(){
        Account a =[Select id,name from Account where name='Test 1'];
        Whitespace_Analysis_Helper.updateOfferings(a.Id);
        List<Company_Offering__c> offerings = [SELECT Id from Company_Offering__c WHERE Account__c=: a.id];
        List<Whitespace_Analysis_Helper.offer> o = Whitespace_Analysis_Helper.getOfferingsData(a.id);
        Integer s = offerings.size();
        system.assertEquals(o.size(), s);
    }
     @IsTest
    static void getOfferingsDataTest(){
        Account a =[Select id,name from Account where name='Test 1'];
        List<Company_Offering__c> offerings = [SELECT Id,Name,Account__c,Business_Owner__c,Business_Owner__r.Name,Tech_Owner__r.Name,
                            Configuration_Category_Detail__c,Configuration_Category_Detail__r.Name,
                            Configuration_Category_Detail__r.Configuration_Category__r.Name,
                            Incumbent_or_Competitor__c,Status__c,Tech_Owner__c 
                        FROM Company_Offering__c 
                        WHERE Account__c=: a.id];
        List<Whitespace_Analysis_Helper.offer> o = Whitespace_Analysis_Helper.getOfferingsData(a.id);
        Integer s = offerings.size();
        system.assertEquals(o.size(), s);
        
    }
    /*static testmethod void getOfferingTest(){
        List<Whitespace_Analysis_Helper.offer> offers = Whitespace_Analysis_Helper.getOfferings();
        System.assert(offers.size()>0);
    }
    
    static testmethod void getOfferingExceptionTest(){
        User solManUser = [SELECT id FROM User WHERE Email='testsoltionManUser@testorg.com'];
		System.runAs(solManUser) 
        {
            Test.startTest();
			try{
				List<Whitespace_Analysis_Helper.offer> offers = Whitespace_Analysis_Helper.getOfferings();
			}
			catch(Exception e){
				System.assertEquals(true,e.getMessage().contains('Error')||e.getMessage().contains('exception'));  
			}
			Test.stopTest();
        }
    }*/
}