force-app/main/default/objects/Company_Offering__c/Company_Offering__c.object-meta.xml
<CustomObject>
    <label>Company Offering</label>
    <nameField>
        <displayFormat>CF-{000}</displayFormat>
        <label>Company_Offering Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Company Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Company_Offering__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Company_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Company_Offering__c/fields/Configuration_Category_Detail__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Category_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration Category Detail</label>
    <referenceTo>Configuration_Category_Detail__c</referenceTo>
    <relationshipLabel>Company Offerings</relationshipLabel>
    <relationshipName>Company_Offerings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Conf_Category__c/Conf_Category__c.object-meta.xml
<CustomObject>
    <label>Configuration Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conf_Category__c/fields/Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Category_Type__c</fullName>
    <label>Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Conf_Category__c/fields/Column_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Name__c</fullName>
    <label>Column Name</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/Configuration_Category_Detail__c.object-meta.xml
<CustomObject>
    <label>Configuration Category Detail</label>
    <nameField>
        <label>Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Category Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Column_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Name__c</fullName>
    <label>Column Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Configuration_Category__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Category__c</fullName>
    <label>Configuration Category</label>
    <referenceTo>Conf_Category__c</referenceTo>
    <relationshipName>Category_Configuration_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Category_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Health</fullName>
    </customValue>
    <customValue>
        <fullName>Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Company Division</fullName>
    </customValue>
    <customValue>
        <fullName>Relationship Type</fullName>
    </customValue>
    <customValue>
        <fullName>Program Milestone</fullName>
    </customValue>
    <customValue>
        <fullName>Stakeholder Personality</fullName>
    </customValue>
    <customValue>
        <fullName>Budget</fullName>
    </customValue>
    <customValue>
        <fullName>Soft Credit Role</fullName>
    </customValue>
    <customValue>
        <fullName>Target</fullName>
    </customValue>
    <customValue>
        <fullName>Company Offerings</fullName>
    </customValue>
    <customValue>
        <fullName>Credit</fullName>
    </customValue>
    <customValue>
        <fullName>Tab Visibility</fullName>
    </customValue>
    <customValue>
        <fullName>Account Insight</fullName>
    </customValue>
    <customValue>
        <fullName>Bbbb</fullName>
        <isActive>false</isActive>
        <label>Bbbb</label>
    </customValue>
    <customValue>
        <fullName>Aaaa</fullName>
        <isActive>false</isActive>
        <label>Aaaa</label>
    </customValue>
    <description>Category Type Picklist values for Conf_Category_Name Object.</description>
    <masterLabel>Category Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Company_Offering_Helper.cls
public with sharing class Company_Offering_Helper {
    @AuraEnabled(cacheable=true)
    public static List<Company_Offering__c> getCompOfferings(String acctId){
        List<Company_Offering__c> offerings;
        try{
            offerings=[Select Id,Name,Account__c from Company_Offering__c where Account__c=:acctId WITH SECURITY_ENFORCED LIMIT 1];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        // if(offerings.size()==0){
        //     Company_Offering__c cOff = new Company_Offering__c(Account__c=acctId);
        //     insert cOff;
        //     offerings.add(cOff);
        // }
        return offerings;
    }
    //Old method not in Use Recheck and Delete
    @AuraEnabled(cacheable=true)
    public static Map<String,String> oldgetConfigData(){
        List<Conf_Category__c> conf;
        try{
            conf = [Select Id,Name,Category_Type__c,Column_Name__c FROM Conf_Category__c WHERE Category_Type__c='Company Offerings' WITH SECURITY_ENFORCED];
        } 
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        Map<String,String> configMap = new Map<String,String>();
        for(Conf_Category__c c:conf){
            configMap.put(c.Column_Name__c,c.Name);
        }
        return configMap;
    }
    //Bring data from conf categ and subcateg. record data handeled in edit form by passing record Id.
    @AuraEnabled(cacheable=true)
    public static List<categWrapper> getConfigData(String recordId){
        List<Conf_Category__c> categs;
        try{
            categs = [Select Id,Name,Category_Type__c,(Select id,name,Column_Name__c from Category_Configuration_Details__r) FROM Conf_Category__c WHERE Category_Type__c='Company Offerings' WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        List<categWrapper> categList= new List<categWrapper>();
        for(Conf_Category__c categ:categs){
            categWrapper c =new categWrapper();
            c.Id=categ.Id;
            c.name=categ.name;
            List<subCategWrapper> subCategList= new List<subCategWrapper>();
            Double categTotal=0.00;
            for(Configuration_Category_Detail__c detail: categ.Category_Configuration_Details__r){
                subCategWrapper s=new subCategWrapper();
                s.Id=detail.id;
                s.name=detail.name;
                s.colName=detail.Column_Name__c;
                subCategList.add(s);
            }
            c.subCategs=subCategList;
            categList.add(c);
        }
        return categList;
    }

    public class categWrapper{
        @AuraEnabled
        public  string Id {get;set;}
        @AuraEnabled
        public  string name {get;set;}
        @AuraEnabled
        public  List<subCategWrapper> subCategs {get;set;}
    }
    public class subCategWrapper{
        @AuraEnabled
        public string Id {get;set;}
        @AuraEnabled
        public string colName {get;set;}
        @AuraEnabled
        public string name {get;set;}
    }
}