force-app/main/default/objects/Company_Offering__c/Company_Offering__c.object-meta.xml
<CustomObject>
    <label>Company Offering</label>
    <nameField>
        <displayFormat>CF-{000}</displayFormat>
        <label>Company_Offering Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Company Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Company_Offering__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Company_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Company_Offering__c/fields/Business_Owner__c.field-meta.xml
<CustomField>
    <fullName>Business_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Company Offerings</relationshipLabel>
    <relationshipName>Company_Offerings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company_Offering__c/fields/Configuration_Category_Detail__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Category_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration Category Detail</label>
    <referenceTo>Configuration_Category_Detail__c</referenceTo>
    <relationshipLabel>Company Offerings</relationshipLabel>
    <relationshipName>Company_Offerings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company_Offering__c/fields/Incumbent_or_Competitor__c.field-meta.xml
<CustomField>
    <fullName>Incumbent_or_Competitor__c</fullName>
    <label>Incumbent or Competitor</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Offering__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not a Fit</fullName>
            </value>
            <value>
                <fullName>Target</fullName>
            </value>
            <value>
                <fullName>Long Shot</fullName>
            </value>
            <value>
                <fullName>Improve Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company_Offering__c/fields/Tech_Owner__c.field-meta.xml
<CustomField>
    <fullName>Tech_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tech Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Company Offerings (Tech Owner)</relationshipLabel>
    <relationshipName>Company_Offerings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Conf_Category__c/Conf_Category__c.object-meta.xml
<CustomObject>
    <label>Configuration Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conf_Category__c/fields/Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Category_Type__c</fullName>
    <label>Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Conf_Category__c/fields/Column_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Name__c</fullName>
    <label>Column Name</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/Configuration_Category_Detail__c.object-meta.xml
<CustomObject>
    <label>Configuration Category Detail</label>
    <nameField>
        <label>Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Category Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Business_Owner__c.field-meta.xml
<CustomField>
    <fullName>Business_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Configuration Category Details</relationshipLabel>
    <relationshipName>Configuration_Category_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Column_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Name__c</fullName>
    <label>Column Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Configuration_Category__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Category__c</fullName>
    <label>Configuration Category</label>
    <referenceTo>Conf_Category__c</referenceTo>
    <relationshipName>Category_Configuration_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Incumbent_or_Competitor__c.field-meta.xml
<CustomField>
    <fullName>Incumbent_or_Competitor__c</fullName>
    <label>Incumbent or Competitor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Opportunities__c.field-meta.xml
<CustomField>
    <fullName>Opportunities__c</fullName>
    <label>Opportunities</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Tech_Owner__c.field-meta.xml
<CustomField>
    <fullName>Tech_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tech Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Configuration Category Details (Tech Owner)</relationshipLabel>
    <relationshipName>Configuration_Category_Details1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Category_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Health</fullName>
    </customValue>
    <customValue>
        <fullName>Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Company Division</fullName>
    </customValue>
    <customValue>
        <fullName>Relationship Type</fullName>
    </customValue>
    <customValue>
        <fullName>Program Milestone</fullName>
    </customValue>
    <customValue>
        <fullName>Stakeholder Personality</fullName>
    </customValue>
    <customValue>
        <fullName>Budget</fullName>
    </customValue>
    <customValue>
        <fullName>Soft Credit Role</fullName>
    </customValue>
    <customValue>
        <fullName>Target</fullName>
    </customValue>
    <customValue>
        <fullName>Company Offerings</fullName>
    </customValue>
    <customValue>
        <fullName>Credit</fullName>
    </customValue>
    <customValue>
        <fullName>Tab Visibility</fullName>
    </customValue>
    <customValue>
        <fullName>Account Insight</fullName>
    </customValue>
    <customValue>
        <fullName>Bbbb</fullName>
        <isActive>false</isActive>
        <label>Bbbb</label>
    </customValue>
    <customValue>
        <fullName>Aaaa</fullName>
        <isActive>false</isActive>
        <label>Aaaa</label>
    </customValue>
    <description>Category Type Picklist values for Conf_Category_Name Object.</description>
    <masterLabel>Category Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Whitespace_Analysis_Helper.cls
public with sharing class Whitespace_Analysis_Helper {
    public static List<String> checkNewOffering(String acctId){
        List<Company_Offering__c> offerings;
        try{
        	offerings = [SELECT varasi_am__Is_Offered__c,Id,Name,Account__c,Business_Owner__c,Business_Owner__r.Name,Tech_Owner__r.Name,Configuration_Category_Detail__c,Configuration_Category_Detail__r.Name,Configuration_Category_Detail__r.Configuration_Category__r.Name,Incumbent_or_Competitor__c,Status__c,Tech_Owner__c FROM Company_Offering__c WHERE Account__c=:acctId WITH SECURITY_ENFORCED];
        }catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        
        List<varasi_am__Configuration_Category_Detail__c> setupOfferings;
        try{
            setupOfferings = [select id from varasi_am__Configuration_Category_Detail__c where varasi_am__Configuration_Category__r.varasi_am__Category_Type__c='Company Offerings' WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        List<String> setOfferingIds = new List<String>();
        for(Company_Offering__c c:offerings){
            setOfferingIds.add(c.Id);
        }
        Integer offeringSize = offerings.size();
        Integer setUPOfferingSize = setupOfferings.size();
        List<String> newOfferings =  new List<String>();
        if(offeringSize == setUPOfferingSize){
            System.debug(newOfferings);
        }
        else{
            for(varasi_am__Configuration_Category_Detail__c offering : setupOfferings){
                if(setOfferingIds.size()==0){
                    newOfferings.add(offering.Id);
                }
                else{
                    if(!setOfferingIds.contains(offering.Id)){
                        newOfferings.add(offering.Id);
                    }
                }
            }
        }
        return newOfferings;
    }
    @AuraEnabled
    public static void updateOfferings(String acctId){
        List<String> newOfferings = checkNewOffering(acctId);
        system.debug('newOfferings:  '+newOfferings);
        LIst<Company_Offering__c> newOfferingsList = new List<Company_Offering__c>();
        if(newOfferings.size()>0){
            for(String newOffering:newOfferings){
                Company_Offering__c newCompOffering = new Company_Offering__c();
                newCompOffering.Configuration_Category_Detail__c=newOffering;
                newCompOffering.Account__c=acctId;
                newOfferingsList.add(newCompOffering);
            }
            system.debug(newOfferingsList);
            // updateOfferings(newOfferingsList);
            // offerings.addAll(newOfferingsList);
            acct_Mgmt_Controller.objectCreatableNew(newOfferingsList);
        }
    }
    @AuraEnabled(cacheable=true)
    public static List<offer> getOfferingsData(Id acctId){
        System.debug('acctId'+acctId);
        	List<Company_Offering__c> offerings;
        	List<offer> offerList = new List<offer>();
        try{
        	offerings = [SELECT varasi_am__Is_Offered__c,Id,Name,Account__c,Business_Owner__c,Business_Owner__r.Name,Tech_Owner__r.Name,Configuration_Category_Detail__c,Configuration_Category_Detail__r.Name,Configuration_Category_Detail__r.Configuration_Category__r.Name,Incumbent_or_Competitor__c,Status__c,Tech_Owner__c FROM Company_Offering__c WHERE Account__c=:acctId WITH SECURITY_ENFORCED];
        }catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        Map<String,List<Company_Offering__c>> offeringMap = new Map<String,List<Company_Offering__c>>();
        for(Company_Offering__c o : offerings){
            if(offeringMap.containsKey(o.Configuration_Category_Detail__r.Configuration_Category__r.Name)){
                List<Company_Offering__c> offList = offeringMap.get(o.Configuration_Category_Detail__r.Configuration_Category__r.Name);
                offList.add(o);
                offeringMap.put(o.Configuration_Category_Detail__r.Configuration_Category__r.Name,offList);
            }else{
           		List<Company_Offering__c> offList = new List<Company_Offering__c>();
                offList.add(o);
                offeringMap.put(o.Configuration_Category_Detail__r.Configuration_Category__r.Name,offList);
            }
        }
        for (String key : offeringMap.keySet()){
            offer mainOffer = new offer();
            mainOffer.name = key;
            mainOffer.viewButton = true;
            List<Company_Offering__c> offeringsList = offeringMap.get(key);
            List<offerWrapper> offerWrapList = new List<offerWrapper>();
            for(Company_Offering__c detail : offeringsList){
                offerWrapper offer=new offerWrapper();
                offer.Id=detail.Id;
                offer.name=detail.Configuration_Category_Detail__r.Name;
                offer.status=detail.Status__c;
                if(detail.Tech_Owner__c != null){
                	offer.tOwner='/'+detail.Tech_Owner__c;    
                }
                offer.tOwnerName=detail.Tech_Owner__r.Name;
                if(detail.Business_Owner__c != null){
                	offer.bOwner='/'+detail.Business_Owner__c;    
                }
                offer.isOffered=detail.varasi_am__Is_Offered__c;
                offer.bOwnerName=detail.Business_Owner__r.Name;
                offer.ioc=detail.Incumbent_or_Competitor__c;
                offer.viewButton=false;
                offerWrapList.add(offer);
            }
            mainOffer.items= offerWrapList;
            offerList.add(mainOffer);
        }
        System.debug('offerList'+offerList);
        return offerList;
    }
    
    /*@AuraEnabled(cacheable=true)
    public static List<offer> getOfferings(){
        List<Conf_Category__c> categs;
        try{
            categs = [Select Id,Name,Category_Type__c,(Select id,name,Column_Name__c,Status__c,Tech_Owner__c,Tech_Owner__r.Name,Opportunities__c,Incumbent_or_Competitor__c,Business_Owner__c,Business_Owner__r.Name from Category_Configuration_Details__r) FROM Conf_Category__c WHERE Category_Type__c='Company Offerings' WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
          }
        List<offer> mainOffers = new List<offer>();
        for(Conf_Category__c categ:categs){
            offer mainOffer=new offer();
            mainOffer.name=categ.name;
            mainOffer.viewButton=true;
            List<offerWrapper> offers = new List<offerWrapper>();
            for(Configuration_Category_Detail__c detail: categ.Category_Configuration_Details__r){
                offerWrapper offer=new offerWrapper();
                offer.Id=detail.Id;
                offer.name=detail.name;
                offer.status=detail.Status__c;
                offer.tOwner='/'+detail.Tech_Owner__c;
                //List<Contact> cont1;
               /* Contact cont1;
                try{
                    cont1=[Select id,Name from Contact where id=:detail.Tech_Owner__c WITH SECURITY_ENFORCED Limit 1];
                }
                catch (System.QueryException exp) {
                    AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
                    throw e;
                  }
                //if(cont1.size()>0){
                if(cont1 != null){
                    offer.tOwnerName=cont1.Name;
                } 
                 offer.tOwnerName=detail.Tech_Owner__r.Name;
                offer.bOwner='/'+detail.Business_Owner__c;
                /*List<Contact> cont2;
                try{
                    cont2=[Select id,Name from Contact where id=:detail.Business_Owner__c WITH SECURITY_ENFORCED Limit 1];
                }
                catch (System.QueryException exp) {
                    AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
                    throw e;
                  }
                if(cont2.size()>0){
                    offer.bOwnerName=cont2.get(0).Name;
                }
                offer.bOwnerName=detail.Business_Owner__r.Name;
                offer.ioc=detail.Incumbent_or_Competitor__c;
                offer.opportunities=detail.Opportunities__c;
                offer.viewButton=false;
                offers.add(offer);
            }
            mainOffer.items=offers;
            mainOffers.add(mainOffer);
        }
        return mainOffers;
    }*/

    public class offer{
        @AuraEnabled
        public String name{get;set;}
        @AuraEnabled
        public List<offerWrapper> items{get;set;}
        @AuraEnabled
        public Boolean viewButton{get;set;}
    }

    public class offerWrapper{
        @AuraEnabled
        public Id Id{get;set;}
        @AuraEnabled
        public String name{get;set;}
        @AuraEnabled
        public String status{get;set;}
        @AuraEnabled
        public String tOwner{get;set;}
        @AuraEnabled
        public String tOwnerName{get;set;}
        @AuraEnabled
        public String bOwner{get;set;}
        @AuraEnabled
        public String bOwnerName{get;set;}
        @AuraEnabled
        public String ioc{get;set;}
        @AuraEnabled
        public String opportunities{get;set;}
        @AuraEnabled
        public Boolean viewButton{get;set;}
        @AuraEnabled
        public Boolean isOffered{get;set;}
        
    }
}