force-app/main/default/objects/Account_Checklist__c/Account_Checklist__c.object-meta.xml
<CustomObject>
    <label>Account Checklist</label>
    <nameField>
        <label>Account Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Checklist__c/fields/Column_10__c.field-meta.xml
<CustomField>
    <fullName>Column_10__c</fullName>
    <label>Column 10</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_11__c.field-meta.xml
<CustomField>
    <fullName>Column_11__c</fullName>
    <label>Column 11</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_12__c.field-meta.xml
<CustomField>
    <fullName>Column_12__c</fullName>
    <label>Column 12</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_13__c.field-meta.xml
<CustomField>
    <fullName>Column_13__c</fullName>
    <label>Column 13</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_14__c.field-meta.xml
<CustomField>
    <fullName>Column_14__c</fullName>
    <label>Column 14</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_15__c.field-meta.xml
<CustomField>
    <fullName>Column_15__c</fullName>
    <label>Column 15</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_16__c.field-meta.xml
<CustomField>
    <fullName>Column_16__c</fullName>
    <label>Column 16</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_17__c.field-meta.xml
<CustomField>
    <fullName>Column_17__c</fullName>
    <label>Column 17</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_18__c.field-meta.xml
<CustomField>
    <fullName>Column_18__c</fullName>
    <label>Column 18</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_19__c.field-meta.xml
<CustomField>
    <fullName>Column_19__c</fullName>
    <label>Column 19</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_1__c.field-meta.xml
<CustomField>
    <fullName>Column_1__c</fullName>
    <label>Column 1</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_20__c.field-meta.xml
<CustomField>
    <fullName>Column_20__c</fullName>
    <label>Column 20</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_21__c.field-meta.xml
<CustomField>
    <fullName>Column_21__c</fullName>
    <label>Column 21</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_22__c.field-meta.xml
<CustomField>
    <fullName>Column_22__c</fullName>
    <label>Column 22</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_23__c.field-meta.xml
<CustomField>
    <fullName>Column_23__c</fullName>
    <label>Column 23</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_24__c.field-meta.xml
<CustomField>
    <fullName>Column_24__c</fullName>
    <label>Column 24</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_25__c.field-meta.xml
<CustomField>
    <fullName>Column_25__c</fullName>
    <label>Column 25</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_26__c.field-meta.xml
<CustomField>
    <fullName>Column_26__c</fullName>
    <label>Column 26</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_27__c.field-meta.xml
<CustomField>
    <fullName>Column_27__c</fullName>
    <label>Column 27</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_28__c.field-meta.xml
<CustomField>
    <fullName>Column_28__c</fullName>
    <label>Column 28</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_29__c.field-meta.xml
<CustomField>
    <fullName>Column_29__c</fullName>
    <label>Column 29</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_2__c.field-meta.xml
<CustomField>
    <fullName>Column_2__c</fullName>
    <label>Column 2</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_30__c.field-meta.xml
<CustomField>
    <fullName>Column_30__c</fullName>
    <label>Column 30</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_31__c.field-meta.xml
<CustomField>
    <fullName>Column_31__c</fullName>
    <label>Column 31</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_32__c.field-meta.xml
<CustomField>
    <fullName>Column_32__c</fullName>
    <label>Column 32</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_33__c.field-meta.xml
<CustomField>
    <fullName>Column_33__c</fullName>
    <label>Column 33</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_34__c.field-meta.xml
<CustomField>
    <fullName>Column_34__c</fullName>
    <label>Column 34</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_35__c.field-meta.xml
<CustomField>
    <fullName>Column_35__c</fullName>
    <label>Column 35</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_36__c.field-meta.xml
<CustomField>
    <fullName>Column_36__c</fullName>
    <label>Column 36</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_37__c.field-meta.xml
<CustomField>
    <fullName>Column_37__c</fullName>
    <label>Column 37</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_38__c.field-meta.xml
<CustomField>
    <fullName>Column_38__c</fullName>
    <label>Column 38</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_39__c.field-meta.xml
<CustomField>
    <fullName>Column_39__c</fullName>
    <label>Column 39</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_3__c.field-meta.xml
<CustomField>
    <fullName>Column_3__c</fullName>
    <label>Column 3</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_40__c.field-meta.xml
<CustomField>
    <fullName>Column_40__c</fullName>
    <label>Column 40</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_41__c.field-meta.xml
<CustomField>
    <fullName>Column_41__c</fullName>
    <label>Column 41</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_42__c.field-meta.xml
<CustomField>
    <fullName>Column_42__c</fullName>
    <label>Column 42</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_43__c.field-meta.xml
<CustomField>
    <fullName>Column_43__c</fullName>
    <label>Column 43</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_44__c.field-meta.xml
<CustomField>
    <fullName>Column_44__c</fullName>
    <label>Column 44</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_45__c.field-meta.xml
<CustomField>
    <fullName>Column_45__c</fullName>
    <label>Column 45</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_46__c.field-meta.xml
<CustomField>
    <fullName>Column_46__c</fullName>
    <label>Column 46</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_47__c.field-meta.xml
<CustomField>
    <fullName>Column_47__c</fullName>
    <label>Column 47</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_48__c.field-meta.xml
<CustomField>
    <fullName>Column_48__c</fullName>
    <label>Column 48</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_49__c.field-meta.xml
<CustomField>
    <fullName>Column_49__c</fullName>
    <label>Column 49</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_4__c.field-meta.xml
<CustomField>
    <fullName>Column_4__c</fullName>
    <label>Column 4</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_50__c.field-meta.xml
<CustomField>
    <fullName>Column_50__c</fullName>
    <label>Column 50</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_5__c.field-meta.xml
<CustomField>
    <fullName>Column_5__c</fullName>
    <label>Column 5</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_6__c.field-meta.xml
<CustomField>
    <fullName>Column_6__c</fullName>
    <label>Column 6</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_7__c.field-meta.xml
<CustomField>
    <fullName>Column_7__c</fullName>
    <label>Column 7</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_8__c.field-meta.xml
<CustomField>
    <fullName>Column_8__c</fullName>
    <label>Column 8</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_9__c.field-meta.xml
<CustomField>
    <fullName>Column_9__c</fullName>
    <label>Column 9</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Configuration_Category__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Checklist Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Conf_Category__c.Category_Type__c</field>
            <operation>equals</operation>
            <value>Checklist</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Conf_Category__c</referenceTo>
    <relationshipLabel>Account Checklists</relationshipLabel>
    <relationshipName>Account_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/varasiFileUploaderHelper.cls
public with sharing class varasiFileUploaderHelper {
    @AuraEnabled
    public static String uploadFile(String base64, String filename, String recordId,string columnName) {
        ContentVersion cv = createContentVersion(base64, filename);
        ContentDocumentLink cdl = createContentLink(cv.Id, recordId);
        if (cv == null || cdl == null) { return null; }
        Account_Checklist__c chkLIstData;
        try{chkLIstData = [select Id,Name,Configuration_Category__c,varasi_am__relatedObjectId__c,
        Column_1__c,Column_2__c,Column_3__c,Column_4__c,Column_5__c,Column_6__c,Column_7__c,Column_8__c,Column_9__c,Column_10__c,
        Column_11__c,Column_12__c,Column_13__c,Column_14__c,Column_15__c,Column_16__c,Column_17__c,Column_18__c,Column_19__c,
        Column_20__c,Column_21__c,Column_22__c,Column_23__c,Column_24__c,Column_25__c,Column_26__c,Column_27__c,Column_28__c,Column_29__c,
        Column_30__c,Column_31__c,Column_32__c,Column_33__c,Column_34__c,Column_35__c,Column_36__c,Column_37__c,Column_38__c,Column_39__c,
        Column_40__c,Column_41__c,Column_42__c,Column_43__c,Column_44__c,Column_45__c,Column_46__c,Column_47__c,Column_48__c,Column_49__c,Column_50__c 
        from  Account_Checklist__c where Id =: recordId WITH SECURITY_ENFORCED ];}
        catch (System.QueryException exp) {
          AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
          throw e;
      }
        List<String> columnValues=chkLIstData.get(columnName) == null ? null : string.valueOf(chkLIstData.get(columnName)).split('~');
        System.debug('columnValues '+columnValues);
        if(columnValues==null){
        	chkLIstData.put(columnName,'null~null~'+cdl.Id+'~null');
            List<Account_Checklist__c> allChecklistData = new List<Account_Checklist__c>();
            allChecklistData.add(chkLIstData);
            //acct_Mgmt_Controller.objectUpsertableNew(allChecklistData);
            List<Account_Checklist__c> updateList = new List<Account_Checklist__c>();
            List<Account_Checklist__c> createList = new List<Account_Checklist__c>();
            for(Account_Checklist__c n : allChecklistData){
                if(n.Id != null){
                    updateList.add(n);
                }else{
                    createList.add(n);
                }
            }
            if(createList.size()>0){
                acct_Mgmt_Controller.objectCreatableNew(createList);
            }
            if(updateList.size()>0){
                acct_Mgmt_Controller.objectUpdatableNew(updateList);   
            }
        	/*if(acct_Mgmt_Controller.objectUpdateable('Account_Checklist__c',fieldList1) && acct_Mgmt_Controller.objectCreatable('Account_Checklist__c',fieldList1)){
          		upsert chkLIstData;
            }*/
        }
        else{
          if(columnValues.size()>2){
            string colVal=columnValues[2]=='null'?String.valueOf(cdl.Id):String.valueOf(columnValues[2])+','+String.valueOf(cdl.Id);
            string colValFull=columnValues[0]+'~'+columnValues[1]+'~'+colVal+'~'+columnValues[3];
            chkLIstData.put(columnName,colValFull);
            //List<String> fieldList1 = new List<String>();
            List<Account_Checklist__c> allChecklistData = new List<Account_Checklist__c>();
            allChecklistData.add(chkLIstData);
            System.debug('colVal in else ' +colVal);
              System.debug('colValFull in else ' +colValFull);
              System.debug('allChecklistData in else ' +allChecklistData);
            //acct_Mgmt_Controller.objectUpsertableNew(allChecklistData);
            List<Account_Checklist__c> updateList = new List<Account_Checklist__c>();
            List<Account_Checklist__c> createList = new List<Account_Checklist__c>();
            for(Account_Checklist__c n : allChecklistData){
                if(n.Id != null){
                    updateList.add(n);
                }else{
                    createList.add(n);
                }
            }
            if(createList.size()>0){
                System.debug('createList in else ' +createList);
                acct_Mgmt_Controller.objectCreatableNew(createList);
            }
            if(updateList.size()>0){
                System.debug('updateList in else ' +updateList);
                acct_Mgmt_Controller.objectUpdatableNew(updateList);   
            }
        	/*if(acct_Mgmt_Controller.objectUpdateable('Account_Checklist__c',fieldList1) && acct_Mgmt_Controller.objectCreatable('Account_Checklist__c',fieldList1)){
            	upsert chkLIstData;
            }*/
          }
        }
        return cdl.Id;
    }
    private static ContentVersion createContentVersion(String base64, String filename) {
        ContentVersion cv = new ContentVersion();
        List<ContentVersion> cvs = new List<ContentVersion>();
        cv.VersionData = EncodingUtil.base64Decode(base64);
        cv.Title = filename;
        cv.PathOnClient = filename;
        cvs.add(cv);
        try {
            //List<String> fieldList1 = new List<String>{'VersionData','Title','PathOnClient'};
            List<ContentVersion> cvsListNew = acct_Mgmt_Controller.objectCreatableNew(cvs);
        	/*if(acct_Mgmt_Controller.objectCreatable('ContentVersion',fieldList1)){
          		insert cv;
          }*/
          return cvsListNew[0];
        } catch(DMLException e) {
          System.debug(e);
          return null;
        }
    }
    private static ContentDocumentLink createContentLink(String contentVersionId, String recordId) {
      if (contentVersionId == null || recordId == null) { return null; }
          ContentDocumentLink cdl = new ContentDocumentLink();
          List<ContentDocumentLink> cdls = new List<ContentDocumentLink>();
          cdl.ContentDocumentId = [
          SELECT ContentDocumentId 
          FROM ContentVersion 
          WHERE Id =: contentVersionId
          ].ContentDocumentId;
          cdl.LinkedEntityId = recordId;
          // ShareType is either 'V', 'C', or 'I'
          // V = Viewer, C = Collaborator, I = Inferred
          cdl.ShareType = 'V';
          cdls.add(cdl);
          try {
              //List<String> fieldList1 = new List<String>{'LinkedEntityId','ShareType'};
              List<ContentDocumentLink> cdlsListNew = acct_Mgmt_Controller.objectCreatableNew(cdls);
        	  /*if(acct_Mgmt_Controller.objectCreatable('ContentDocumentLink',fieldList1)){
          		insert cdl;
             }*/
          return cdlsListNew[0];
          } catch(DMLException e) {
          System.debug(e);
          return null;
        }
      }
}