force-app/main/default/objects/Account_Checklist__c/Account_Checklist__c.object-meta.xml
<CustomObject>
    <label>Account Checklist</label>
    <nameField>
        <label>Account Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Checklist__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Checklists</relationshipLabel>
    <relationshipName>Account_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_1__c.field-meta.xml
<CustomField>
    <fullName>Column_1__c</fullName>
    <label>Column 1</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Configuration_Category__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Checklist Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Conf_Category__c.Category_Type__c</field>
            <operation>equals</operation>
            <value>Checklist</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Conf_Category__c</referenceTo>
    <relationshipLabel>Account Checklists</relationshipLabel>
    <relationshipName>Account_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Review__c/Business_Review__c.object-meta.xml
<CustomObject>
    <label>Business Review</label>
    <nameField>
        <label>Business Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Review__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Reviews</relationshipLabel>
    <relationshipName>Business_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Conf_Category__c/Conf_Category__c.object-meta.xml
<CustomObject>
    <label>Configuration Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conf_Category__c/fields/Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Category_Type__c</fullName>
    <label>Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Category_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Health</fullName>
    </customValue>
    <customValue>
        <fullName>Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Company Division</fullName>
    </customValue>
    <customValue>
        <fullName>Relationship Type</fullName>
    </customValue>
    <customValue>
        <fullName>Program Milestone</fullName>
    </customValue>
    <customValue>
        <fullName>Stakeholder Personality</fullName>
    </customValue>
    <customValue>
        <fullName>Budget</fullName>
    </customValue>
    <customValue>
        <fullName>Soft Credit Role</fullName>
    </customValue>
    <customValue>
        <fullName>Target</fullName>
    </customValue>
    <customValue>
        <fullName>Company Offerings</fullName>
    </customValue>
    <customValue>
        <fullName>Credit</fullName>
    </customValue>
    <customValue>
        <fullName>Tab Visibility</fullName>
    </customValue>
    <customValue>
        <fullName>Account Insight</fullName>
    </customValue>
    <customValue>
        <fullName>Bbbb</fullName>
        <isActive>false</isActive>
        <label>Bbbb</label>
    </customValue>
    <customValue>
        <fullName>Aaaa</fullName>
        <isActive>false</isActive>
        <label>Aaaa</label>
    </customValue>
    <description>Category Type Picklist values for Conf_Category_Name Object.</description>
    <masterLabel>Category Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/VarasiFileUploaderHelperTest.cls
@isTest
public class VarasiFileUploaderHelperTest {
	 @testSetup static void DataSet(){
         Account acc = new Account(Name='Test Account');
         insert acc;
         Business_Review__c review2 = new Business_Review__c(Name='Review 2',Account__c=acc.Id);
         insert review2;
         Conf_Category__c config = new Conf_Category__c(Name='Account Onboarding',Category_Type__c='Checklist');
         insert config;
         Account_Checklist__c checklistItem = new Account_Checklist__c(Name='Checklist 1',varasi_am__relatedObjectId__c=review2.Id,Configuration_Category__c=config.Id,Column_1__c='null~null~null~null');
         insert checklistItem;
         Profile p2 = [SELECT Id FROM Profile WHERE Name='Solution Manager']; 
         User u2 = new User(Alias = 'solUser', Email='testsoltionManUser@testorg.com', 
                            EmailEncodingKey='UTF-8', LastName='SolManager', LanguageLocaleKey='en_US', 
                            LocaleSidKey='en_US', ProfileId = p2.Id, 
                            TimeZoneSidKey='America/Los_Angeles', UserName='testuserVarasi@testorg.com');
         insert u2;
         
     }
     @isTest static void uploadFileTEst(){
      Account_Checklist__c checklistItem;
      try{
      checklistItem = [SELECT Id,Name FROM Account_Checklist__c WHERE Name='Checklist 1' WITH SECURITY_ENFORCED LIMIT 1]; }
      catch (System.QueryException exp) {
        AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
        throw e;
      }
      String cdlId=varasiFileUploaderHelper.uploadFile('SSBtIGplZXZhbiA=','trial.txt',checklistItem.Id,'Column_1__c');
      System.assert(cdlId!=null);
      Map<ID, String> contentMap=varasiFileDownloaderHelper.getRelatedFiles(cdlId);
      System.assert(contentMap.size()>0);
      User solManUser = [SELECT id FROM User WHERE Email='testsoltionManUser@testorg.com'];
      System.runAs(solManUser)
      {
             Test.startTest();
             try{
                 Map<ID, String> contentMap2=varasiFileDownloaderHelper.getRelatedFiles(cdlId);
             }
             catch(Exception e){
                 System.assertEquals(true,e.getMessage().contains('Error')||e.getMessage().contains('Insufficient permissions'));
             }
         }
         Test.stopTest();
  	}
}