force-app/main/default/objects/Account_Checklist__c/Account_Checklist__c.object-meta.xml
<CustomObject>
    <label>Account Checklist</label>
    <nameField>
        <label>Account Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Checklist__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Checklists</relationshipLabel>
    <relationshipName>Account_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_10__c.field-meta.xml
<CustomField>
    <fullName>Column_10__c</fullName>
    <label>Column 10</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_11__c.field-meta.xml
<CustomField>
    <fullName>Column_11__c</fullName>
    <label>Column 11</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_12__c.field-meta.xml
<CustomField>
    <fullName>Column_12__c</fullName>
    <label>Column 12</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_13__c.field-meta.xml
<CustomField>
    <fullName>Column_13__c</fullName>
    <label>Column 13</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_14__c.field-meta.xml
<CustomField>
    <fullName>Column_14__c</fullName>
    <label>Column 14</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_15__c.field-meta.xml
<CustomField>
    <fullName>Column_15__c</fullName>
    <label>Column 15</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_16__c.field-meta.xml
<CustomField>
    <fullName>Column_16__c</fullName>
    <label>Column 16</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_17__c.field-meta.xml
<CustomField>
    <fullName>Column_17__c</fullName>
    <label>Column 17</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_18__c.field-meta.xml
<CustomField>
    <fullName>Column_18__c</fullName>
    <label>Column 18</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_19__c.field-meta.xml
<CustomField>
    <fullName>Column_19__c</fullName>
    <label>Column 19</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_1__c.field-meta.xml
<CustomField>
    <fullName>Column_1__c</fullName>
    <label>Column 1</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_20__c.field-meta.xml
<CustomField>
    <fullName>Column_20__c</fullName>
    <label>Column 20</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_21__c.field-meta.xml
<CustomField>
    <fullName>Column_21__c</fullName>
    <label>Column 21</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_22__c.field-meta.xml
<CustomField>
    <fullName>Column_22__c</fullName>
    <label>Column 22</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_23__c.field-meta.xml
<CustomField>
    <fullName>Column_23__c</fullName>
    <label>Column 23</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_24__c.field-meta.xml
<CustomField>
    <fullName>Column_24__c</fullName>
    <label>Column 24</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_25__c.field-meta.xml
<CustomField>
    <fullName>Column_25__c</fullName>
    <label>Column 25</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_26__c.field-meta.xml
<CustomField>
    <fullName>Column_26__c</fullName>
    <label>Column 26</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_27__c.field-meta.xml
<CustomField>
    <fullName>Column_27__c</fullName>
    <label>Column 27</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_28__c.field-meta.xml
<CustomField>
    <fullName>Column_28__c</fullName>
    <label>Column 28</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_29__c.field-meta.xml
<CustomField>
    <fullName>Column_29__c</fullName>
    <label>Column 29</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_2__c.field-meta.xml
<CustomField>
    <fullName>Column_2__c</fullName>
    <label>Column 2</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_30__c.field-meta.xml
<CustomField>
    <fullName>Column_30__c</fullName>
    <label>Column 30</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_31__c.field-meta.xml
<CustomField>
    <fullName>Column_31__c</fullName>
    <label>Column 31</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_32__c.field-meta.xml
<CustomField>
    <fullName>Column_32__c</fullName>
    <label>Column 32</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_33__c.field-meta.xml
<CustomField>
    <fullName>Column_33__c</fullName>
    <label>Column 33</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_34__c.field-meta.xml
<CustomField>
    <fullName>Column_34__c</fullName>
    <label>Column 34</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_35__c.field-meta.xml
<CustomField>
    <fullName>Column_35__c</fullName>
    <label>Column 35</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_36__c.field-meta.xml
<CustomField>
    <fullName>Column_36__c</fullName>
    <label>Column 36</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_37__c.field-meta.xml
<CustomField>
    <fullName>Column_37__c</fullName>
    <label>Column 37</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_38__c.field-meta.xml
<CustomField>
    <fullName>Column_38__c</fullName>
    <label>Column 38</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_39__c.field-meta.xml
<CustomField>
    <fullName>Column_39__c</fullName>
    <label>Column 39</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_3__c.field-meta.xml
<CustomField>
    <fullName>Column_3__c</fullName>
    <label>Column 3</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_40__c.field-meta.xml
<CustomField>
    <fullName>Column_40__c</fullName>
    <label>Column 40</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_41__c.field-meta.xml
<CustomField>
    <fullName>Column_41__c</fullName>
    <label>Column 41</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_42__c.field-meta.xml
<CustomField>
    <fullName>Column_42__c</fullName>
    <label>Column 42</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_43__c.field-meta.xml
<CustomField>
    <fullName>Column_43__c</fullName>
    <label>Column 43</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_44__c.field-meta.xml
<CustomField>
    <fullName>Column_44__c</fullName>
    <label>Column 44</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_45__c.field-meta.xml
<CustomField>
    <fullName>Column_45__c</fullName>
    <label>Column 45</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_46__c.field-meta.xml
<CustomField>
    <fullName>Column_46__c</fullName>
    <label>Column 46</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_47__c.field-meta.xml
<CustomField>
    <fullName>Column_47__c</fullName>
    <label>Column 47</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_48__c.field-meta.xml
<CustomField>
    <fullName>Column_48__c</fullName>
    <label>Column 48</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_49__c.field-meta.xml
<CustomField>
    <fullName>Column_49__c</fullName>
    <label>Column 49</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_4__c.field-meta.xml
<CustomField>
    <fullName>Column_4__c</fullName>
    <label>Column 4</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_50__c.field-meta.xml
<CustomField>
    <fullName>Column_50__c</fullName>
    <label>Column 50</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_5__c.field-meta.xml
<CustomField>
    <fullName>Column_5__c</fullName>
    <label>Column 5</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_6__c.field-meta.xml
<CustomField>
    <fullName>Column_6__c</fullName>
    <label>Column 6</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_7__c.field-meta.xml
<CustomField>
    <fullName>Column_7__c</fullName>
    <label>Column 7</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_8__c.field-meta.xml
<CustomField>
    <fullName>Column_8__c</fullName>
    <label>Column 8</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_9__c.field-meta.xml
<CustomField>
    <fullName>Column_9__c</fullName>
    <label>Column 9</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Configuration_Category__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Checklist Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Conf_Category__c.Category_Type__c</field>
            <operation>equals</operation>
            <value>Checklist</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Conf_Category__c</referenceTo>
    <relationshipLabel>Account Checklists</relationshipLabel>
    <relationshipName>Account_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Conf_Category__c/Conf_Category__c.object-meta.xml
<CustomObject>
    <label>Configuration Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conf_Category__c/fields/Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Category_Type__c</fullName>
    <label>Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Conf_Category__c/fields/Column_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Name__c</fullName>
    <label>Column Name</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/Configuration_Category_Detail__c.object-meta.xml
<CustomObject>
    <label>Configuration Category Detail</label>
    <nameField>
        <label>Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Category Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Column_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Name__c</fullName>
    <label>Column Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Column_Owner__c.field-meta.xml
<CustomField>
    <fullName>Column_Owner__c</fullName>
    <label>Column Owner</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Configuration_Category__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Category__c</fullName>
    <label>Configuration Category</label>
    <referenceTo>Conf_Category__c</referenceTo>
    <relationshipName>Category_Configuration_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Category_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Health</fullName>
    </customValue>
    <customValue>
        <fullName>Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Company Division</fullName>
    </customValue>
    <customValue>
        <fullName>Relationship Type</fullName>
    </customValue>
    <customValue>
        <fullName>Program Milestone</fullName>
    </customValue>
    <customValue>
        <fullName>Stakeholder Personality</fullName>
    </customValue>
    <customValue>
        <fullName>Budget</fullName>
    </customValue>
    <customValue>
        <fullName>Soft Credit Role</fullName>
    </customValue>
    <customValue>
        <fullName>Target</fullName>
    </customValue>
    <customValue>
        <fullName>Company Offerings</fullName>
    </customValue>
    <customValue>
        <fullName>Credit</fullName>
    </customValue>
    <customValue>
        <fullName>Tab Visibility</fullName>
    </customValue>
    <customValue>
        <fullName>Account Insight</fullName>
    </customValue>
    <customValue>
        <fullName>Bbbb</fullName>
        <isActive>false</isActive>
        <label>Bbbb</label>
    </customValue>
    <customValue>
        <fullName>Aaaa</fullName>
        <isActive>false</isActive>
        <label>Aaaa</label>
    </customValue>
    <description>Category Type Picklist values for Conf_Category_Name Object.</description>
    <masterLabel>Category Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Account_Checklist_Helper.cls
public with sharing class Account_Checklist_Helper {
    
    // @AuraEnabled(cacheable=true)
    // public static Map<String,String>  getChecklist(Id accChecklistId){
    //     Account_Checklist__c checklist1;
    //     try{
    //         checklist1 = [select Id,Name,Configuration_Category__c from  Account_Checklist__c where Id =: accChecklistId WITH SECURITY_ENFORCED];
    //     }
    //     catch (System.QueryException exp) {
    //         AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
    //         throw e;
    //     }
    //     String configCatId = checklist1.Configuration_Category__c;
    //     Map<String,String> m1 = new Map<String,String>();
    //     List<Configuration_Category_Detail__c> checklist;
    //     try{
    //         checklist = [select Id,Name,Configuration_Category__c,Column_Name__c,Column_Owner__c from Configuration_Category_Detail__c Where Configuration_Category__c=:configCatId WITH SECURITY_ENFORCED];
    //     }
    //     catch (System.QueryException exp) {
    //         AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
    //         throw e;
    //     }
    //     for(Configuration_Category_Detail__c check:checklist){
    //        m1.put(check.varasi_am__Column_Name__c,check.Name);
    //     }
    //     return m1;
    // }
    @AuraEnabled(cacheable=true)
    public static List<Map<String,String>>  getUsers(){
        List<Map<String,string>> userOptions = new List<Map<String,String>>();
        List<User> users;
        try{
            users = [Select id,name from User where id!='' WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        for(user u:users){
            Map<String,String> uMap = new Map<String,String>();
            uMap.put('value', u.id);
            uMap.put('label', u.Name);
            userOptions.add(uMap);
        }
        return userOptions;
    }
    @AuraEnabled(cacheable=true)
    public static List<ChecklistWrapper>  getChecklist11(Id accChecklistId){
        Account_Checklist__c checklist1;
        try{
            checklist1 = [select Id,Name,Configuration_Category__c,
                varasi_am__relatedObjectId__c,
                Column_1__c,Column_2__c,Column_3__c,Column_4__c,Column_5__c,Column_6__c,Column_7__c,Column_8__c,Column_9__c,Column_10__c,
                Column_11__c,Column_12__c,Column_13__c,Column_14__c,Column_15__c,Column_16__c,Column_17__c,Column_18__c,Column_19__c,
                Column_20__c,Column_21__c,Column_22__c,Column_23__c,Column_24__c,Column_25__c,Column_26__c,Column_27__c,Column_28__c,Column_29__c,
                Column_30__c,Column_31__c,Column_32__c,Column_33__c,Column_34__c,Column_35__c,Column_36__c,Column_37__c,Column_38__c,Column_39__c,
                Column_40__c,Column_41__c,Column_42__c,Column_43__c,Column_44__c,Column_45__c,Column_46__c,Column_47__c,Column_48__c,Column_49__c,Column_50__c 
                from  Account_Checklist__c where Id =: accChecklistId WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        String configCatId = checklist1.Configuration_Category__c;
        ChecklistWrapper c =new ChecklistWrapper();
        List<ChecklistWrapper> chkList = new List<ChecklistWrapper>();
        c.accntId=checklist1.varasi_am__relatedObjectId__c;
        c.categId=configCatId;
        c.checklistId=accChecklistId;
        c.name=null;
        Map<String,String> m1 = new Map<String,String>();
        List<MetricWrapper> mList= new LIst<MetricWrapper>();
        List<Configuration_Category_Detail__c> checklist;
        try{
            checklist = [select Id,Name,Column_Name__c,Column_Owner__c,Configuration_Category__c from Configuration_Category_Detail__c Where Configuration_Category__c=:configCatId WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        for(Configuration_Category_Detail__c check:checklist){
            MetricWrapper m = new MetricWrapper();
            m.Id=check.Id;
            m.colName=check.varasi_am__Column_Name__c;
            m.name=check.name;
            if(checklist1!=null){
                List<String> columnValues=checklist1.get(check.Column_Name__c) == null ? null : string.valueOf(checklist1.get(check.Column_Name__c)).split('~');
                if(columnValues!=null){
                    if(columnValues.size()>0){
                        m.isComplete=columnValues[0]=='null'?null:String.valueOf(columnValues[0]);
                        if(columnValues[0]!='null'){
                            if(columnValues[0]=='In Progress'){
                                m.statusColor='slds-text-color_weak';
                            }
                            else if(columnValues[0]=='Not Started'){
                                m.statusColor='slds-text-color_error';
                            }
                            else if(columnValues[0]=='Complete'){
                                m.statusColor='slds-text-color_success';
                            }
                            else{
                                m.statusColor='slds-text-color_default';
                            }
                        }
                    }
                    if(columnValues.size()>1){
                        m.assignedUser=columnValues[1]=='null'?null:String.valueOf(columnValues[1]);
                    }
                    if(columnValues.size()>2){
                        m.comment=columnValues[2]=='null'?null:String.valueOf(columnValues[2]);
                    }
                    if(columnValues.size()>3){
                        m.deadLineDate=columnValues[3]=='null'?null:String.valueOf(columnValues[3]);
                    }
                }
                else{
                    m.isComplete=null;
                    m.assignedUser=null;
                    m.comment=null;
                    m.deadLineDate=null;
                }
            }
            else{
                m.isComplete=null;
                m.assignedUser=null;
                m.comment=null;
                m.deadLineDate=null;
            }
           mList.add(m);
        }
        c.metrics=mList;
        chkList.add(c);
        return chkList;
    }
    public class ChecklistWrapper{
        @AuraEnabled
        public string checklistId {get;set;}
        @AuraEnabled
        public string name {get;set;}
        @AuraEnabled
        public string accntId {get;set;}
        @AuraEnabled
        public string categId {get;set;}
        @AuraEnabled
        public List<MetricWrapper> metrics {get;set;}
    }
    public class MetricWrapper{
        @AuraEnabled
        public string Id {get;set;}
        @AuraEnabled
        public string colName {get;set;}
        @AuraEnabled
        public string name {get;set;}
        @AuraEnabled
        public String assignedUser {get;set;}
        @AuraEnabled
        public String isComplete {get;set;}
        @AuraEnabled
        public String statusColor {get;set;}
        @AuraEnabled
        public String comment {get;set;}
        @AuraEnabled
        public String deadLineDate {get;set;}
    }
    @AuraEnabled(cacheable=true)
    public static Map<String,String>  getAccountChecklist(Id configCatId){
        Map<String,String> m1 = new Map<String,String>();
        List<Configuration_Category_Detail__c> checklist;
        try{
            checklist = [select Id,Name,Configuration_Category__c,Column_Name__c,Column_Owner__c from Configuration_Category_Detail__c Where Configuration_Category__c=:configCatId WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        for(Configuration_Category_Detail__c check:checklist){
           m1.put(check.varasi_am__Column_Name__c,check.Name);
        }
        return m1;
    }

    @AuraEnabled(cacheable=true)
    public static List<ChecklistWrapper>  getAccountChecklist11(Id configCatId,string recordId){
        ChecklistWrapper c =new ChecklistWrapper();
        List<ChecklistWrapper> chkList = new List<ChecklistWrapper>();
        c.accntId=recordId;
        c.categId=configCatId;
        c.checklistId=null;
        c.name=null;
        Map<String,String> m1 = new Map<String,String>();
        List<MetricWrapper> mList= new LIst<MetricWrapper>();
        List<Configuration_Category_Detail__c> checklist;
        try{
            checklist = [select Id,Name,Column_Name__c,Column_Owner__c,Configuration_Category__c from Configuration_Category_Detail__c Where Configuration_Category__c=:configCatId WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        for(Configuration_Category_Detail__c check:checklist){
            MetricWrapper m = new MetricWrapper();
            m.Id=check.Id;
            m.colName=check.varasi_am__Column_Name__c;
            m.name=check.name;
            m.isComplete='Not Started';
            m.assignedUser=null;
            m.comment=null;
            m.deadLineDate=null;
           mList.add(m);
        }
        c.metrics=mList;
        chkList.add(c);
        return chkList;
    }

    @AuraEnabled(cacheable=true)
    public static List<Conf_Category__c>  getChecklistCategories(){
        List<Conf_Category__c> configCategories;
        try{
            configCategories = [Select Id,Name,Category_Type__c from Conf_Category__c where Category_Type__c='Checklist' WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        return configCategories;
    }
    
   /* public static Boolean isCreateable(Schema.SObjectType objectType, Set<String> fields){
        Boolean retVal = false;
        Map<String, SObjectField > fieldsMap = objectType.getDescribe().fields.getMap();
        for(String fname: fields){
            // If the fields do not exists then we can skip and there will be no change in the DB
            if(!fieldsMap.containsKey(fname) || (fieldsMap.get(fname).getDescribe().isCreateable() && objectType.getDescribe().isCreateable())){
                retVal = true;
            } else {
                return false;
            }
        }
        return retVal;
    }*/

    @AuraEnabled
    public static void  savedChecklistData(List<ChecklistWrapper> checkListDataList){
        system.debug(checkListDataList);
        system.debug(checkListDataList.size());
        List<Account_Checklist__c> allCheckList = new List<Account_Checklist__c>();
        Account_Checklist__c checkList = new Account_Checklist__c();

        Id relatedRecordId = checkListDataList.get(0).accntId;
        String sObjName = relatedRecordId.getSObjectType().getDescribe().getName();
        String query = 'SELECT Id,Account__c FROM '+String.escapeSingleQuotes(sObjName) +' WHERE Id=:relatedRecordId LIMIT 1';
        List<sObject> relatedObjRecord=Database.query(query);
        checkList.varasi_am__Account__c =(Id) relatedObjRecord.get(0).get('Account__c');
        checkList.id=checkListDataList.get(0).checklistId;
        if(checkListDataList.get(0).checklistId==null){
            checkList.name=checkListDataList.get(0).name;
            checkList.varasi_am__relatedObjectId__c=checkListDataList.get(0).accntId;
            checkList.Configuration_Category__c=checkListDataList.get(0).categId;
        }
        for (Integer i = 0; i < checkListDataList.get(0).metrics.size(); i++) {
            string colValue = string.valueOf(checkListDataList.get(0).metrics[i].isComplete)+ '~'+ string.valueOf(checkListDataList.get(0).metrics[i].assignedUser)+'~'+string.valueOf(checkListDataList.get(0).metrics[i].comment) + '~' +string.valueOf(checkListDataList.get(0).metrics[i].deadLineDate);
            checkList.put(checkListDataList.get(0).metrics[i].colName,colValue);
        }
        /*for(ChecklistWrapper checkListData:checkListDataList){
            relatedObjectIds.add(checkListData.accntId);
            checkList.id=checkListData.checklistId;
            if(checkListData.checklistId==null){
                checkList.name=checkListData.name;
                checkList.varasi_am__relatedObjectId__c=checkListData.accntId;
                checkList.Configuration_Category__c=checkListData.categId;
            }
            for (Integer i = 0; i < checkListData.metrics.size(); i++) {
                string colValue = string.valueOf(checkListData.metrics[i].isComplete)+ '~'+ string.valueOf(checkListData.metrics[i].assignedUser)+'~'+string.valueOf(checkListData.metrics[i].comment) + '~' +string.valueOf(checkListData.metrics[i].deadLineDate);
                checkList.put(checkListData.metrics[i].colName,colValue);
            }
        }*/
        allCheckList.add(checkList);
        List<Account_Checklist__c> updateList = new List<Account_Checklist__c>();
        List<Account_Checklist__c> createList = new List<Account_Checklist__c>();
        for(Account_Checklist__c n : allCheckList){
            if(n.Id != null){
                updateList.add(n);
            }else{
                createList.add(n);
            }
        }
        if(createList.size()>0){
            acct_Mgmt_Controller.objectCreatableNew(createList);
            /*Schema.SObjectType objectType =createList.getSObjectType();
            Set<String> fieldSet = new Set<String>();
            for(Account_Checklist__c a : createList){
                Set<String> populatedFields = a.getPopulatedFieldsAsMap().keySet();
                for(String s : populatedFields){
                   // if(s!= 'Id'){
                        fieldSet.add(s);
                  //  }
                } 
            }*/
              
        }
        if(updateList.size()>0){
            acct_Mgmt_Controller.objectUpdatableNew(updateList);   
        }
        
        //List<String> fieldList = new List<String>{'Name','varasi_am__relatedObjectId__c','varasi_am__Configuration_Category__c'};
        //acct_Mgmt_Controller.objectUpsertableNew(allCheckList);
        /*if(acct_Mgmt_Controller.objectUpdateable('Account_Checklist__c',fieldList) && acct_Mgmt_Controller.objectCreatable('Account_Checklist__c',fieldList)){
        	upsert checkList;
        }*/
    }
}