force-app/main/default/objects/Account_Checklist__c/Account_Checklist__c.object-meta.xml
<CustomObject>
    <label>Account Checklist</label>
    <nameField>
        <label>Account Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Checklist__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Checklists</relationshipLabel>
    <relationshipName>Account_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_10__c.field-meta.xml
<CustomField>
    <fullName>Column_10__c</fullName>
    <label>Column 10</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_11__c.field-meta.xml
<CustomField>
    <fullName>Column_11__c</fullName>
    <label>Column 11</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_12__c.field-meta.xml
<CustomField>
    <fullName>Column_12__c</fullName>
    <label>Column 12</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_13__c.field-meta.xml
<CustomField>
    <fullName>Column_13__c</fullName>
    <label>Column 13</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_14__c.field-meta.xml
<CustomField>
    <fullName>Column_14__c</fullName>
    <label>Column 14</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_15__c.field-meta.xml
<CustomField>
    <fullName>Column_15__c</fullName>
    <label>Column 15</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_16__c.field-meta.xml
<CustomField>
    <fullName>Column_16__c</fullName>
    <label>Column 16</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_17__c.field-meta.xml
<CustomField>
    <fullName>Column_17__c</fullName>
    <label>Column 17</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_18__c.field-meta.xml
<CustomField>
    <fullName>Column_18__c</fullName>
    <label>Column 18</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_19__c.field-meta.xml
<CustomField>
    <fullName>Column_19__c</fullName>
    <label>Column 19</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_1__c.field-meta.xml
<CustomField>
    <fullName>Column_1__c</fullName>
    <label>Column 1</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_20__c.field-meta.xml
<CustomField>
    <fullName>Column_20__c</fullName>
    <label>Column 20</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_21__c.field-meta.xml
<CustomField>
    <fullName>Column_21__c</fullName>
    <label>Column 21</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_22__c.field-meta.xml
<CustomField>
    <fullName>Column_22__c</fullName>
    <label>Column 22</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_23__c.field-meta.xml
<CustomField>
    <fullName>Column_23__c</fullName>
    <label>Column 23</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_24__c.field-meta.xml
<CustomField>
    <fullName>Column_24__c</fullName>
    <label>Column 24</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_25__c.field-meta.xml
<CustomField>
    <fullName>Column_25__c</fullName>
    <label>Column 25</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_26__c.field-meta.xml
<CustomField>
    <fullName>Column_26__c</fullName>
    <label>Column 26</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_27__c.field-meta.xml
<CustomField>
    <fullName>Column_27__c</fullName>
    <label>Column 27</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_28__c.field-meta.xml
<CustomField>
    <fullName>Column_28__c</fullName>
    <label>Column 28</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_29__c.field-meta.xml
<CustomField>
    <fullName>Column_29__c</fullName>
    <label>Column 29</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_2__c.field-meta.xml
<CustomField>
    <fullName>Column_2__c</fullName>
    <label>Column 2</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_30__c.field-meta.xml
<CustomField>
    <fullName>Column_30__c</fullName>
    <label>Column 30</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_31__c.field-meta.xml
<CustomField>
    <fullName>Column_31__c</fullName>
    <label>Column 31</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_32__c.field-meta.xml
<CustomField>
    <fullName>Column_32__c</fullName>
    <label>Column 32</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_33__c.field-meta.xml
<CustomField>
    <fullName>Column_33__c</fullName>
    <label>Column 33</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_34__c.field-meta.xml
<CustomField>
    <fullName>Column_34__c</fullName>
    <label>Column 34</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_35__c.field-meta.xml
<CustomField>
    <fullName>Column_35__c</fullName>
    <label>Column 35</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_36__c.field-meta.xml
<CustomField>
    <fullName>Column_36__c</fullName>
    <label>Column 36</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_37__c.field-meta.xml
<CustomField>
    <fullName>Column_37__c</fullName>
    <label>Column 37</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_38__c.field-meta.xml
<CustomField>
    <fullName>Column_38__c</fullName>
    <label>Column 38</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_39__c.field-meta.xml
<CustomField>
    <fullName>Column_39__c</fullName>
    <label>Column 39</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_3__c.field-meta.xml
<CustomField>
    <fullName>Column_3__c</fullName>
    <label>Column 3</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_40__c.field-meta.xml
<CustomField>
    <fullName>Column_40__c</fullName>
    <label>Column 40</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_41__c.field-meta.xml
<CustomField>
    <fullName>Column_41__c</fullName>
    <label>Column 41</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_42__c.field-meta.xml
<CustomField>
    <fullName>Column_42__c</fullName>
    <label>Column 42</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_43__c.field-meta.xml
<CustomField>
    <fullName>Column_43__c</fullName>
    <label>Column 43</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_44__c.field-meta.xml
<CustomField>
    <fullName>Column_44__c</fullName>
    <label>Column 44</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_45__c.field-meta.xml
<CustomField>
    <fullName>Column_45__c</fullName>
    <label>Column 45</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_46__c.field-meta.xml
<CustomField>
    <fullName>Column_46__c</fullName>
    <label>Column 46</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_47__c.field-meta.xml
<CustomField>
    <fullName>Column_47__c</fullName>
    <label>Column 47</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_4__c.field-meta.xml
<CustomField>
    <fullName>Column_4__c</fullName>
    <label>Column 4</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_5__c.field-meta.xml
<CustomField>
    <fullName>Column_5__c</fullName>
    <label>Column 5</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_6__c.field-meta.xml
<CustomField>
    <fullName>Column_6__c</fullName>
    <label>Column 6</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_7__c.field-meta.xml
<CustomField>
    <fullName>Column_7__c</fullName>
    <label>Column 7</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_8__c.field-meta.xml
<CustomField>
    <fullName>Column_8__c</fullName>
    <label>Column 8</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_9__c.field-meta.xml
<CustomField>
    <fullName>Column_9__c</fullName>
    <label>Column 9</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Configuration_Category__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Checklist Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Conf_Category__c.Category_Type__c</field>
            <operation>equals</operation>
            <value>Checklist</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Conf_Category__c</referenceTo>
    <relationshipLabel>Account Checklists</relationshipLabel>
    <relationshipName>Account_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Recommendation__c/Account_Recommendation__c.object-meta.xml
<CustomObject>
    <label>Account Recommendation</label>
    <nameField>
        <label>Account Recommendation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Recommendations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Recommendation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Recommendations</relationshipLabel>
    <relationshipName>Account_Recommendations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Conf_Category__c/Conf_Category__c.object-meta.xml
<CustomObject>
    <label>Configuration Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conf_Category__c/fields/Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Category_Type__c</fullName>
    <label>Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Conf_Category__c/fields/Column_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Name__c</fullName>
    <label>Column Name</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/Configuration_Category_Detail__c.object-meta.xml
<CustomObject>
    <label>Configuration Category Detail</label>
    <nameField>
        <label>Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Category Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Column_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Name__c</fullName>
    <label>Column Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Configuration_Category__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Category__c</fullName>
    <label>Configuration Category</label>
    <referenceTo>Conf_Category__c</referenceTo>
    <relationshipName>Category_Configuration_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Category_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Health</fullName>
    </customValue>
    <customValue>
        <fullName>Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Company Division</fullName>
    </customValue>
    <customValue>
        <fullName>Relationship Type</fullName>
    </customValue>
    <customValue>
        <fullName>Program Milestone</fullName>
    </customValue>
    <customValue>
        <fullName>Stakeholder Personality</fullName>
    </customValue>
    <customValue>
        <fullName>Budget</fullName>
    </customValue>
    <customValue>
        <fullName>Soft Credit Role</fullName>
    </customValue>
    <customValue>
        <fullName>Target</fullName>
    </customValue>
    <customValue>
        <fullName>Company Offerings</fullName>
    </customValue>
    <customValue>
        <fullName>Credit</fullName>
    </customValue>
    <customValue>
        <fullName>Tab Visibility</fullName>
    </customValue>
    <customValue>
        <fullName>Account Insight</fullName>
    </customValue>
    <customValue>
        <fullName>Bbbb</fullName>
        <isActive>false</isActive>
        <label>Bbbb</label>
    </customValue>
    <customValue>
        <fullName>Aaaa</fullName>
        <isActive>false</isActive>
        <label>Aaaa</label>
    </customValue>
    <description>Category Type Picklist values for Conf_Category_Name Object.</description>
    <masterLabel>Category Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AcctChecklist.cls
public with sharing class AcctChecklist implements Callable{
    
     public List<Account_Recommendation__c> UnusedChecklist(String ruleConfig,Boolean postToChatter,List<Account> accountList){
         System.debug('Acct List '+accountList);
        Account_Recommendation__c recom;
        Map<String,Account_Recommendation__c> recomMap = new Map<String,Account_Recommendation__c>();
        List<Account_Recommendation__c> savedRecomList = new List<Account_Recommendation__c>();
        try{
          savedRecomList = [Select id,varasi_am__Account__c,varasi_am__Date__c,varasi_am__Done__c,varasi_am__Recommendation__c,varasi_am__Reference_ID__c,varasi_am__Status__c,varasi_am__Rule__c,varasi_am__Expiry_Date__c,Name from Account_Recommendation__c where Name='Account Checklist' WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
          AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
          throw e;
      }
        for (Account_Recommendation__c rec : savedRecomList) {
          recomMap.put(rec.varasi_am__Reference_ID__c,rec);
        }
         List<Account_Recommendation__c> recomList = new List<Account_Recommendation__c>();
         List<Configuration_Category_Detail__c> chkCategory;
          List<Account_Checklist__c> checklists;
          try{
            chkCategory = [SELECT Id,Column_Name__c,Configuration_Category__c,Configuration_Category__r.Name,Configuration_Category__r.Category_Type__c FROM Configuration_Category_Detail__c
            WHERE Configuration_Category__r.Category_Type__c = 'Checklist' WITH SECURITY_ENFORCED];
            checklists= [SELECT Id,Name,CreatedDate,Configuration_Category__c,Configuration_Category__r.Name,Account__c,
            Column_1__c,Column_2__c,Column_3__c,Column_4__c,Column_5__c,Column_6__c,Column_7__c,Column_8__c,Column_9__c,Column_10__c,
            Column_11__c,Column_12__c,Column_13__c,Column_14__c,Column_15__c,Column_16__c,Column_17__c,Column_18__c,Column_19__c,
            Column_20__c,Column_21__c,Column_22__c,Column_23__c,Column_24__c,Column_25__c,Column_26__c,Column_27__c,Column_28__c,Column_29__c,
            Column_30__c,Column_31__c,Column_32__c,Column_33__c,Column_34__c,Column_35__c,Column_36__c,Column_37__c,Column_38__c,Column_39__c,
            Column_40__c,Column_41__c,Column_42__c,Column_43__c,Column_44__c,Column_45__c,Column_46__c,Column_47__c,Column_48__c,Column_49__c,Column_50__c              
            FROM Account_Checklist__c where id!='' AND Account__c IN: accountList WITH SECURITY_ENFORCED];
          }
    catch (System.QueryException exp) {
      AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
      throw e;
    }
        for (Account account : accountList) {
          /*List<Configuration_Category_Detail__c> chkCategory;
          List<Account_Checklist__c> checklists;
          try{
            chkCategory = [SELECT Id,Column_Name__c,Configuration_Category__c,Configuration_Category__r.Name,Configuration_Category__r.Category_Type__c FROM Configuration_Category_Detail__c
            WHERE Configuration_Category__r.Category_Type__c = 'Checklist' WITH SECURITY_ENFORCED];
            checklists= [SELECT Id,Name,CreatedDate,Configuration_Category__c,Configuration_Category__r.Name,
            Column_1__c,Column_2__c,Column_3__c,Column_4__c,Column_5__c,Column_6__c,Column_7__c,Column_8__c,Column_9__c,Column_10__c,
            Column_11__c,Column_12__c,Column_13__c,Column_14__c,Column_15__c,Column_16__c,Column_17__c,Column_18__c,Column_19__c,
            Column_20__c,Column_21__c,Column_22__c,Column_23__c,Column_24__c,Column_25__c,Column_26__c,Column_27__c,Column_28__c,Column_29__c,
            Column_30__c,Column_31__c,Column_32__c,Column_33__c,Column_34__c,Column_35__c,Column_36__c,Column_37__c,Column_38__c,Column_39__c,
            Column_40__c,Column_41__c,Column_42__c,Column_43__c,Column_44__c,Column_45__c,Column_46__c,Column_47__c,Column_48__c,Column_49__c,Column_50__c              
            FROM Account_Checklist__c where id!='' WITH SECURITY_ENFORCED];
          }
    catch (System.QueryException exp) {
      AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
      throw e;
    }*/
            for(Integer i=0;i<checklists.size();i++){
                if(account.Id == checklists[i].Account__c){
                    DateTime checklistDateTime = checklists[i].CreatedDate;
                    checklistDateTime = checklistDateTime.addDays(Integer.valueOf(ruleConfig));
                    if(checklistDateTime < DateTime.now()){
                      Decimal progress = 0 ;
                      Decimal count =0;

                      System.debug(checklists[i].Name);
                      for(Configuration_Category_Detail__c categ: chkCategory){
                      	if(checklists[i].Configuration_Category__c == categ.Configuration_Category__c){
                          system.debug('count : '+ count + ' - ' +checklists[i].get(categ.Column_Name__c));
                           count++;
                           if(!String.isEmpty(String.valueOf(checklists[i].get(categ.Column_Name__c)))){
                            String status=String.valueOf(checklists[i].get(categ.Column_Name__c)).split('~')[0];
                            if(status=='Complete' || status=='In Progress'){
                                  progress++;
                              }
                           }
                            }
                    	}
                        if(progress<=0){
                            if(recomMap.containsKey(checklists[i].Id)){
                                recom = recomMap.get(checklists[i].Id);
                            }else{
                                String description = checklists[i].Name+' is Unused';
                                recom = new Account_Recommendation__c(varasi_am__Date__c=System.today(),varasi_am__Reference_ID__c=checklists[i].Id,varasi_am__Status__c='Open',Name='Account Checklist',varasi_am__Account__c=account.Id,varasi_am__Done__c=false,varasi_am__Recommendation__c=description);
                                //List<String> fieldList1 = new List<String>{'ParentId','Body'};
                                 FeedItem post = new FeedItem();
                                 List<FeedItem> posts = new List<FeedItem>();
                                 post.ParentId = account.Id;
                                 post.Body = description;
                                 posts.add(post);
                                      acct_Mgmt_Controller.objectCreatableNew(posts);
                                /* if(acct_Mgmt_Controller.objectUpdateable('FeedItem',fieldList1)){
                                    FeedItem post = new FeedItem();
                                    post.ParentId = Userinfo.getUserId();
                                    post.Body = description;
                                              insert post;
                                }*/
                            }
                            recomList.add(recom);
                        } 
                        else{
                            if(recomMap.containsKey(checklists[i].Id)){
                                recom = recomMap.get(checklists[i].Id);
                                recom.varasi_am__Status__c='Resolved';
                                recomList.add(recom);
                            }
                        }
                    }
                }
                
            }
        }
         return recomList;
      }   

    public Object call(String action, Map<String, Object> args) {
        switch on action {
          when 'UnusedChecklist' {
            return this.UnusedChecklist((String)args.get('ruleConfig'),(Boolean)args.get('postToChatter'),(List<Account>)args.get('accountList'));
          }
          when else {
           throw new ExtensionMalformedCallException('Method not implemented');
          }
        }
    }
    public class ExtensionMalformedCallException extends Exception {}
}