force-app/main/default/objects/Account_Checklist__c/Account_Checklist__c.object-meta.xml
<CustomObject>
    <label>Account Checklist</label>
    <nameField>
        <label>Account Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Checklist__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Checklists</relationshipLabel>
    <relationshipName>Account_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Column_1__c.field-meta.xml
<CustomField>
    <fullName>Column_1__c</fullName>
    <label>Column 1</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Checklist__c/fields/Configuration_Category__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Checklist Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Conf_Category__c.Category_Type__c</field>
            <operation>equals</operation>
            <value>Checklist</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Conf_Category__c</referenceTo>
    <relationshipLabel>Account Checklists</relationshipLabel>
    <relationshipName>Account_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Insight__mdt/Account_Insight__mdt.object-meta.xml
<CustomObject>
    <label>Account Insight</label>
    <pluralLabel>Account Insights</pluralLabel>
</CustomObject>

force-app/main/default/objects/Account_Insight__mdt/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Class Name</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Insight__mdt/fields/Function_Name__c.field-meta.xml
<CustomField>
    <fullName>Function_Name__c</fullName>
    <label>Function Name</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Insight__mdt/fields/Rule_Config__c.field-meta.xml
<CustomField>
    <fullName>Rule_Config__c</fullName>
    <label>Rule Config</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Insight_Rule__c/Account_Insight_Rule__c.object-meta.xml
<CustomObject>
    <label>Account Insight Rule</label>
    <nameField>
        <displayFormat>AIR-{0000}</displayFormat>
        <label>Account Insight Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Insight Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Recommendation__c/Account_Recommendation__c.object-meta.xml
<CustomObject>
    <label>Account Recommendation</label>
    <nameField>
        <label>Account Recommendation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Recommendations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Recommendation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Recommendations</relationshipLabel>
    <relationshipName>Account_Recommendations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Review__c/Business_Review__c.object-meta.xml
<CustomObject>
    <label>Business Review</label>
    <nameField>
        <label>Business Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Review__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Reviews</relationshipLabel>
    <relationshipName>Business_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Conf_Category__c/Conf_Category__c.object-meta.xml
<CustomObject>
    <label>Configuration Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conf_Category__c/fields/Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Category_Type__c</fullName>
    <label>Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Conf_Category__c/fields/Function_Name__c.field-meta.xml
<CustomField>
    <fullName>Function_Name__c</fullName>
    <label>Function Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conf_Category__c/fields/Rule_Config__c.field-meta.xml
<CustomField>
    <fullName>Rule_Config__c</fullName>
    <label>Rule Config</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Category_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Health</fullName>
    </customValue>
    <customValue>
        <fullName>Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Company Division</fullName>
    </customValue>
    <customValue>
        <fullName>Relationship Type</fullName>
    </customValue>
    <customValue>
        <fullName>Program Milestone</fullName>
    </customValue>
    <customValue>
        <fullName>Stakeholder Personality</fullName>
    </customValue>
    <customValue>
        <fullName>Budget</fullName>
    </customValue>
    <customValue>
        <fullName>Soft Credit Role</fullName>
    </customValue>
    <customValue>
        <fullName>Target</fullName>
    </customValue>
    <customValue>
        <fullName>Company Offerings</fullName>
    </customValue>
    <customValue>
        <fullName>Credit</fullName>
    </customValue>
    <customValue>
        <fullName>Tab Visibility</fullName>
    </customValue>
    <customValue>
        <fullName>Account Insight</fullName>
    </customValue>
    <customValue>
        <fullName>Bbbb</fullName>
        <isActive>false</isActive>
        <label>Bbbb</label>
    </customValue>
    <customValue>
        <fullName>Aaaa</fullName>
        <isActive>false</isActive>
        <label>Aaaa</label>
    </customValue>
    <description>Category Type Picklist values for Conf_Category_Name Object.</description>
    <masterLabel>Category Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Account_Rule_Helper_Test.cls
@isTest
public class Account_Rule_Helper_Test {
	
    @testSetup
    public static void dataSet(){
        
       // Account_Insight_Rule__c rule = new Account_Insight_Rule__c(Class_Name__c='AcctChecklist',Function_Name__c='UnusedChecklist',Rule_Config__c='0');
     	//insert rule;
     //   Account_Insight_Rule__c rule2 = new Account_Insight_Rule__c(Class_Name__c='AcctHealthInsights',Function_Name__c='ScoreDrop',Rule_Config__c='0.10');
     //	insert rule2;
        Account acc = new Account(Name='Test Account');
        insert acc;
        Business_Review__c review = new Business_Review__c(Name='Review 1',Account__c=acc.Id);
        insert review;
        Conf_Category__c config = new Conf_Category__c(Name='Account Onboarding',Category_Type__c='Checklist');
        insert config;
        Account_Checklist__c checklistItem = new Account_Checklist__c(Name='Checklist 1',Account__c=acc.Id,varasi_am__relatedObjectId__c=review.Id,Configuration_Category__c=config.Id,Column_1__c='true~null~null');
        insert checklistItem;
         Profile p2 = [SELECT Id FROM Profile WHERE Name='Solution Manager']; 
  		User u2 = new User(Alias = 'solUser', Email='testsoltionManUser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='SolManager', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p2.Id, 
        TimeZoneSidKey='America/Los_Angeles', UserName='testuserVarasi@testorg.com');
        insert u2;
    }
    
    static testMethod void getInsightRulesTest(){
        // List<Account_Insight__mdt> expectedruleList;
        // try{
        //     expectedruleList = [Select Id from Account_Insight__mdt WHERE Id != null WITH SECURITY_ENFORCED];
        // }
        // catch (System.QueryException exp) {
        //     AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
        //     throw e;
        // }
        List<varasi_am__Conf_Category__c> actualruleList = Account_Rule_Helper.getInsightRules();
        //System.assertEquals(expectedruleList.size(), actualruleList.size());
        system.assert(actualruleList.size()>=0, 'No Insights records present');
    }
    
    static testMethod void getInsightRulesExceptionTest(){
        // List<Account_Insight__mdt> expectedruleList;
        // try{
        //     expectedruleList = [Select Id from Account_Insight__mdt WHERE Id != null WITH SECURITY_ENFORCED];
        // }
        // catch (System.QueryException exp) {
        //     AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
        //     throw e;
        // }
        User solManUser = [SELECT id FROM User WHERE Email='testsoltionManUser@testorg.com'];
		System.runAs(solManUser) 
        {
            Test.startTest();
			try{
				List<varasi_am__Conf_Category__c> actualruleList = Account_Rule_Helper.getInsightRules();   
			}
			catch(Exception e){
				System.assertEquals(true,e.getMessage().contains('Error')||e.getMessage().contains('exception'));  
			}
			Test.stopTest();
        }
    }
    
    static testMethod void callBatchTest(){
        Account_Rule_Helper.callBatch(); 
        List<Account_Recommendation__c> recommendations;
        try{
            recommendations = [Select Id from Account_Recommendation__c WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        System.assertEquals(recommendations.size(), 0);
    }
    
    static testMethod void scheduleBatchTest(){
        Account_Rule_Helper.scheduleBatch();
        List<AsyncApexJob> jobsScheduled;
        try{
            jobsScheduled = [select Id, ApexClassID, ApexClass.Name, Status, JobType from AsyncApexJob where JobType = 'ScheduledApex' WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        System.assertEquals(1, jobsScheduled.size());
    }
    
    static testMethod void isJobScheduledTest(){
        Account_Batch_Schedule abs = new Account_Batch_Schedule();
        String schedule = '0 1 * * * ?';
        Id jobID = system.schedule('Acct_Insights',schedule,abs);
        Boolean res = Account_Rule_Helper.isJobScheduled();
        System.assertEquals(true, res);
    }
    
    static testMethod void deleteJobTest(){
        Account_Batch_Schedule abs = new Account_Batch_Schedule();
        String schedule = '0 1 * * * ?';
        Id jobID = system.schedule('Acct_Insights',schedule,abs);
        Account_Rule_Helper.deleteJob();
        Boolean res = Account_Rule_Helper.isJobScheduled();
        System.assertEquals(false, res);
        
    }
}