force-app/main/default/objects/Conf_Category__c/Conf_Category__c.object-meta.xml
<CustomObject>
    <label>Configuration Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conf_Category__c/fields/Available_Column_Names__c.field-meta.xml
<CustomField>
    <fullName>Available_Column_Names__c</fullName>
    <label>Available Column Names</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Conf_Category__c/fields/Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Category_Type__c</fullName>
    <label>Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Conf_Category__c/fields/Column_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Name__c</fullName>
    <label>Column Name</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/Configuration_Category_Detail__c.object-meta.xml
<CustomObject>
    <label>Configuration Category Detail</label>
    <nameField>
        <label>Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Category Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Column_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Name__c</fullName>
    <label>Column Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Configuration_Category__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Category__c</fullName>
    <label>Configuration Category</label>
    <referenceTo>Conf_Category__c</referenceTo>
    <relationshipName>Category_Configuration_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Category_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Health</fullName>
    </customValue>
    <customValue>
        <fullName>Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Company Division</fullName>
    </customValue>
    <customValue>
        <fullName>Relationship Type</fullName>
    </customValue>
    <customValue>
        <fullName>Program Milestone</fullName>
    </customValue>
    <customValue>
        <fullName>Stakeholder Personality</fullName>
    </customValue>
    <customValue>
        <fullName>Budget</fullName>
    </customValue>
    <customValue>
        <fullName>Soft Credit Role</fullName>
    </customValue>
    <customValue>
        <fullName>Target</fullName>
    </customValue>
    <customValue>
        <fullName>Company Offerings</fullName>
    </customValue>
    <customValue>
        <fullName>Credit</fullName>
    </customValue>
    <customValue>
        <fullName>Tab Visibility</fullName>
    </customValue>
    <customValue>
        <fullName>Account Insight</fullName>
    </customValue>
    <customValue>
        <fullName>Bbbb</fullName>
        <isActive>false</isActive>
        <label>Bbbb</label>
    </customValue>
    <customValue>
        <fullName>Aaaa</fullName>
        <isActive>false</isActive>
        <label>Aaaa</label>
    </customValue>
    <description>Category Type Picklist values for Conf_Category_Name Object.</description>
    <masterLabel>Category Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/categoriesHelperTest.cls
@isTest
public with sharing class categoriesHelperTest {
    @testSetup
    public static void DataSet(){
        Conf_Category__c config = new Conf_Category__c(Name='New Budget',Category_Type__c='Budget');
        insert config;
        Conf_Category__c config1 = new Conf_Category__c(Name='IT Services',Category_Type__c='Company Offerings',Available_Column_Names__c='varasi_am__Column_3__c');
        insert config1;
        Configuration_Category_Detail__c cDetail = new Configuration_Category_Detail__c(Column_Name__c='varasi_am__Column_1__c',Configuration_Category__c=config.Id);
        insert cDetail;
        Configuration_Category_Detail__c cDetail2 = new Configuration_Category_Detail__c(Column_Name__c='varasi_am__Column_2__c',Configuration_Category__c=config.Id);
        insert cDetail2;
        Conf_Category__c config3 = new Conf_Category__c(Name='New Account Health',Category_Type__c='Account Health');
        insert config3;
        Configuration_Category_Detail__c cDetail3 = new Configuration_Category_Detail__c(Column_Name__c='varasi_am__Column_3__c',Configuration_Category__c=config3.Id);
        insert cDetail3;
        Conf_Category__c config4 = new Conf_Category__c(Name='New Checklist',Category_Type__c='Checklist');
        insert config4;
        Configuration_Category_Detail__c cDetail4 = new Configuration_Category_Detail__c(Column_Name__c='varasi_am__Column_4__c',Configuration_Category__c=config4.Id);
        insert cDetail4;
        Conf_Category__c config5 = new Conf_Category__c(Name='New Target',Category_Type__c='Target');
        insert config5;
        Configuration_Category_Detail__c cDetail5 = new Configuration_Category_Detail__c(Column_Name__c='varasi_am__Column_5__c',Configuration_Category__c=config5.Id);
        insert cDetail5;
        Conf_Category__c config6 = new Conf_Category__c(Name='New Company Offerings',Category_Type__c='Company Offerings');
        insert config6;
        Configuration_Category_Detail__c cDetail6 = new Configuration_Category_Detail__c(Column_Name__c='varasi_am__Column_6__c',Configuration_Category__c=config6.Id);
        insert cDetail6;
    }
    static testMethod void getTreeGridDataTest(){
        List<String> pickListValuesList = new List<String>();
        Schema.DescribeFieldResult fieldResult = Conf_Category__c.Category_Type__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple){
			pickListValuesList.add(pickListVal.getLabel());
		}
        List<categoriesHelper.ConfigWrapper> dataList=categoriesHelper.getTreeGridData();                                        
       	System.assertEquals(pickListValuesList.size(),dataList.size());
    }
    static testMethod void getColumnNameTest(){
        Conf_Category__c categ;
        // try{
            categ=[Select Id,Name from Conf_Category__c where Name='New Budget' ];//WITH SECURITY_ENFORCED];
        // }
        // catch (System.QueryException exp) {
        //     AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
        //     throw e;
        // }
        String colName = categoriesHelper.getColumnName(categ.Id);
        System.assertEquals('varasi_am__Column_3__c',colName );
    
        Conf_Category__c categ2;
        try{
            categ2=[Select Id,Name from Conf_Category__c where Name='IT Services' WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        String colName2 = categoriesHelper.getColumnName(categ2.Id);
        System.assertEquals( 'varasi_am__Column_3__c',colName2 );
    }
    
    static testMethod void deleteMetricTest(){
        Conf_Category__c categ;
        Configuration_Category_Detail__c detail;
        Conf_Category__c categ1;
        Configuration_Category_Detail__c detail1;
        Conf_Category__c categ2;
        Configuration_Category_Detail__c detail2;
        Conf_Category__c categ3;
        Configuration_Category_Detail__c detail3;
        Conf_Category__c categ4;
        Configuration_Category_Detail__c detail4;
        try{
            categ=[Select Id,Name from Conf_Category__c where Name='New Budget' WITH SECURITY_ENFORCED];
            detail=[Select Id,Column_Name__c from Configuration_Category_Detail__c where Column_Name__c=:'varasi_am__Column_1__c'  WITH SECURITY_ENFORCED LIMIT 1];
            categ1=[Select Id,Name from Conf_Category__c where Name='New Account Health' WITH SECURITY_ENFORCED];
            detail1=[Select Id,Column_Name__c from Configuration_Category_Detail__c where Column_Name__c=:'varasi_am__Column_3__c'  WITH SECURITY_ENFORCED];
            categ2=[Select Id,Name from Conf_Category__c where Name='New Checklist' WITH SECURITY_ENFORCED];
            detail2=[Select Id,Column_Name__c from Configuration_Category_Detail__c where Column_Name__c=:'varasi_am__Column_4__c'  WITH SECURITY_ENFORCED];
            categ3=[Select Id,Name from Conf_Category__c where Name='New Target' WITH SECURITY_ENFORCED];
            detail3=[Select Id,Column_Name__c from Configuration_Category_Detail__c where Column_Name__c=:'varasi_am__Column_5__c'  WITH SECURITY_ENFORCED];
            categ4=[Select Id,Name from Conf_Category__c where Name='New Company Offerings' WITH SECURITY_ENFORCED];
            detail4=[Select Id,Column_Name__c from Configuration_Category_Detail__c where Column_Name__c=:'varasi_am__Column_6__c'  WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        categoriesHelper.deleteMetric(categ.Id,  detail.Id);
        categoriesHelper.deleteMetric(categ1.Id,  detail1.Id);
        categoriesHelper.deleteMetric(categ2.Id,  detail2.Id);
        //categoriesHelper.deleteMetric(categ3.Id, 'varasi_am__Column_5__c', detail3.Id);
        //categoriesHelper.deleteMetric(categ4.Id, 'varasi_am__Column_6__c', detail4.Id);
        System.assertEquals(True, True);
    }
}