force-app/main/default/objects/Conf_Category__c/Conf_Category__c.object-meta.xml
<CustomObject>
    <label>Configuration Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Company_Counterpart__c.field-meta.xml
<CustomField>
    <fullName>Company_Counterpart__c</fullName>
    <label>Company Counterpart</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Company_Counterpart_Contact__c.field-meta.xml
<CustomField>
    <fullName>Company_Counterpart_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company Counterpart Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Company_Counterpart_User__c.field-meta.xml
<CustomField>
    <fullName>Company_Counterpart_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company Counterpart User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LinkedIn__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn__c</fullName>
    <label>LinkedIn</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Relationship_Score__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Score__c</fullName>
    <label>Relationship Score</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relationship Type</label>
    <referenceTo>Conf_Category__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Score_Image_Link__c.field-meta.xml
<CustomField>
    <fullName>Score_Image_Link__c</fullName>
    <formula>IF(ISPICKVAL( Relationship_Score__c ,&quot;5&quot;),&quot;/resource/Star5&quot;,
IF(ISPICKVAL( Relationship_Score__c ,&quot;4&quot;),&quot;/resource/Star4&quot;,
IF(ISPICKVAL( Relationship_Score__c ,&quot;3&quot;),&quot;/resource/Star3&quot;,
IF(ISPICKVAL( Relationship_Score__c ,&quot;2&quot;),&quot;/resource/Star2&quot;,
&quot;/resource/Star1&quot;
)
)
)
)</formula>
    <label>Score Image Link</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Soft_Credits__c.field-meta.xml
<CustomField>
    <fullName>Soft_Credits__c</fullName>
    <label>Soft Credits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sponsor_Credit__c.field-meta.xml
<CustomField>
    <fullName>Sponsor_Credit__c</fullName>
    <label>Sponsor Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/relationshipHelper.cls
public with sharing class relationshipHelper {
    @AuraEnabled(cacheable=true)
    public static List<contactWraper> getContacts(String accntId) {
        //Account accnts;
        List<Contact> contacts;
        try{
            /*accnts=[select id,
                        (select name,id,Sponsor_Credit__c,Soft_Credits__c,Relationship_Type__r.name,Relationship_Score__c,Company_Counterpart__c,
                        Company_Counterpart_Contact__r.name,Description,LinkedIn__c,Company_Counterpart_User__r.name,Score_Image_Link__c from contacts) 
                        from account 
                        where id=:accntId WITH SECURITY_ENFORCED]; */
            contacts = [select name,id,AccountId,varasi_am__Sponsor_Credit__c,varasi_am__Soft_Credits__c,varasi_am__Relationship_Type__r.name,varasi_am__Relationship_Score__c,varasi_am__Company_Counterpart__c,
                        varasi_am__Company_Counterpart_Contact__r.name,Description,varasi_am__LinkedIn__c,varasi_am__Company_Counterpart_User__r.name,varasi_am__Score_Image_Link__c,(Select ContactId,Role,Opportunity.Name,Opportunity.Amount,Opportunity.CloseDate,Opportunity.ExpectedRevenue,Opportunity.StageName from OpportunityContactRoles)
                        from contact where AccountId=:accntId WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
              AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
              throw e;
        }
        List<contactWraper> contactsList = new List<contactWraper>();    
        
        //for (Contact c : accnts.contacts) {
        for(Contact c: contacts){
            contactWraper con = new contactWraper();
            con.Id=c.id;
            con.scoreLink = c.Score_Image_Link__c;
            con.softCredit=c.Soft_Credits__c;
            con.sponsorCredit=c.Sponsor_Credit__c;
            con.name=c.name;
            con.recordLink='/'+c.id;
            con.relationshipType=c.Relationship_Type__r.name;
            con.relationshipScore=c.Relationship_Score__c;
            con.description=c.Description;
            con.linkedIn=c.LinkedIn__c;
            
            if(c.Company_Counterpart__c=='User'){
                con.companyCounterPart=c.Company_Counterpart_User__r.name;
            }
            else{
                con.companyCounterPart=c.Company_Counterpart_Contact__r.name;
            }
            try{
            	//con.opportunityList=[Select ContactId,Role,Opportunity.Name,Opportunity.Amount,Opportunity.CloseDate,Opportunity.ExpectedRevenue,Opportunity.StageName from OpportunityContactRole where ContactId=:c.Id WITH SECURITY_ENFORCED];
            	con.opportunityList = c.OpportunityContactRoles;
            }
            catch (System.QueryException exp) {
                AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
                throw e;
            }
            if(con.opportunityList.size()>0){
                con.hasOpportunity=true;
            }
            else{
                con.hasOpportunity=false;
            }
            contactsList.add(con);
        }
        system.debug('contactsList : '+contactsList);
        return contactsList;
    }

    public class contactWraper{
        @AuraEnabled
        public decimal softCredit{get;set;}
        @AuraEnabled
        public decimal sponsorCredit{get;set;}
        @AuraEnabled
        public string name{get;set;}
        @AuraEnabled
        public string scoreLink{get;set;}
        @AuraEnabled
        public string relationshipType{get;set;}
        @AuraEnabled
        public string relationshipScore{get;set;}
        @AuraEnabled
        public string companyCounterPart{get;set;}
        @AuraEnabled
        public Id Id{get;set;}
        @AuraEnabled
        public String description{get;set;}
        @AuraEnabled
        public String linkedIn{get;set;}
        @AuraEnabled
        public string recordLink{get;set;}
        @AuraEnabled
        public List<OpportunityContactRole> opportunityList{get;set;}
        @AuraEnabled
        public Boolean hasOpportunity{get;set;}
    }
}