force-app/main/default/objects/Account/fields/Strategic_Account__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Strategic Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Health_Metrics__c/Account_Health_Metrics__c.object-meta.xml
<CustomObject>
    <label>Account Health Metrics</label>
    <nameField>
        <displayFormat>AHM-{0000}</displayFormat>
        <label>Account Health Metrics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Health Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Health_Metrics__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Health Metrics</relationshipLabel>
    <relationshipName>Account_Health_Metrics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Health_Metrics__c/fields/Column_1__c.field-meta.xml
<CustomField>
    <fullName>Column_1__c</fullName>
    <label>Column 1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Health_Metrics__c/fields/Column_2__c.field-meta.xml
<CustomField>
    <fullName>Column_2__c</fullName>
    <label>Column 2</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Health_Metrics__c/fields/Health_Score_Date__c.field-meta.xml
<CustomField>
    <fullName>Health_Score_Date__c</fullName>
    <label>Health Score Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Target__c/Account_Target__c.object-meta.xml
<CustomObject>
    <label>Account Target</label>
    <nameField>
        <label>Account Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Target__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Targets</relationshipLabel>
    <relationshipName>Account_Targets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Target__c/fields/Expected_Target__c.field-meta.xml
<CustomField>
    <fullName>Expected_Target__c</fullName>
    <label>Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Target__c/fields/Target_Year__c.field-meta.xml
<CustomField>
    <fullName>Target_Year__c</fullName>
    <label>Year</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conf_Category__c/Conf_Category__c.object-meta.xml
<CustomObject>
    <label>Configuration Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conf_Category__c/fields/Available_Column_Names__c.field-meta.xml
<CustomField>
    <fullName>Available_Column_Names__c</fullName>
    <label>Available Column Names</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Conf_Category__c/fields/Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Category_Type__c</fullName>
    <label>Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Conf_Category__c/fields/Column_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Name__c</fullName>
    <label>Column Name</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/Configuration_Category_Detail__c.object-meta.xml
<CustomObject>
    <label>Configuration Category Detail</label>
    <nameField>
        <label>Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Category Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Column_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Name__c</fullName>
    <label>Column Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Configuration_Category__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Category__c</fullName>
    <label>Configuration Category</label>
    <referenceTo>Conf_Category__c</referenceTo>
    <relationshipName>Category_Configuration_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User/fields/Selected_Account_List__c.field-meta.xml
<CustomField>
    <fullName>Selected_Account_List__c</fullName>
    <label>Selected Account List</label>
    <length>131070</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Category_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Health</fullName>
    </customValue>
    <customValue>
        <fullName>Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Company Division</fullName>
    </customValue>
    <customValue>
        <fullName>Relationship Type</fullName>
    </customValue>
    <customValue>
        <fullName>Program Milestone</fullName>
    </customValue>
    <customValue>
        <fullName>Stakeholder Personality</fullName>
    </customValue>
    <customValue>
        <fullName>Budget</fullName>
    </customValue>
    <customValue>
        <fullName>Soft Credit Role</fullName>
    </customValue>
    <customValue>
        <fullName>Target</fullName>
    </customValue>
    <customValue>
        <fullName>Company Offerings</fullName>
    </customValue>
    <customValue>
        <fullName>Credit</fullName>
    </customValue>
    <customValue>
        <fullName>Tab Visibility</fullName>
    </customValue>
    <customValue>
        <fullName>Account Insight</fullName>
    </customValue>
    <customValue>
        <fullName>Bbbb</fullName>
        <isActive>false</isActive>
        <label>Bbbb</label>
    </customValue>
    <customValue>
        <fullName>Aaaa</fullName>
        <isActive>false</isActive>
        <label>Aaaa</label>
    </customValue>
    <description>Category Type Picklist values for Conf_Category_Name Object.</description>
    <masterLabel>Category Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/account_Home_Page_Controller_Test.cls
@isTest
public class account_Home_Page_Controller_Test {
      
    @testSetup static void DataSet(){
        Account acc = new Account(Name='Test Account',Strategic_Account__c=true);
        insert acc;

        Account acc2 = new Account(Name='Test Account 2',Strategic_Account__c=false);
        insert acc2;
        
        Account_Target__c target = new Account_Target__c(Name='Test Target',Account__c=acc.Id,Target_Year__c='2020',varasi_am__Fiscal_Month__c='March',Expected_Target__c=20000);
        insert target;
        Conf_Category__c config1 = new Conf_Category__c(Name='IT Services',Category_Type__c='Company Offerings',Available_Column_Names__c='varasi_am__Column_3__c');
        insert config1;
        Configuration_Category_Detail__c cDetail2 = new Configuration_Category_Detail__c(Column_Name__c='varasi_am__Column_2__c',Configuration_Category__c=config1.Id);
        insert cDetail2;
        Account_Target__c target2 = new Account_Target__c(Name='Test Target 2',Account__c=acc.Id,Target_Year__c='2021',varasi_am__Fiscal_Month__c='March',Expected_Target__c=20000);
        insert target2;
        Profile p2 = [SELECT Id FROM Profile WHERE Name='Solution Manager']; 
        /*User u = new User(
         ProfileId = p2.Id,
         Title = 'T',
         Email = 'testUser@varasi.com',
         LastName = 'testUser',
         CompanyName = 'Varasi',
         LanguageLocaleKey = 'en_US',
         Alias = 'A',
         Username = 'testUser@varasi.com',
         TimeZoneSidKey = 'America/Los_Angeles',
         EmailEncodingKey = 'UTF-8',
         LocaleSidKey = 'en_US'
		);
        insert u;*/
  		User u2 = new User(Alias = 'solUser', Email='testsoltionManUser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='SolManager', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p2.Id, 
        TimeZoneSidKey='America/Los_Angeles', UserName='testuserVarasi@testorg.com');
        insert u2;
        
      	Account_Health_Metrics__c ahm = new Account_Health_Metrics__c(Account__c=acc.Id,Column_1__c='4',Column_2__c='5',Health_Score_Date__c=System.today());
        Account_Health_Helper.saveHealthRecord(ahm);
    }

     static testMethod void testGetYearList(){
        List<String> yearList = account_Home_Page_Controller.getYearList();
        System.assertEquals(true,yearList.size()>0);
    }
   static testMethod void testGetMetaData(){
    	acct_Mgmt_Controller.getMetaData();
        System.assertEquals(true,true);
    }
    static testMethod void testGetYearExceptionList(){
        User solManUser = [SELECT id FROM User WHERE Email='testsoltionManUser@testorg.com'];
		System.runAs(solManUser) 
        {
            Test.startTest();
			try{
				List<String> yearList = account_Home_Page_Controller.getYearList();
			}
			catch(Exception e){
				System.assertEquals(true,e.getMessage().contains('Error')||e.getMessage().contains('exception'));  
			}
			Test.stopTest();
        }
    }

    static testMethod void getPeopleViewTest(){
        List<Account> a = [SELECT Id FROM Account WHERE Name='Test Account' WITH SECURITY_ENFORCED LIMIT 1];
        List<String> idsList = new List<String>();
        idsList.add(a.get(0).Id);
        List<account_Home_Page_Controller.UserWrapper> data = account_Home_Page_Controller.getPeopleView('2020',idsList);
        System.assert(true,data.size()>0);
    }
     static testMethod void getAccountListTest(){
        List<Map<String,String>> acctData = account_Home_Page_Controller.getAccountList(true);
        System.assertEquals(true,acctData.size()>0);
    }
    
    static testMethod void getAccountListExceptionTest(){
        User solManUser = [SELECT id FROM User WHERE Email='testsoltionManUser@testorg.com'];
		System.runAs(solManUser) 
        {
            Test.startTest();
			try{
				List<Map<String,String>> acctData = account_Home_Page_Controller.getAccountList(true);
			}
			catch(Exception e){
				System.assertEquals(true,e.getMessage().contains('Error')||e.getMessage().contains('Insufficient permissions'));  
			}
			Test.stopTest();
        }
    }

     static testMethod void saveSelectedAcctsNUsersTest(){
        Account a;
        // try{
            a = [SELECT Id FROM Account WITH SECURITY_ENFORCED LIMIT 1];
        // }
        // catch (System.QueryException exp) {
        //     AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
        //     throw e;
        // }
        account_Home_Page_Controller.saveSelectedAcctsNUsers(a.Id);
        User u;
        try{
            u=[Select Id,Selected_Account_List__c from User WITH SECURITY_ENFORCED LIMIT 1];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        System.assertEquals(null, u.Selected_Account_List__c);    
    }
    
    static testMethod void saveSelectedAcctsNUsersExceptionTest(){
        Account a;
        // try{
            a = [SELECT Id FROM Account WITH SECURITY_ENFORCED LIMIT 1];
        // }
        // catch (System.QueryException exp) {
        //     AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
        //     throw e;
        // }
        User solManUser = [SELECT id FROM User WHERE Email='testsoltionManUser@testorg.com'];
		System.runAs(solManUser) 
        {
            Test.startTest();
			try{
				account_Home_Page_Controller.saveSelectedAcctsNUsers(a.Id);
			}
			catch(Exception e){
				System.assertEquals(true,e.getMessage().contains('Error')||e.getMessage().contains('exception'));  
			}
			Test.stopTest();
        }  
    }


    static testMethod void testGetCompanyOfferings(){
    	List<account_Home_Page_Controller.CategWrap> mList =  account_Home_Page_Controller.getCompanyOfferings();
        System.assertEquals(true,mList.size()>0);
    }

     static testMethod void getUserSortedAccountsTest(){
        List<account_Home_Page_Controller.UserHomeWrapper> userAcctsData = account_Home_Page_Controller.getUserSortedAccounts();
        System.assertEquals(true,userAcctsData.size()>0);
    }
    
    static testMethod void getUserSortedAccountsExceptionTest(){
        User solManUser = [SELECT id FROM User WHERE Email='testsoltionManUser@testorg.com'];
		System.runAs(solManUser) 
        {
            Test.startTest();
			try{
				List<account_Home_Page_Controller.UserHomeWrapper> userAcctsData = account_Home_Page_Controller.getUserSortedAccounts();
			}
			catch(Exception e){
				System.assertEquals(true,e.getMessage().contains('Error')||e.getMessage().contains('exception'));  
			}
			Test.stopTest();
        }
    }
    
    
     static testMethod void updateStrategicAcctsTest(){
        List<Account> acctList = new List<Account>();
        try{
            acctList = [SELECT Id FROM Account WHERE Strategic_Account__c=true WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        List<Id> ids = new List<Id>{acctList[0].Id};
        account_Home_Page_Controller.updateStrategicAccts(ids,true);       
        System.assertEquals(acctList.size(),ids.size());
    }
    
    static testMethod void updateStrategicAcctsExceptionTest(){
        List<Account> acctList = new List<Account>();
        try{
            acctList = [SELECT Id FROM Account WHERE Strategic_Account__c=true WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        List<Id> ids = new List<Id>{acctList[0].Id};
        User solManUser = [SELECT id FROM User WHERE Email='testsoltionManUser@testorg.com'];
		System.runAs(solManUser) 
        {
            Test.startTest();
			try{
				account_Home_Page_Controller.updateStrategicAccts(ids,true);     
			}
			catch(Exception e){
				System.assertEquals(true,e.getMessage().contains('Error')||e.getMessage().contains('exception'));  
			}
			Test.stopTest();
        }
    }

}