force-app/main/default/objects/Account_Goal__c/Account_Goal__c.object-meta.xml
<CustomObject>
    <label>Account Goal</label>
    <nameField>
        <label>Account Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Goal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Goal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Goal</relationshipLabel>
    <relationshipName>Account_Goal</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_1__c.field-meta.xml
<CustomField>
    <fullName>Column_1__c</fullName>
    <label>Column 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Target_Year__c.field-meta.xml
<CustomField>
    <fullName>Target_Year__c</fullName>
    <label>Year</label>
    <length>254</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conf_Category__c/Conf_Category__c.object-meta.xml
<CustomObject>
    <label>Configuration Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conf_Category__c/fields/Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Category_Type__c</fullName>
    <label>Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Conf_Category__c/fields/Column_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Name__c</fullName>
    <label>Column Name</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/Configuration_Category_Detail__c.object-meta.xml
<CustomObject>
    <label>Configuration Category Detail</label>
    <nameField>
        <label>Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Category Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Column_Name_2__c.field-meta.xml
<CustomField>
    <fullName>Column_Name_2__c</fullName>
    <label>Column Name 2</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Column_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Name__c</fullName>
    <label>Column Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Configuration_Category__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Category__c</fullName>
    <label>Configuration Category</label>
    <referenceTo>Conf_Category__c</referenceTo>
    <relationshipName>Category_Configuration_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Category_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Health</fullName>
    </customValue>
    <customValue>
        <fullName>Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Company Division</fullName>
    </customValue>
    <customValue>
        <fullName>Relationship Type</fullName>
    </customValue>
    <customValue>
        <fullName>Program Milestone</fullName>
    </customValue>
    <customValue>
        <fullName>Stakeholder Personality</fullName>
    </customValue>
    <customValue>
        <fullName>Budget</fullName>
    </customValue>
    <customValue>
        <fullName>Soft Credit Role</fullName>
    </customValue>
    <customValue>
        <fullName>Target</fullName>
    </customValue>
    <customValue>
        <fullName>Company Offerings</fullName>
    </customValue>
    <customValue>
        <fullName>Credit</fullName>
    </customValue>
    <customValue>
        <fullName>Tab Visibility</fullName>
    </customValue>
    <customValue>
        <fullName>Account Insight</fullName>
    </customValue>
    <customValue>
        <fullName>Bbbb</fullName>
        <isActive>false</isActive>
        <label>Bbbb</label>
    </customValue>
    <customValue>
        <fullName>Aaaa</fullName>
        <isActive>false</isActive>
        <label>Aaaa</label>
    </customValue>
    <description>Category Type Picklist values for Conf_Category_Name Object.</description>
    <masterLabel>Category Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Account_Goal_Helper_Test.cls
@isTest
public class Account_Goal_Helper_Test {
	
    @testSetup
    public static void dataSetup(){
        Account accnt=new Account(Name='New Account');
        insert accnt;
        Conf_Category__c config = new Conf_Category__c(Name='New Target',Category_Type__c='Target',Column_Name_2__c='is_Max_3__c');
        insert config;
        Configuration_Category_Detail__c cDetail = new Configuration_Category_Detail__c(Column_Name__c='Column_1__c',Configuration_Category__c=config.Id);
        insert cDetail;
        Account_Goal__c goal = new Account_Goal__c(Name='goal 1',Account__c=accnt.Id,Column_1__c='50',varasi_am__Target_Year__c='2021');
        insert goal;  
         Profile p2 = [SELECT Id FROM Profile WHERE Name='Solution Manager']; 
  		User u2 = new User(Alias = 'solUser', Email='testsoltionManUser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='SolManager', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p2.Id, 
        TimeZoneSidKey='America/Los_Angeles', UserName='testuserVarasi@testorg.com');
        insert u2;
    }
    
    static testMethod void getConfigDataTest(){
        Account acc;
        try{
            acc=[Select Id,Name from Account where Name='New Account' WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        List<Account_Goal_Helper.categWrapper> configData = Account_Goal_Helper.getConfigData(acc.Id);
        System.assertEquals(1, configData.size());
    }
    
    static testMethod void getConfigDataExceptionTest(){
        Account acc;
        try{
            acc=[Select Id,Name from Account where Name='New Account' WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        User solManUser = [SELECT id FROM User WHERE Email='testsoltionManUser@testorg.com'];
		System.runAs(solManUser) 
        {
            Test.startTest();
			try{
				List<Account_Goal_Helper.categWrapper> configData = Account_Goal_Helper.getConfigData(acc.Id);
			}
			catch(Exception e){
				System.assertEquals(true,e.getMessage().contains('Error')||e.getMessage().contains('exception'));  
			}
			Test.stopTest();
        }
    }
    
    // static testMethod void getGoalDataTest(){
    //     Account_Goal__c goal = [Select Id,Name from Account_Goal__c where Name='goal 1'];
    //     List<Account_Goal_Helper.goalWrapper> goalData = Account_Goal_Helper.getGoalData(goal.Id);
    //     System.assertEquals(1,goalData.size());
    // }
    
    static testMethod void getGoalRecsTest(){
        Account acc;
        List<Account_Goal__c> expectedGoals;
        try{
            acc=[Select Id,Name from Account where Name='New Account'];
            expectedGoals = [Select Id,Name,Account__r.Name,Account__c,Target_Year__c FROM Account_Goal__c WHERE 
            Account__c =: acc.Id  WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        List<Account_Goal__c> actualGoals = Account_Goal_Helper.getGoalRecs(acc.Id);
        System.assertEquals(expectedGoals, actualGoals);  
    }
    
    static testMethod void getGoalRecsExceptionTest(){
        Account acc;
        List<Account_Goal__c> expectedGoals;
        try{
            acc=[Select Id,Name from Account where Name='New Account'];
            expectedGoals = [Select Id,Name,Account__r.Name,Account__c,Target_Year__c FROM Account_Goal__c WHERE 
            Account__c =: acc.Id  WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        User solManUser = [SELECT id FROM User WHERE Email='testsoltionManUser@testorg.com'];
		System.runAs(solManUser) 
        {
            Test.startTest();
			try{
				 List<Account_Goal__c> actualGoals = Account_Goal_Helper.getGoalRecs(acc.Id);
			}
			catch(Exception e){
				System.assertEquals(true,e.getMessage().contains('Error')||e.getMessage().contains('exception'));  
			}
			Test.stopTest();
        } 
    }
    
    static testMethod void getConfigData2Test(){
        Account_Goal__c goal;
        try{
            goal = [Select Id,Name from Account_Goal__c where Name='goal 1' WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        List<Account_Goal_Helper.categWrapper> configData = Account_Goal_Helper.getConfigData2(goal.Id);
        //configData.add(new Account_Goal_Helper.categWrapper());
        Account_Goal_Helper.saveGoalData(configData);
        System.assertEquals(1, configData.size());
    }
    
    static testMethod void getConfigData2ExceptionTest(){
        Account_Goal__c goal;
        try{
            goal = [Select Id,Name from Account_Goal__c where Name='goal 1' WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        User solManUser = [SELECT id FROM User WHERE Email='testsoltionManUser@testorg.com'];
		System.runAs(solManUser) 
        {
            Test.startTest();
			try{
				List<Account_Goal_Helper.categWrapper> configData = Account_Goal_Helper.getConfigData2(goal.Id);
        //configData.add(new Account_Goal_Helper.categWrapper());
        Account_Goal_Helper.saveGoalData(configData);
			}
			catch(Exception e){
				System.assertEquals(true,e.getMessage().contains('Error')||e.getMessage().contains('exception'));  
			}
			Test.stopTest();
        }
    }
}