force-app/main/default/objects/Account_Goal__c/Account_Goal__c.object-meta.xml
<CustomObject>
    <label>Account Goal</label>
    <nameField>
        <label>Account Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Goal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Goal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Goal</relationshipLabel>
    <relationshipName>Account_Goal</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_10__c.field-meta.xml
<CustomField>
    <fullName>Column_10__c</fullName>
    <label>Column 10</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_11__c.field-meta.xml
<CustomField>
    <fullName>Column_11__c</fullName>
    <label>Column 11</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_12__c.field-meta.xml
<CustomField>
    <fullName>Column_12__c</fullName>
    <label>Column 12</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_13__c.field-meta.xml
<CustomField>
    <fullName>Column_13__c</fullName>
    <label>Column 13</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_14__c.field-meta.xml
<CustomField>
    <fullName>Column_14__c</fullName>
    <label>Column 14</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_15__c.field-meta.xml
<CustomField>
    <fullName>Column_15__c</fullName>
    <label>Column 15</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_16__c.field-meta.xml
<CustomField>
    <fullName>Column_16__c</fullName>
    <label>Column 16</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_17__c.field-meta.xml
<CustomField>
    <fullName>Column_17__c</fullName>
    <label>Column 17</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_18__c.field-meta.xml
<CustomField>
    <fullName>Column_18__c</fullName>
    <label>Column 18</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_19__c.field-meta.xml
<CustomField>
    <fullName>Column_19__c</fullName>
    <label>Column 19</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_1__c.field-meta.xml
<CustomField>
    <fullName>Column_1__c</fullName>
    <label>Column 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_20__c.field-meta.xml
<CustomField>
    <fullName>Column_20__c</fullName>
    <label>Column 20</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_21__c.field-meta.xml
<CustomField>
    <fullName>Column_21__c</fullName>
    <label>Column 21</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_22__c.field-meta.xml
<CustomField>
    <fullName>Column_22__c</fullName>
    <label>Column 22</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_23__c.field-meta.xml
<CustomField>
    <fullName>Column_23__c</fullName>
    <label>Column 23</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_24__c.field-meta.xml
<CustomField>
    <fullName>Column_24__c</fullName>
    <label>Column 24</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_25__c.field-meta.xml
<CustomField>
    <fullName>Column_25__c</fullName>
    <label>Column 25</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_26__c.field-meta.xml
<CustomField>
    <fullName>Column_26__c</fullName>
    <label>Column 26</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_27__c.field-meta.xml
<CustomField>
    <fullName>Column_27__c</fullName>
    <label>Column 27</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_28__c.field-meta.xml
<CustomField>
    <fullName>Column_28__c</fullName>
    <label>Column 28</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_29__c.field-meta.xml
<CustomField>
    <fullName>Column_29__c</fullName>
    <label>Column 29</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_2__c.field-meta.xml
<CustomField>
    <fullName>Column_2__c</fullName>
    <label>Column 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_30__c.field-meta.xml
<CustomField>
    <fullName>Column_30__c</fullName>
    <label>Column 30</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_31__c.field-meta.xml
<CustomField>
    <fullName>Column_31__c</fullName>
    <label>Column 31</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_32__c.field-meta.xml
<CustomField>
    <fullName>Column_32__c</fullName>
    <label>Column 32</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_33__c.field-meta.xml
<CustomField>
    <fullName>Column_33__c</fullName>
    <label>Column 33</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_34__c.field-meta.xml
<CustomField>
    <fullName>Column_34__c</fullName>
    <label>Column 34</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_35__c.field-meta.xml
<CustomField>
    <fullName>Column_35__c</fullName>
    <label>Column 35</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_36__c.field-meta.xml
<CustomField>
    <fullName>Column_36__c</fullName>
    <label>Column 36</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_37__c.field-meta.xml
<CustomField>
    <fullName>Column_37__c</fullName>
    <label>Column 37</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_38__c.field-meta.xml
<CustomField>
    <fullName>Column_38__c</fullName>
    <label>Column 38</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_39__c.field-meta.xml
<CustomField>
    <fullName>Column_39__c</fullName>
    <label>Column 39</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_3__c.field-meta.xml
<CustomField>
    <fullName>Column_3__c</fullName>
    <label>Column 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_40__c.field-meta.xml
<CustomField>
    <fullName>Column_40__c</fullName>
    <label>Column 40</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_41__c.field-meta.xml
<CustomField>
    <fullName>Column_41__c</fullName>
    <label>Column 41</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_42__c.field-meta.xml
<CustomField>
    <fullName>Column_42__c</fullName>
    <label>Column 42</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_43__c.field-meta.xml
<CustomField>
    <fullName>Column_43__c</fullName>
    <label>Column 43</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_44__c.field-meta.xml
<CustomField>
    <fullName>Column_44__c</fullName>
    <label>Column 44</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_45__c.field-meta.xml
<CustomField>
    <fullName>Column_45__c</fullName>
    <label>Column 45</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_46__c.field-meta.xml
<CustomField>
    <fullName>Column_46__c</fullName>
    <label>Column 46</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_47__c.field-meta.xml
<CustomField>
    <fullName>Column_47__c</fullName>
    <label>Column 47</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_48__c.field-meta.xml
<CustomField>
    <fullName>Column_48__c</fullName>
    <label>Column 48</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_49__c.field-meta.xml
<CustomField>
    <fullName>Column_49__c</fullName>
    <label>Column 49</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_4__c.field-meta.xml
<CustomField>
    <fullName>Column_4__c</fullName>
    <label>Column 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_5__c.field-meta.xml
<CustomField>
    <fullName>Column_5__c</fullName>
    <label>Column 5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_6__c.field-meta.xml
<CustomField>
    <fullName>Column_6__c</fullName>
    <label>Column 6</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_7__c.field-meta.xml
<CustomField>
    <fullName>Column_7__c</fullName>
    <label>Column 7</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_8__c.field-meta.xml
<CustomField>
    <fullName>Column_8__c</fullName>
    <label>Column 8</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Column_9__c.field-meta.xml
<CustomField>
    <fullName>Column_9__c</fullName>
    <label>Column 9</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Goal__c/fields/Target_Year__c.field-meta.xml
<CustomField>
    <fullName>Target_Year__c</fullName>
    <label>Year</label>
    <length>254</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conf_Category__c/Conf_Category__c.object-meta.xml
<CustomObject>
    <label>Configuration Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conf_Category__c/fields/Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Category_Type__c</fullName>
    <label>Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Conf_Category__c/fields/Column_Name_3__c.field-meta.xml
<CustomField>
    <fullName>Column_Name_3__c</fullName>
    <label>Column Name 3</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conf_Category__c/fields/Column_Name_4__c.field-meta.xml
<CustomField>
    <fullName>Column_Name_4__c</fullName>
    <label>Column Name 4</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conf_Category__c/fields/Column_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Name__c</fullName>
    <label>Column Name</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conf_Category__c/fields/is_Max_1__c.field-meta.xml
<CustomField>
    <fullName>is_Max_1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Max 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Conf_Category__c/fields/Progress_Tracker__c.field-meta.xml
<CustomField>
    <fullName>Progress_Tracker__c</fullName>
    <label>Progress Tracker</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conf_Category__c/fields/Target_Limit__c.field-meta.xml
<CustomField>
    <fullName>Target_Limit__c</fullName>
    <label>Target Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/Configuration_Category_Detail__c.object-meta.xml
<CustomObject>
    <label>Configuration Category Detail</label>
    <nameField>
        <label>Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Category Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Column_Name_2__c.field-meta.xml
<CustomField>
    <fullName>Column_Name_2__c</fullName>
    <label>Column Name 2</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Column_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Name__c</fullName>
    <label>Column Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Configuration_Category__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Category__c</fullName>
    <label>Configuration Category</label>
    <referenceTo>Conf_Category__c</referenceTo>
    <relationshipName>Category_Configuration_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Category_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Health</fullName>
    </customValue>
    <customValue>
        <fullName>Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Company Division</fullName>
    </customValue>
    <customValue>
        <fullName>Relationship Type</fullName>
    </customValue>
    <customValue>
        <fullName>Program Milestone</fullName>
    </customValue>
    <customValue>
        <fullName>Stakeholder Personality</fullName>
    </customValue>
    <customValue>
        <fullName>Budget</fullName>
    </customValue>
    <customValue>
        <fullName>Soft Credit Role</fullName>
    </customValue>
    <customValue>
        <fullName>Target</fullName>
    </customValue>
    <customValue>
        <fullName>Company Offerings</fullName>
    </customValue>
    <customValue>
        <fullName>Credit</fullName>
    </customValue>
    <customValue>
        <fullName>Tab Visibility</fullName>
    </customValue>
    <customValue>
        <fullName>Account Insight</fullName>
    </customValue>
    <customValue>
        <fullName>Bbbb</fullName>
        <isActive>false</isActive>
        <label>Bbbb</label>
    </customValue>
    <customValue>
        <fullName>Aaaa</fullName>
        <isActive>false</isActive>
        <label>Aaaa</label>
    </customValue>
    <description>Category Type Picklist values for Conf_Category_Name Object.</description>
    <masterLabel>Category Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Account_Goal_Helper.cls
public with sharing class Account_Goal_Helper {
    public class goalWrapper{
        @AuraEnabled
        public Conf_Category__c configCat {get;set;}
        @AuraEnabled
        public Decimal progressTrackerValue {get;set;}
        @AuraEnabled
        public String variant {get;set;}
        
    }

    @AuraEnabled(cacheable=true)
    public static List<CategWrapper> getConfigData(String recordId){
        // List<Conf_Category__c> configData = [SELECT Id,Name,Category_Type__c,Column_Name__c,Column_Name_2__c,Column_Name_3__c,
        // Column_Name_4__ FROM Conf_Category__c WHERE Category_Type__c='Target'];
        // return configData;
        List<Conf_Category__c> categs;
        try{
            categs = [Select Id,Name,Category_Type__c,(Select id,name,Column_Name__c from Category_Configuration_Details__r) FROM Conf_Category__c WHERE Category_Type__c='Target' WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        List<CategWrapper> categList= new List<CategWrapper>();
        for(Conf_Category__c categ:categs){
            CategWrapper c =new CategWrapper();
            c.Id=categ.Id;
            c.name=categ.name;
            c.goalId=null;
            c.accntId=recordId;
            c.goalYear=null;
            c.goalName=null;
            List<subCategWrapper> subCategList= new List<subCategWrapper>();
            for(Configuration_Category_Detail__c detail: categ.Category_Configuration_Details__r){
                subCategWrapper s=new subCategWrapper();
                s.Id=detail.id;
                s.name=detail.name;
                s.colName=detail.Column_Name__c;
                s.goalValue=null;
                s.isMax=null;
                s.currentValue=null;
                subCategList.add(s);
            }
            c.subCategs=subCategList;
            categList.add(c);
        }
        return categList;
    }

    // @AuraEnabled(cacheable=true)
    // public static List<goalWrapper> getGoalData(String recId){
    //     List<Conf_Category__c> configData = [SELECT Id,Name,Category_Type__c,Column_Name__c,Column_Name_2__c,Column_Name_3__c,
    //     Column_Name_4__c,Target_Limit__c    ,is_Max_1__c,Progress_Tracker__c  FROM Conf_Category__c WHERE Category_Type__c='Target'];
    //     Account_Goal__c goal = [SELECT Id,Name,Account__c,Target_Year__c FROM Account_Goal__c WHERE 
    //     Id =: recId];
    //     List<goalWrapper> gWrapper = new List<goalWrapper>();
    //     for(Conf_Category__c c:configData){
    //         goalWrapper g = new goalWrapper();
    //         g.configCat = c;
    //         Decimal trackerVal = (Decimal)goal.get(c.Progress_Tracker__c);
    //         Boolean isMax = (Boolean)goal.get(c.Column_Name_2__c);
    //         g.progressTrackerValue = trackerVal;
    //         if(g.progressTrackerValue >=100){
    //             g.progressTrackerValue = 100;
    //         }
    //         if(trackerVal>=100 && isMax == TRUE){
    //             g.variant = 'warning';
    //         }
    //         else{
    //             g.variant = 'base-autocomplete';
    //         }
    //         gWrapper.add(g);
    //     }
    //     System.debug('gWrapper'+gWrapper);
    //     return gWrapper;
    // }

    @AuraEnabled(cacheable=true)
    public static List<Account_Goal__c> getGoalRecs(String acctId){
        List<Account_Goal__c> recs;
        try{
            recs = [Select Id,Name,Account__r.Name,Account__c,Target_Year__c FROM Account_Goal__c WHERE 
            Account__c =: acctId WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        return recs;
    }


    @AuraEnabled(cacheable=true)
    public static List<CategWrapper> getConfigData2(String recordId){
        Account_Goal__c budgetRec;
        List<Conf_Category__c> categs;
        try{
            budgetRec = [Select id,name,Account__c,Column_1__c,Column_2__c,Column_3__c,Column_4__c,Column_5__c,Column_6__c,Column_7__c,Column_8__c,Column_9__c,Column_10__c,
                                        Column_11__c,Column_12__c,Column_13__c,Column_14__c,Column_15__c,Column_16__c,Column_17__c,Column_18__c,Column_19__c,
                                        Column_20__c,Column_21__c,Column_22__c,Column_23__c,Column_24__c,Column_25__c,Column_26__c,Column_27__c,Column_28__c,Column_29__c,
                                        Column_30__c,Column_31__c,Column_32__c,Column_33__c,Column_34__c,Column_35__c,Column_36__c,Column_37__c,Column_38__c,Column_39__c,
                                        Column_40__c,Column_41__c,Column_42__c,Column_43__c,Column_44__c,Column_45__c,Column_46__c,Column_47__c,Column_48__c,Column_49__c,Column_50__c
                                                from Account_Goal__c
                                                where id=:recordId WITH SECURITY_ENFORCED];
            categs = [Select Id,Name,Category_Type__c,(Select id,name,Column_Name__c from Category_Configuration_Details__r) FROM Conf_Category__c WHERE Category_Type__c='Target' WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        List<CategWrapper> categList= new List<CategWrapper>();
        for(Conf_Category__c categ:categs){
            CategWrapper c =new CategWrapper();
            c.Id=categ.Id;
            c.name=categ.name;
            c.goalId=recordId;
            c.accntId=budgetRec.Account__c;
            List<subCategWrapper> subCategList= new List<subCategWrapper>();
            for(Configuration_Category_Detail__c detail: categ.Category_Configuration_Details__r){
                subCategWrapper s=new subCategWrapper();
                s.Id=detail.id;
                s.name=detail.name;
                s.colName=detail.Column_Name__c;
                if(budgetRec!=null){
                    List<String> columnValues=budgetRec.get(detail.Column_Name__c) == null ? null : string.valueOf(budgetRec.get(detail.Column_Name__c)).split('~');
                    if(columnValues!=null){
                        if(columnValues.size()>0){
                            s.goalValue=columnValues[0]=='null'?null:Integer.valueOf(columnValues[0]);
                        }
                        if(columnValues.size()>1){
                            s.isMax=columnValues[1]=='null'?null:Boolean.valueOf(columnValues[1]);
                        }
                        if(columnValues.size()>2){
                            s.currentValue=columnValues[2]=='null'?null:Integer.valueOf(columnValues[2]);
                        }
                            Double tempGoalValue = s.goalValue != null ? s.goalValue : 1;
                            System.debug('tempGoalValue'+tempGoalValue);
                            Double tempCurrentValue = s.currentValue != null ? s.currentValue : 0;
                            System.debug('tempCurrentValue'+tempCurrentValue);
                            Double tempProgressValue = (tempCurrentValue/tempGoalValue) * 100;
                            System.debug('tempProgressValue'+tempProgressValue);
                            if(s.isMax == true && tempProgressValue>100){
                                s.variant = 'warning';
                            }else{
                                s.variant = 'base';
                            }
                            if(tempProgressValue <= 100){
                                s.progressValue = (Integer)tempProgressValue;
                            }else if(tempProgressValue > 100){
                                s.progressValue = 100;
                            }
                            System.debug('s.progressValue'+s.progressValue);
                    }
                    else{
                        s.goalValue=null;
                        s.isMax=null;
                        s.currentValue=null;
                        s.progressValue = 0;
                        s.variant = 'base';
                        System.debug('s.progressValue else 1'+s.progressValue);
                    }
                }
                else{
                    s.goalValue=null;
                    s.isMax=null;
                    s.currentValue=null;
                    s.progressValue = 0;
                    s.variant = 'base';
                    System.debug('s.progressValue else 2'+s.progressValue);
                }
                subCategList.add(s);
            }
            c.subCategs=subCategList;
            categList.add(c);
        }
        return categList;
    }
    public class CategWrapper{
        @AuraEnabled
        public  string Id {get;set;}
        @AuraEnabled
        public  string name {get;set;}
        @AuraEnabled
        public  String goalId {get;set;}
        @AuraEnabled
        public  String accntId {get;set;}
        @AuraEnabled
        public  String goalName {get;set;}
        @AuraEnabled
        public  String goalYear {get;set;}
        @AuraEnabled
        public  List<subCategWrapper> subCategs {get;set;}
    }
    public class subCategWrapper{
        @AuraEnabled
        public string Id {get;set;}
        @AuraEnabled
        public string colName {get;set;}
        @AuraEnabled
        public string name {get;set;}
        @AuraEnabled
        public Integer goalValue {get;set;}
        @AuraEnabled
        public Boolean isMax {get;set;}
        @AuraEnabled
        public Integer currentValue {get;set;}
        @AuraEnabled
        public Integer progressValue {get;set;}
        @AuraEnabled
        public String variant {get;set;}
    }

    public static Boolean isCreateable(Schema.SObjectType objectType, Set<String> fields){
        Boolean retVal = false;
        Map<String, SObjectField > fieldsMap = objectType.getDescribe().fields.getMap();
        for(String fname: fields){
            // If the fields do not exists then we can skip and there will be no change in the DB
            if(!fieldsMap.containsKey(fname) || fieldsMap.get(fname).getDescribe().isCreateable()){
                retVal = true;
            } else {
                return false;
            }
        }
        return retVal;
    }
    
    @AuraEnabled
    public static void createGoalData(List<CategWrapper> goals){
        System.debug('Goals :- '+goals);
        List<Account_Goal__c> accGoalsInsert = new List<Account_Goal__c>();
        Account_Goal__c accGoal = new Account_Goal__c();
        for (CategWrapper goal : goals) {
                accGoal.Account__c=goal.accntId;
                accGoal.name=goal.goalName;
                accGoal.Target_Year__c=goal.goalYear;
                for (Integer i = 0; i < goal.subCategs.size(); i++) {
                    string colValue = string.valueOf(goal.subCategs[i].goalValue)+ '~'+ string.valueOf(goal.subCategs[i].isMax)+'~'+ string.valueOf(goal.subCategs[i].currentValue);
                    accGoal.put(goal.subCategs[i].colName,colValue);
                }
        }
        system.debug('accGoal  :   '+accGoal);
        //List<String> fieldList = new List<String>{'Name','varasi_am__Account__c','varasi_am__Target_Year__c'};
            accGoalsInsert.add(accGoal);
        //accGoals.add(accGoal);
        if(accGoalsInsert.size()>0){
            acct_Mgmt_Controller.objectCreatableNew(accGoalsInsert);  
        }
        /*if(acct_Mgmt_Controller.objectUpdateable('Account_Goal__c',fieldList) && acct_Mgmt_Controller.objectCreatable('Account_Goal__c',fieldList)){
        	upsert accGoal;
        }*/
    }

    @AuraEnabled
    public static void saveGoalData(List<CategWrapper> goals){
        System.debug('Goals :- '+goals);
        List<Account_Goal__c> accGoalsUpdate = new List<Account_Goal__c>();
        Account_Goal__c accGoal = new Account_Goal__c();
        for (CategWrapper goal : goals) {
            accGoal.id=goal.goalId;
            for (Integer i = 0; i < goal.subCategs.size(); i++) {
                string colValue = string.valueOf(goal.subCategs[i].goalValue)+ '~'+ string.valueOf(goal.subCategs[i].isMax)+'~'+ string.valueOf(goal.subCategs[i].currentValue);
                accGoal.put(goal.subCategs[i].colName,colValue);
            }
        }
        system.debug('accGoal  :   '+accGoal);
        //List<String> fieldList = new List<String>{'Name','varasi_am__Account__c','varasi_am__Target_Year__c'};
        accGoalsUpdate.add(accGoal);
        //accGoals.add(accGoal);
        if(accGoalsUpdate.size()>0){
            acct_Mgmt_Controller.objectUpdatableNew(accGoalsUpdate);
        }
        /*if(acct_Mgmt_Controller.objectUpdateable('Account_Goal__c',fieldList) && acct_Mgmt_Controller.objectCreatable('Account_Goal__c',fieldList)){
        	upsert accGoal;
        }*/
    }
}