force-app/main/default/objects/Account_Health_Metrics__c/Account_Health_Metrics__c.object-meta.xml
<CustomObject>
    <label>Account Health Metrics</label>
    <nameField>
        <displayFormat>AHM-{0000}</displayFormat>
        <label>Account Health Metrics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Health Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Health_Metrics__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Health Metrics</relationshipLabel>
    <relationshipName>Account_Health_Metrics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Health_Metrics__c/fields/Column_1__c.field-meta.xml
<CustomField>
    <fullName>Column_1__c</fullName>
    <label>Column 1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Health_Metrics__c/fields/Column_2__c.field-meta.xml
<CustomField>
    <fullName>Column_2__c</fullName>
    <label>Column 2</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Health_Metrics__c/fields/Health_Score_Date__c.field-meta.xml
<CustomField>
    <fullName>Health_Score_Date__c</fullName>
    <label>Health Score Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Target__c/Account_Target__c.object-meta.xml
<CustomObject>
    <label>Account Target</label>
    <nameField>
        <label>Account Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Target__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Targets</relationshipLabel>
    <relationshipName>Account_Targets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Target__c/fields/Expected_Target__c.field-meta.xml
<CustomField>
    <fullName>Expected_Target__c</fullName>
    <label>Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Target__c/fields/Target_Year__c.field-meta.xml
<CustomField>
    <fullName>Target_Year__c</fullName>
    <label>Year</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conf_Category__c/Conf_Category__c.object-meta.xml
<CustomObject>
    <label>Configuration Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conf_Category__c/fields/Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Category_Type__c</fullName>
    <label>Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Conf_Category__c/fields/Column_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Name__c</fullName>
    <label>Column Name</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conf_Category__c/fields/Internal_Account__c.field-meta.xml
<CustomField>
    <fullName>Internal_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Internal Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Configuration Categories</relationshipLabel>
    <relationshipName>Configuration_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/Configuration_Category_Detail__c.object-meta.xml
<CustomObject>
    <label>Configuration Category Detail</label>
    <nameField>
        <label>Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Category Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Column_Name__c.field-meta.xml
<CustomField>
    <fullName>Column_Name__c</fullName>
    <label>Column Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Category_Detail__c/fields/Configuration_Category__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Category__c</fullName>
    <label>Configuration Category</label>
    <referenceTo>Conf_Category__c</referenceTo>
    <relationshipName>Category_Configuration_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Category_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Health</fullName>
    </customValue>
    <customValue>
        <fullName>Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Company Division</fullName>
    </customValue>
    <customValue>
        <fullName>Relationship Type</fullName>
    </customValue>
    <customValue>
        <fullName>Program Milestone</fullName>
    </customValue>
    <customValue>
        <fullName>Stakeholder Personality</fullName>
    </customValue>
    <customValue>
        <fullName>Budget</fullName>
    </customValue>
    <customValue>
        <fullName>Soft Credit Role</fullName>
    </customValue>
    <customValue>
        <fullName>Target</fullName>
    </customValue>
    <customValue>
        <fullName>Company Offerings</fullName>
    </customValue>
    <customValue>
        <fullName>Credit</fullName>
    </customValue>
    <customValue>
        <fullName>Tab Visibility</fullName>
    </customValue>
    <customValue>
        <fullName>Account Insight</fullName>
    </customValue>
    <customValue>
        <fullName>Bbbb</fullName>
        <isActive>false</isActive>
        <label>Bbbb</label>
    </customValue>
    <customValue>
        <fullName>Aaaa</fullName>
        <isActive>false</isActive>
        <label>Aaaa</label>
    </customValue>
    <description>Category Type Picklist values for Conf_Category_Name Object.</description>
    <masterLabel>Category Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Account_Target_Helper_Test.cls
@isTest
public class Account_Target_Helper_Test {

    @testSetup static void DataSet(){
        Account acc = new Account(Name='Test Account');
        insert acc;
        Account acc2 = new Account(Name='Internal Account');
        insert acc2;
        
        Account_Target__c target = new Account_Target__c(Name='Test Target',Account__c=acc.Id,Target_Year__c='2021',varasi_am__Fiscal_Month__c='March',Expected_Target__c=20000);
        insert target;
        
        Account_Target__c target2 = new Account_Target__c(Name='Test Target 2',Account__c=acc.Id,Target_Year__c='2021',varasi_am__Fiscal_Month__c='March',Expected_Target__c=20000);
        insert target2;
        
         Conf_Category__c config = new Conf_Category__c(Name='Revenue',Category_Type__c='Account Health');
        insert config;
        Conf_Category__c config2 = new Conf_Category__c(Name='Internal Account',Internal_Account__c=acc2.Id);
        insert config2;
        Conf_Category__c config3 = new Conf_Category__c(Name='Offerings',Category_Type__c='Company Offerings');
        insert config3;
        Configuration_Category_Detail__c configDetail = new Configuration_Category_Detail__c(Name='Revenue Rate',Configuration_Category__c=config.Id,Column_Name__c='varasi_am__Column_1__c'); 
        insert configDetail;
        Configuration_Category_Detail__c configDetail2 = new Configuration_Category_Detail__c(Name='Recurring Revenue',Configuration_Category__c=config.Id,Column_Name__c='varasi_am__Column_2__c'); 
        insert configDetail2;
        Configuration_Category_Detail__c configDetail3 = new Configuration_Category_Detail__c(Name='Stagnant Revenue',Configuration_Category__c=config.Id,Column_Name__c='varasi_am__Column_3__c'); 
        insert configDetail3;
        Configuration_Category_Detail__c configDetail4 = new Configuration_Category_Detail__c(Name='ETL Services',Configuration_Category__c=config3.Id,Column_Name__c='varasi_am__Column_4__c'); 
        insert configDetail4;
        Account_Health_Metrics__c ahm = new Account_Health_Metrics__c(Account__c=acc.Id,Column_1__c='4',Column_2__c='5',Health_Score_Date__c=System.today());
        Account_Health_Helper.saveHealthRecord(ahm);
        
        date d = date.newInstance(2020, 7 ,21);
        Opportunity opp = new Opportunity(Name='Test Opp',AccountId=acc.Id,CloseDate=d,StageName='Prospecting',Amount = 5000,Probability=50,varasi_am__Company_Offering_Category__c=config3.Id,varasi_am__Company_Offering_Sub_Category__c=configDetail4.Id); 
        insert opp;
        Profile p2 = [SELECT Id FROM Profile WHERE Name='Solution Manager']; 
  		User u2 = new User(Alias = 'solUser', Email='testsoltionManUser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='SolManager', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p2.Id, 
        TimeZoneSidKey='America/Los_Angeles', UserName='testuserVarasi@testorg.com');
        insert u2;
    }
    @isTest static void getConfigData(){
        List<Conf_Category__c> configs = Account_Target_Helper.getConfigData();
        System.assert(configs.size()==0);
    }
    
    @isTest static void getYearListTest(){
        Account acc;
        try{
            acc = [SELECT Id,Name FROM Account WHERE Name='Test Account' WITH SECURITY_ENFORCED LIMIT 1];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        List<Account_Target_Helper.YearWrapper> yearList = Account_Target_Helper.getYearList(acc.Id);
        System.assert(yearList.size()==3);
    }
    
    @isTest static void getFiscalYearTest(){
        String fiscalYear = Account_Target_Helper.getFiscalYear();
        System.assertEquals('2021', fiscalYear);
        String fiscalMonth = Account_Target_Helper.getFiscalMonth();
        System.assertEquals('March', fiscalMonth);
    }
    
    @isTest static void getTargetRecsTest(){
        Account acc;
        try{
            acc = [SELECT Id,Name FROM Account WHERE Name='Test Account' WITH SECURITY_ENFORCED LIMIT 1];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        List<Account_Target_Helper.accountTargetWrapper> targetList = Account_Target_Helper.getTargetRecs(acc.Id);
        System.assert(targetList.size()>0);
    }
    
    @isTest static void getAccountTargetRecsTest(){
        Account acc;
        try{
           acc= [SELECT Id,Name FROM Account WHERE Name='Test Account' WITH SECURITY_ENFORCED LIMIT 1];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        List<Account_Target__c> acctList = Account_Target_Helper.getAccountTargetRecs(acc.Id,'2021');
        System.assert(acctList.size()>0);
    }
    
     @isTest static void getTargetRecordsTest(){
        Account acc;
        try{
            acc = [SELECT Id,Name FROM Account WHERE Name='Test Account' WITH SECURITY_ENFORCED LIMIT 1];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        List<Account_Target__c> targetList = Account_Target_Helper.getTargetRecords(acc.Id,'2021');
        System.assert(targetList.size()>0);
         
        List<Account_Target__c> targetList2 = Account_Target_Helper.getTargetRecords(acc.Id);
        System.assert(targetList2.size()>0);
    }
    
     @isTest static void getActualAndPipelineTest(){
        Account acc;
        try{
            acc = [SELECT Id,Name FROM Account WHERE Name='Test Account' WITH SECURITY_ENFORCED LIMIT 1];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        Integer year=2020;
        Decimal actual = Account_Target_Helper.getActual(year,acc.Id);
        System.assertEquals(null, actual);
        Decimal pipeline = Account_Target_Helper.getPipeLine(year,acc.Id);
        System.assertEquals(2500, pipeline);
    }
    
    @isTest static void insertOppTriggerTest(){
        Account acc;
        Opportunity opp;
        try{
            acc = [SELECT Id,Name FROM Account WHERE Name='Test Account' WITH SECURITY_ENFORCED LIMIT 1];
            opp = [SELECT Id,Name FROM Opportunity WHERE Name='Test Opp' WITH SECURITY_ENFORCED LIMIT 1];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        opp.Probability = 1;
        update opp;
        Integer year=2020;
        Decimal actual = Account_Target_Helper.getPipeLine(year,acc.Id);
        System.assertEquals(50.0, actual);
        
    }
    
    @isTest static void updateOppTriggerTest(){
        date d = date.newInstance(2020, 7 ,21);
        Account acc;
        try{
            acc = [SELECT Id,Name FROM Account WHERE Name='Test Account' WITH SECURITY_ENFORCED LIMIT 1];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        Conf_Category__c config3 = [select id from Conf_Category__c where Category_Type__c='Company Offerings' limit 1];
        Configuration_Category_Detail__c configDetail4 =[select id from Configuration_Category_Detail__c where Configuration_Category__c=:config3.Id limit 1];
        Opportunity opp2 = new Opportunity(Name='Test Opp 2',AccountId=acc.Id,CloseDate=d,StageName='Prospecting',Amount = 5000,Probability=100,varasi_am__Company_Offering_Category__c=config3.Id,varasi_am__Company_Offering_Sub_Category__c=configDetail4.Id); 
        insert opp2;
        
    	date d2 = date.newInstance(2021, 8 ,21);
        opp2.CloseDate = d2;
        opp2.Probability = 60;
        update opp2;
        
        opp2.CloseDate = d;
        opp2.Probability = 100;
        update opp2;
        
       	opp2.Probability = 60;
        update opp2;
        Integer year=2020;
        Decimal actual = Account_Target_Helper.getPipeLine(year,acc.Id);
        System.assertEquals(5500.0, actual);
    }
    
    @isTest static void updateOppTriggerTest2(){
        date d = date.newInstance(2021, 2 ,21);
        Account acc;
        try{
            acc = [SELECT Id,Name FROM Account WHERE Name='Test Account' WITH SECURITY_ENFORCED LIMIT 1];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        Conf_Category__c config3 = [select id from Conf_Category__c where Category_Type__c='Company Offerings' limit 1];
        Configuration_Category_Detail__c configDetail4 =[select id from Configuration_Category_Detail__c where Configuration_Category__c=:config3.Id limit 1];
        Opportunity opp2 = new Opportunity(Name='Test Opp 2',AccountId=acc.Id,CloseDate=d,StageName='Prospecting',Amount = 5000,Probability=100,varasi_am__Company_Offering_Category__c=config3.Id,varasi_am__Company_Offering_Sub_Category__c=configDetail4.Id); 
        insert opp2;
        
    	date d2 = date.newInstance(2021, 8 ,21);
        opp2.CloseDate = d2;
        opp2.Probability = 60;
        update opp2;
        
        opp2.Probability = 100;
        update opp2;
        
        delete opp2;
        Integer year=2020;
        Decimal actual = Account_Target_Helper.getActual(year,acc.Id);
        System.assertEquals(null, actual);
    }
    
    @isTest static void acctHomePageTest(){
        List<Account> accs;
        try{
            accs = [Select Id from Account WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        List<String> accId=new List<String>();
        for(Account a:accs){
            accId.add(a.Id);
        }
        List<Integer> listOfData = account_Home_Page_Controller.getChartData(true,'2020',accId);
        System.debug('listOfData'+listOfData);
        System.assert(listOfData.size()>0);
        List<account_Home_Page_Controller.accountWrapper> acctWrap = account_Home_Page_Controller.getAccounts('2020',accId);
        System.debug('acctWrap'+acctWrap);
        System.assert(acctWrap.size()>0);  

    }
    
     @isTest static void peopleViewTest(){
        List<Account> accs;
        try{
            accs = [Select Id from Account WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        List<String> accId=new List<String>();
        for(Account a:accs){
            accId.add(a.Id);
        }
        List<account_Home_Page_Controller.UserWrapper> userWrap = account_Home_Page_Controller.getPeopleView('2020',accId); 
        System.assert(userWrap.size()>=0); 
    }
    
    @isTest static void getYearsTest(){
        List<String> years = Account_Target_Helper.getYears();
        System.assertEquals(1, years.size());
    }
    
    @isTest static void getFileUrlTest(){
        Account_Target__c target;
        try{
            target = [Select Id from Account_Target__c WITH SECURITY_ENFORCED LIMIT 1];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        String fileUrl = Account_Target_Helper.getFileUrl(target.Id);
        System.assertEquals(null,fileUrl);
        List<ContentVersion> docs = Account_Target_Helper.getDocument(target.Id);
        System.assertEquals(0,docs.size());
    }
    
    @isTest static void getAllAccountTargetRecsTest(){
        List<Account> accts;
        try{
            accts = [SELECT Id,Name FROM Account WITH SECURITY_ENFORCED];
        }
        catch (System.QueryException exp) {
            AuraHandledException e =  new AuraHandledException('Error Enforcing security:'+exp.getMessage());
            throw e;
        }
        List<Id> ids = new List<Id>{accts[0].Id,accts[1].Id};
        List<Account_Target_Helper.targetWrapper> targets = Account_Target_Helper.getAllAccountTargetRecs('2021',ids);
        System.assertEquals(1,targets.size());
    }
    
    
    
    
}